### ISSUE TITLE
Ignition : Why does it fail so hard ?

### ISSUE THREAD

**Issue by slallema** [coreos/bugs#1070]
Hello,
I'm playing a bit with ignition and of course during the writing of the json file I occasionally make some mistakes. 
The problem is that when ignition can't create a resource, it just fails and stop, leaving the server in a state where you can't ssh on it to debug. The only debug possibility is through console and that's painful.
I think it would be better to log the error and continue the boot.

That behavior would also solve my second problem : sometimes I install a new server and I create a DATA partition, sometimes that partition existed from a previous install and I just want to recover it. But if I don't force the wipeTable and the FS creation, ignition fails even if would have result in valid configuration by just ignoring the step.

what do you think ?

**Comment by crawford** [comment]
The reason Ignition fails hard is because the provisioning operation needs to be atomic. Either it all happens, or none of it happens. We learned the hard way through coreos-cloudinit that many users do not notice if there was a cloud-config error when the machine boots. When the provisioning is atomic, the operator can be certain that if they can SSH into the machine, it is in fact the machine they asked for, rather than a partially set up one. I am fairly convinced that this is the correct behavior, so it would take a pretty strong argument to convince me otherwise.

Now, that being said, I completely agree that debugging is a pain. I do think we can solve this without change the atomic nature of Ignition though. I've kicked around a few ideas like a simple SSH server that runs on failure or POSTing logs to a given endpoint in addition to the planned support for Ignition configs on https://coreos.com/validate. Opening up an SSH server makes me nervous, so I'm leaning toward the second option, but I'm curious if you have any ideas or preferences.

Regarding your second problem, I'm not convinced Ignition is behaving correctly here. The general idea is that a config describes a goal state, not necessarily the steps to be taken. Given that, if the config specifies an ext4 filesystem on /dev/sda1, and that is already the case, it would make sense that Ignition does nothing. During its development, we always started from a bare machine, so this case was never hit. I think it's reasonable to change this behavior but let me think about it a bit more before I commit.

**Comment by robszumski** [comment]
In general, can we just output to the console that is already set up? The goal on a platform like EC2 would be to see the failures in their cloud console.

Additionally, can we add a debug section to a config that is invoked when the process goes wrong? Options:

1. If there is a good chance your network is up, post to a location. Maybe the default is a gist if you provide a Github username? Is this a service that CoreOS runs?
2. Open up an SSH server with either a specific key or preset password
3. scp the file to another machine in order to avoid running an SSH server?

**Comment by crawford** [comment]
> In general, can we just output to the console that is already set up? The goal on a platform like EC2 would be to see the failures in their cloud console.

We already do that.

> Additionally, can we add a debug section to a config that is invoked when the process goes wrong?

We can't add it to the config. What happens if the config fails to parse?

> Options:

1. Wouldn't that require a GitHub password to accompany the username? Yikes.
2. That's possible.
3. That would require an SSH private key. Yikes.

**Comment by robszumski** [comment]
> 3. That would require an SSH private key. Yikes.

Or a password to a user that is unprivileged

**Comment by slallema** [comment]
@crawford I agree that it's probably safer to fail if something goes wrong. I like the idea of sending the logs somewhere else. I'm also considering collecting the console logs from the BMC (I've seen people using conserver for that).

On the second point, checking the existing partitions and fs would increase the complexity of ignition but I think it would be useful for instance to run another first_boot that would wipe the ROOT partition before reconfiguring everything but keep the other partitions. That would allow a fast complete reconfig of the host without losing DATA and without using too much network.

**Comment by crawford** [comment]
> Regarding your second problem, I'm not convinced Ignition is behaving correctly here. The general idea is that a config describes a goal state, not necessarily the steps to be taken. Given that, if the config specifies an ext4 filesystem on /dev/sda1, and that is already the case, it would make sense that Ignition does nothing. During its development, we always started from a bare machine, so this case was never hit. I think it's reasonable to change this behavior but let me think about it a bit more before I commit.

We're going to go ahead and add a `reuseExisting` flag (or something to that effect) to the filesystems. That will affect both the formatting of the filesystem and the population of its files.

**Comment by dgonyeo** [comment]
The `wipeFilesystem` flag, which enables reuse of existing filesystems, has been marged. This docs file has more information on its use: https://github.com/coreos/ignition/blob/master/doc/filesystems.md
