### ISSUE TITLE
cloud-init: Very slow cloud-config file parsing

### ISSUE THREAD

**Issue by albertdb** [coreos/bugs#1072]
Hi!

I have a quite big cloud-config file (~160000 lines, mainly due to three write_file) that takes almost 3 minutes to parse taking 100% CPU. This should be much faster, it's all about reading lines.

Am I missing something?

Thanks.

**Comment by crawford** [comment]
Wow, that's a pretty big config. It's not surprising that it takes that long to parse the config - YAML is a very complex language. I don't think there is much we can do to make _coreos-cloudinit_ faster, but I would be curious how Ignition performs with an equivalent config. Ignition uses JSON instead, which has a much simpler parser. There is also an [open proposal](https://github.com/coreos/bugs/issues/1067) to add support for downloading remote files to Ignition (which is probably what you eventually want).

Would you mind trying an Ignition config? Or can you share your config with me so that I can test?
