### ISSUE TITLE
Please tag AMIs

### ISSUE THREAD

**Issue by blalor** [coreos/bugs#111]
Please tag Amazon AMIs with channel, version, timestamp, etc.  For example, the current stable release looks like:

``` json
    {
      "VirtualizationType": "hvm",
      "Name": "CoreOS-stable-367.1.1-hvm",
      "Hypervisor": "xen",
      "ImageId": "ami-02a2766a",
      "State": "available",
      "BlockDeviceMappings": [
        {
          "DeviceName": "/dev/xvda",
          "Ebs": {
            "DeleteOnTermination": true,
            "SnapshotId": "snap-afd82903",
            "VolumeSize": 8,
            "VolumeType": "standard",
            "Encrypted": false
          }
        },
        {
          "DeviceName": "/dev/xvdb",
          "VirtualName": "ephemeral0"
        }
      ],
      "Architecture": "x86_64",
      "ImageLocation": "595879546273/CoreOS-stable-367.1.1-hvm",
      "RootDeviceType": "ebs",
      "OwnerId": "595879546273",
      "RootDeviceName": "/dev/xvda",
      "Public": true,
      "ImageType": "machine",
      "Description": "CoreOS stable 367.1.1 (HVM)"
    }
```

It would be helpful to have the following tags:
- channel: stable
- version: 367.1.1
- timestamp: Unix epoch or ISO8601 timestamp of release

This will make it easier to choose the most recent image for a given channel programmatically.

**Comment by jimmycuadra** [comment]
Is the code that publishes these AMIs open source? It doesn't seem the CoreOS team has time to do this themselves, but maybe someone in the community could help out.

**Comment by crawford** [comment]
@jimmycuadra yes it is. The main entry point is https://github.com/coreos/scripts/blob/master/oem/ami/prod.sh.

**Comment by bgilbert** [comment]
https://github.com/coreos/mantle/pull/540 reimplements the AMI publishing process inside `plume`.  The new implementation sets `Channel` and `Version` tags, but doesn't record the release timestamp because that isn't known when the AMIs are created.  The channel and version number should be sufficient to select the most recent image, but if you need the release timestamp, you can look it up in the [releases feed](https://coreos.com/releases/releases.json).

The new tags should start appearing in the next alpha release.  Thanks for the report!

**Comment by euank** [comment]
For anyone following this bug: it turns out tagging AMIs doesn't work like we want it to.

From [their docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html)

> You can tag public or shared resources, but the tags you assign are available only to your AWS account and not to the other accounts sharing the resource. 

As far as I can tell, there's no way to publish/share tags.
