### ISSUE TITLE
CoreOS official images RAW size too big

### ISSUE THREAD

**Issue by fnordahl** [coreos/bugs#1121]
When running VMs on top of Ceph RBD you will want to use RAW images and leverage the COW-functionality of Ceph RBD itself instead of on-disk formats like QCOW2.

From what I can tell the base layout would take up about 2393 MB in a flattened RAW image. However the image is padded and the actual raw image size is about 8500 MB.

CoreOS would be wonderful for cramming into those nano-instances, but the extra 6 GB padded to the images prohibits the use of the official images for this. Would it be possible to reduce the raw image size of the official images to be closer to the actually base layout disk usage?

**Comment by crawford** [comment]
To which image format are you specifically referring? The [raw disk image](http://alpha.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2) is 4.5 GB unpacked. Some of the image formats are going to be smaller than the others.

**Comment by fnordahl** [comment]
Thank you for the swift response! I'm referring to these images:
http://stable.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2
http://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2

Example of processed image:
<pre>$ wget http://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2
$ bunzip2 coreos_production_openstack_image.img.bz2 
$ qemu-img convert -f qcow2 -O raw coreos_production_openstack_image.img coreos_production_openstack_image.raw
$ # Simulate what would happen if I uploaded this to Ceph RBD with dd
$ dd if=coreos_production_openstack_image.raw of=coreos_production_openstack_image_flatten.raw bs=1M
$ du -h coreos_production_openstack_image_flatten.raw 
8.5G	coreos_production_openstack_image_flatten.raw
</pre>

Example of layout/usage from installed CoreOS image:
<pre>core@co ~ $ sudo sgdisk -p /dev/vda
Disk /dev/vda: 41943040 sectors, 20.0 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): E23F762A-EADC-404F-8C58-09D2EDEC1A47
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 41943006
Partitions will be aligned on 2048-sector boundaries
Total free space is 4062 sectors (2.0 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            4096          266239   128.0 MiB   EF00  EFI-SYSTEM
   2          266240          270335   2.0 MiB     EF02  BIOS-BOOT
   3          270336         2367487   1024.0 MiB  FFFF  USR-A
   4         2367488         4464639   1024.0 MiB  FFFF  USR-B
   6         4464640         4726783   128.0 MiB   8300  OEM
   7         4726784         4857855   64.0 MiB    FFFF  OEM-CONFIG
   9         4857856        41943006   17.7 GiB    FFFF  ROOT
core@co ~ $ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda9        18G   23M   17G   1% /
</pre>

**Comment by Tha-Robert** [comment]
I agree the openstack version should have a raw image as well.
Because now you cant even convert the image with qemu tools :/
I dont know if it is a bug in qemu-img convert or with the image.

<code>

$ qemu-img -V
qemu-img version 2.11.0
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

$ uname -v
Darwin Kernel Version 17.2.0

$ mount ./
/dev/disk1s1 on / (apfs, local, journaled)

$  wget https://beta.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2

$ date
Fri Dec 14 17:15:57 CET 2017

$ bunzip2 coreos_production_openstack_image.img.bz2

$ shasum coreos_production_openstack_image.img.org
ae2119c6f0390dc36f247f7016923ea85de5d8e6  coreos_production_openstack_image.img.org

$ cp -a coreos_production_openstack_image.img.org coreos_production_openstack_image.img
$ qemu-img convert -f qcow2 -O raw coreos_production_openstack_image.img.org coreos_production_openstack_image.bin
$ qemu-system-x86_64 -m 256 -nographic -hda coreos_production_openstack_image.img -boot c
SeaBIOS (version rel-1.11.0-0-g63451fca13-prebuilt.qemu-project.org)


iPXE (http://ipxe.org) 00:03.0 C980 PCI2.10 PnP PMM+0FF915A0+0FEF15A0 C980
                                                                               


Booting from Hard Disk...
GRUB loading....
Welcome to GRUB!
....

$ qemu-system-x86_64 -m 256 -nographic -hda coreos_production_openstack_image.bin -boot c

SeaBIOS (version rel-1.11.0-0-g63451fca13-prebuilt.qemu-project.org)


iPXE (http://ipxe.org) 00:03.0 C980 PCI2.10 PnP PMM+0FF915A0+0FEF15A0 C980
                                                                               


Booting from Hard Disk...
Boot failed: not a bootable disk
....

$ head -c 8192 coreos_production_openstack_i | hexdump -C
coreos_production_openstack_image.bin      coreos_production_openstack_image.img      coreos_production_openstack_image.img.org  
$ head -c 8192 coreos_production_openstack_image.bin | hexdump -C
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00002000

$ qemu-img info coreos_production_openstack_image.bin
image: coreos_production_openstack_image.bin
file format: raw
virtual size: 8.5G (9116319744 bytes)
disk size: 217M

$ qemu-img info coreos_production_openstack_image.img
image: coreos_production_openstack_image.img
file format: qcow2
virtual size: 8.5G (9116319744 bytes)
disk size: 785M
cluster_size: 65536
Format specific information:
    compat: 0.10
    refcount bits: 16

</code>

**Comment by ajeddeloh** [comment]
Fyi, it looks like [we build "mini" openstack images without a resized root partition](https://beta.release.core-os.net/amd64-usr/current/coreos_production_openstack_mini_image.img.bz2). Which might be of interest to you. We use the qemu tools to build the qcow images, so I'm surprised the converted raw doesn't work. We are on a slightly earlier version of the qemu tools (2.9.0).

Is this behavior new? Does using the qemu 2.9.x tools work?

**Comment by Tha-Robert** [comment]
No difference with the old qemu.

```
$ qemu-img -V
qemu-img version 2.9.0
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

$ qemu-img convert -f qcow2 -O raw coreos_production_openstack_image.img.org coreos_production_openstack_image.bin

$ qemu-system-x86_64 -m 256 -nographic -hda coreos_production_openstack_image.bin -boot c
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/qemu-system-x86_64
  Reason: image not found
Abort trap: 6

```

It did work on the CoreOS-Alpha image from date:
20170927

I think i used the qemu version 2.10.1 at the time.

**Comment by Tha-Robert** [comment]
I tried this on a Ubuntu machine and it works so its seams like its only on OS X or with the new apfs filesystem.

Hope this helps someone else also.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
