### ISSUE TITLE
cloud-config & fleet

### ISSUE THREAD

**Issue by hackzilla** [coreos/bugs#117]
There seems to be no way of automatically adding services defined in cloud-config to be submitted to fleet and started.

Also if you update your units in cloud-config, it would be nice if they also updated fleet, as at the moment, you have to manually destroy then, and resubmit them.

**Comment by JeanMertz** [comment]
@jonboulle 

> There seems to be no way of automatically adding services defined in cloud-config to be submitted to fleet and started.
>> Would you mind elaborating on your specific use case here? Are you just trying to ensure that after bootstrapping a cluster you have certain units automatically started somewhere in the cluster?

Another use-case for us, is when we fire up a development environment of our cluster using Vagrant.

Here's the process we use:

* boot VMs
* cloud-config file will create a `consul@.service` unit template
* after this we want to start the Consul service, using remote fleet management:

    ```
    bin/fleetctl start consul@{1..3}.service
    ```

  (where `bin/fleetctl`) is a wrapper to find the correct address of the remote fleet daemon)

However, this presents two issues:

1. the `consul@.service` template is defined *inside the cloud-config file* and when doing remote execution, this file does not exist. We also can't do things like `/etc/sytemd/system/consul@{1..3}.service`, because it will look for that file on your local machine.

2. *if* we kept a local copy of the unit template in our Git repository, we would have to update its contents in two places (both the cloud-config file and the unit template file itself).

If we could actually *submit* unit files/templates as proposed by @hackzilla, there would be no need for a local duplicate, as Fleet wil find the template in its registry already.

(however, I do not agree with the proposed format, I'd rather have a `submit` option for each `coreos.unit.*` right next to the already existing options like `enable`).

Also, one final note: we already use `Ansible` to get all unit files on the remote machines, but Consul is an exception to this, because Ansible actually uses consul to get a dynamic manifest of all our running instances, so we have to have Consul running before we can start the Ansible run, resulting in a catch-22 .

**Comment by crawford** [comment]
This isn't something we are going to support.
