### ISSUE TITLE
support for Atheros 802.11ac wireless card needed (CONFIG_ATH10K)

### ISSUE THREAD

**Issue by f0** [coreos/bugs#1183]
Hi,

i want run coreos on a Alix APU system with an Qualcomm Atheros QCA986x/988x 802.11ac Wireless Network Adapter card as my router.

Is it possible to activate the module on coreos?

regards f0

**Comment by crawford** [comment]
CoreOS is not designed to be used outside of server environments. I don't want to open the gate to including all sorts of peripheral drivers in our kernel. That being said, you should be able to compile the module yourself with `make -C /lib/modules/$(uname -r)/build M=$PWD`. We've populated `/lib/modules/$(uname -r)/build` and included the appropriate headers to facilitate this.

**Comment by f0** [comment]
@crawford  i understand this, for my understanding a router / Ap is a "server", but i expected this answer.

**Comment by crawford** [comment]
Yeah, sorry. We've got to draw the line somewhere. Let me know if you have any trouble compiling that module.

**Comment by f0** [comment]
@crawford 
whats the best way? Using the sdk? i tried the way with the toolbox but the right branch is missing

**Comment by f0** [comment]
@crawford  ok i have some trouble 

ok a coreos host (991.2.0) i run a ubuntu container (install gcc and make)

```
docker run -net host -v /lib/modules/$(uname -r)/build:/lib/modules/$(uname -r)/build -ti ubuntu /bin/bash
```

i got this error .... any ideas?
```
root@e0be3616ccf4:/lib/modules/4.4.6-coreos/source# make -C  /lib/modules/$(uname -r)/build M=drivers/net/wireless/ath/ath10k
make: Entering directory `/lib/modules/4.4.6-coreos/build'
/linux-4.4.6/Makefile:660: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
mkdir: cannot create directory 'drivers': Read-only file system
mkdir: cannot create directory 'drivers': Read-only file system
  LD      drivers/net/wireless/ath/ath10k/built-in.o
ar: drivers/net/wireless/ath/ath10k/built-in.o: No such file or directory
make[3]: *** [drivers/net/wireless/ath/ath10k/built-in.o] Error 1
make[2]: *** [_module_drivers/net/wireless/ath/ath10k] Error 2
make[1]: *** [sub-make] Error 2
make: *** [__sub-make] Error 2
make: Leaving directory `/lib/modules/4.4.6-coreos/build'
```

**Comment by marineam** [comment]
@f0 a couple issues: looks like the compiler version is different which may or may not be problematic. Also you must build with an external object directory, with your invocation of make that may need to be via KBUILD_OUTPUT= or O=, not sure which.

**Comment by f0** [comment]
@marineam  hm both does not change anything....
make -C  /lib/modules/$(uname -r)/build M=drivers/net/wireless/ath/ath10k O=/test

**Comment by marineam** [comment]
f0: oh wait... completely skipped over the obvious, the tree at /lib/modules/4.4.6-coreos/source is stripped down to only include what is needed to build external modules. No real kernel source is there. So you still need the ath10k source. So you can avoid the complexity of ebuilds and packages normally involved in assembling our kernels I've posted a branch for 4.4.6-coreos here: https://github.com/coreos/linux/tree/v4.4.6-coreos

Looks like that driver uses CFG80211 and MAC80211 so you are going to need quite a number of modules beyond just ath10k. Once you get them built there is still the matter of loading them. If it was a single module insmod would be plenty, and in this case may still work for you if you insmod them in the right order. Otherwise you need modprobe/depmod which expect /lib/modules/4.4.6-coreos but being read-only you'll need to use overlayfs or similar trick to be able to install your modules there.

I'm not sure all this pain is worth it :(

**Comment by f0** [comment]
@marineam   yes is see its to complicated... so i need to run a vm on top of coreos for my access point.
