### ISSUE TITLE
Should Ignition support older configs?

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1192]
Currently, Ignition only supports version 1 of the config spec. We are in the final stages of implementing version 2.0.0 (we switched to semver) of the config spec and the question has come up of whether or not Ignition should simultaneously support version 1 and version 2.0.0.

Regarding the support of multiple versions, there are three strategies that can be adopted:

  1. Only one version is supported at a time.
  2. The latest version and one previous are supported.
  3. All versions are supported.

With a bit of induction, we can prove that option 2 implies option 3:

       v1 can be translated to v2.0.0
       v(N+0).0.0 can be translated to v(N+1).0.0
    .: v(N).0.0 can be translated to v(latest).0.0

My gut tells me that we cannot guarantee that we will be able to preserve the semantics of Ignition throughout its lifetime (though I have no concrete proof of this). Assuming this is true, we cannot guarantee that we will be able to support option 3. Additionally, it means we cannot guarantee that we will be able to support option 2 for all possible versions (there will exist a discontinuity between two major versions).

My proposal is to make a reasonable effort to support option 2 (no hard guarantees). This would provide (what I believe to be) a reasonable window to transition from one version of the config spec to the next (judging by the current rate of development, that window would be roughly one year) for most major spec revisions.

I'm curious what people think of this plan.

**Comment by crawford** [comment]
Thanks GitHub.

**Comment by marineam** [comment]
Sounds good to me. It's not like we are building provably correct software here. ;)

At some point here we need to establish standard mechanisms for documenting, detecting, and warning users about deprecated features. If we are good about reporting them in motd for users and sending up to us via update_engine making incompatible changes will become a lot less scary.

**Comment by brianredbeard** [comment]
@marineam I agree with those points 100%.  I'd like for us to think of what comes next after motd though.  By this I mean that we attempt to discourage users from actively logging into hosts, as such we need a mechanism for the hosts to pass information back to a central service.

This could be as simple today as log aggregation with `systemd-journal-upload`.  In the future though I could foresee having a service (I'll call it `coreos-dispatcher`) which an administrator may run which aggregates and responds to information sent to it.  I'll include three useful scenarios:


  - Host reports to dispatcher it's running `789.0.0`.  Dispatcher checks and posts to a webhook "Host XXX has failed to process updates for 211 versions."
  - Host processes update, but we (CoreOS) have deprecated some software or feature (e.g. "As of version 835.8.0 the kubelet will no longer be present in the base image."
  - Fundamental change to software (e.g. "The version of Docker has been reverted to 1.6.2 due to a regression which prevents flannel from running.")

All of these are real occurrences which myself or others have directly experienced.

**Comment by robszumski** [comment]
Sounds good to me.

@brianredbeard brings up great points as well. I'd also like to see a generic email announce list or something designed primarily for a human.

**Comment by crawford** [comment]
It was suggested that Ignition utilize the "Accept" HTTP request header to inform the sender of acceptable versions. I think this is a great idea, regardless of the direction we go.

**Comment by marineam** [comment]
@crawford Accept sounds like a good thing to have :)

@brianredbeard on the issue of getting such info off the host I think there are a few things we can do:

 - Create a standard way to record use of deprecated things, like a directory of files in /var. The very first consumer of this could be motd.
 - Another consumer will be update_engine so we can gather stats on deprecated things in the wild so we know how significant the eventual removal will be.
 - Figure out some scheme to integrate this into our tectonic and other mgmt/deploy tools, part of which may be your coreos-dispatcher :)

**Comment by crawford** [comment]
We are going to go with my proposal.
