### ISSUE TITLE
rkt-ized kubelet fails cadvisor stats summary

### ISSUE THREAD

**Issue by pieterlange** [coreos/bugs#1225]
Hi,

while trying to deploy heapster i ran into the problem of collecting stats from my kubelets. The <IP>:10250/stats/summary API call fails with a HTTP 500 error and lists the following error:
`Internal Error: non-existent label "root"`

The same error message is logged to journald:
`Apr 14 13:52:23 ip-10-40-1-95.eu-west-1.compute.internal kubelet-wrapper[1550]: I0414 13:52:23.589808    1550 handler.go:239] HTTP InternalServerError: Internal Error: non-existent label "root"`

I get the distinct impression this only showed up after running the kubelet as rkt-ized application. I'm running CoreOS 1000.0.0 and kubernetes 1.2.0. Hyperkube is stock from the main kubernetes repo with added symlinks so i can start using `/kubelet`, `/proxy` and so on.

```
Environment=KUBELET_ACI=quay.io/plange/hyperkube
Environment=KUBELET_VERSION=v1.2.0
```

**Comment by aaronlevy** [comment]
This is due to an issue with how cadvisor labels the filesystem mounts. A fix has been merged into upstream cadvisor: https://github.com/google/cadvisor/commit/5ff166996826d30464f553b4b9296a46e7bdd599

However, the cadvisor version will need to be bumped in kubernetes to see this fix. In the interim, we carry this as a patch in our builds of the quay.io/coreos/hyperkube images (https://github.com/coreos/kubernetes/commits/coreos-hyperkube-v1.2.2)

**Comment by pieterlange** [comment]
Thanks for the heads up :) i'll start using the coreos hyperkube image.
