### ISSUE TITLE
CoreOS on SWRAID

### ISSUE THREAD

**Issue by vmatekole** [coreos/bugs#1232]
Hi!
Has there been any progress on this front? Developing consistent documentation for installing on SWRAID. Would going with HWRAID be an easier option for now?

**Comment by robszumski** [comment]
The Hetzner part or the software raid part?

For raid, check out this Ignition example: https://coreos.com/ignition/docs/latest/examples.html#create-a-raid-enabled-data-volume

Ignition is needed for this because it runs before systemd even boots, which means your disks get formatted as early as possible in the boot process. You can pass this Ignition config to the CoreOS install script.

(closing https://github.com/coreos/docs/issues/790 in favor of this since this is a more correct repo)
