### ISSUE TITLE
Question about the Docker 1.10 update on Beta channel (1010.1.0)

### ISSUE THREAD

**Issue by politician** [coreos/bugs#1245]
Are there any advisories out for users on the Stable channel running layer-based private registries such as `dogestry` with respect to the Docker 1.10 update currently on the Beta channel?

As you know, Docker 1.10 contains a breaking change to the way images and layers are stored.  We're currently building images with Docker 1.9 and shipping them into a `dogestry` private registry to store layers in AWS S3 rather than using a public registry like Docker Hub.

Is CoreOS aware of any known issues with this combination of tools?

**Comment by crawford** [comment]
> Is CoreOS aware of any known issues with this combination of tools?

Are you implying that there _are_ known issues or are you just asking if any exist? English is too ambiguous -_-

**Comment by politician** [comment]
I wasn't implying that when I asked the question, but after doing some testing it looks like older versions of dogestry cannot download layers produced by 1.10.  

For us, it looks like if we continue to publish layers using Docker 1.9, then those layers will be transparently upgraded to the 1.10 format when they land on the CoreOS machines.  So, if we choose to upgrade our build process to Docker 1.10 we will also have to upgrade `dogestry`.

It might be worthwhile to let other people know that this automatic update includes breaking changes that may affect existing deployment processes even though the breaking changes aren't specifically caused by CoreOS.

**Comment by crawford** [comment]
Hrmm, this is good to know. Thanks for the heads up.

**Comment by chr0n1x** [comment]
I'm seeing issues on CoreOS 1010.xx, docker version 1.10.3. Specifically, lstat issues on FS layers. Not really sure how to debug & provide any useful information though :(

Is there a documented upgrade path for this?

**Comment by crawford** [comment]
@chr0n1x this seems like it would be right up Docker's alley. Can you reach out to them and see what they think?

**Comment by philips** [comment]
From twitter it seems like this might be related to overlayfs. Have you confirmed that non-overlayfs backends don't have this issue?

**Comment by politician** [comment]
I just noticed that both of my clusters are now running 1010.5.0 which contains Docker 1.10 even though this bug is P0 and still open.  So, now I'm in firefighting mode here.

**Comment by crawford** [comment]
@politician my sincere apologies for this. I was made aware that the Docker Hub was removing support for Docker 1.9 today, so we were forced to begin rolling out Docker 1.10 to everyone. Since I can't seem to find documentation on the deprecation (and I wasn't personally notified, despite being on the mailing lists), I've attached a screenshot of the notice that was sent to some of the Docker Hub users.

<img width="628" alt="screen_shot_2016-06-01_at_1 41 49_pm" src="https://cloud.githubusercontent.com/assets/368848/15725125/35fbbabe-27ff-11e6-905d-1f4b9fbd3b43.png">

We are putting together some documentation for running a specific version of Docker within a rkt container, since this class of problem is evidently going to happen again. This whole thing is such a mess and I'm sorry you got caught up in it.

**Comment by chr0n1x** [comment]
@philips @crawford thanks for the input / followup.

@politician we've had this issue on multiple clusters. We're currently locking to an AMI with a sane config/setup and stopping automatic updates (CoreOS ~899). We have a private channel though, so I'm not sure if that's of help; I figured that I would mention it here though.

I'm personally under the impression that this is a problem specifically with docker. On `1010` we've tried:

1. `systemctl stop docker docker.socket && rm -rf /var/lib/docker && systemctl reboot` - on nodes that were already running containers that were rebooted to update to `1010`. This problem persisted though.
2. Starting up fresh nodes using latest stable (with docker 1.10) - this issue and some others popped up.
3. We've also tried the docker 1.10 migrator container ([here](https://docs.docker.com/engine/migration/)) but that didn't really help since the error happens before any of the fs layers are registered, so I guess that it was wasted time.
4. Rebuilding docker images that were known to cause issues on our machines with a docker 1.10 client & daemon - problem still popped up sporadically.

I hope that the listing above saves some time for others that are experiencing this issue.

**Comment by politician** [comment]
@chr0n1x @crawford Thanks for the followups.  I'll dig through that information, but right now the one node that updated in my beta environment ran out of disk space (probably unrelated).  The `etcd2` error logs filled up with broken snap files, and so where I'm at now is trying to get etcd2 2.3.1 to rejoin a cluster whose members are on the older etcd2 2.2.3.

**Comment by politician** [comment]
I've restored the node to the etcd2 cluster, and then discovered the reason my disks filled up:

1. In order to update to CoreOS 1010.5.0 the machine restarted.
2. `systemd` launched a restart of all of the containers scheduled to start on that node.
3. The launch scripts request the latest version of the container from the external container repository before calling `docker run`.  These scripts check the remote version against the local version using the Docker API.  
4. **These checks all failed, triggering the simultaneous download of updated versions.**
5. The `/tmp` partition filled up causing services to fail and restart (triggering more downloads doomed to fail).
6. _Somehow_ (TBD) this translated into a large number of orphaned Docker volumes that filled up the primary drive (~2000 8M volumes) which is likely how `etcd2` got horked in the first place (no free disk space).  It's possible that the existing images on the machine are incompatible with Docker 1.10 and/or the Docker 1.10 image upgrader requires the `/tmp` partition (which was full).

At this time, I'm going to (a) race to finish the `push` path of https://github.com/politician/azdockertool, and hope I can get that done ahead of failures in my production systems, (b) race to upgrade all of our images to Docker 1.10.

**Comment by politician** [comment]
> @politician my sincere apologies for this. 

@crawford Apology accepted.  It looks like your hands were tied; maybe in the future we can decouple CoreOS from the shenanigans over at Docker HQ?

**Comment by crawford** [comment]
> I've set the REBOOT_STRATEGY=off and restarted locksmithd. Now it's in an infinite start/stop loop, is that intentional?

Huh, it's not intentional, but it is expected. You can stop and mask the service to prevent it from running at all. (Sorry for the delayed response)

> maybe in the future we can decouple CoreOS from the shenanigans over at Docker HQ?

Working on it ;)
