### ISSUE TITLE
a syntax error.

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1319]
<a href="https://api.github.com/users/wmydz1"><img src="https://avatars.githubusercontent.com/u/9999341?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [wmydz1](https://api.github.com/users/wmydz1)**

----

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/samchen/Documents/software/coreos-vagrant/Vagrantfile
Line number: 0
Message: Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 10 column 1

**Comment by MidnightWonderer** [comment]
I have the same error message as you guys but I know how it occurred.
The error message is somewhat misleading.  
Psych is a YAML parser. The syntax error refer to the syntax of yml file not Vagrant file.
For me (common case; I guess) the syntax error is in "user-data".
The line number reported is a bit shifted because the comment lines were stripped before the line number is determined.(I guess)
