### ISSUE TITLE
Including Packer JSON in repo

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1320]
<a href="https://api.github.com/users/kveroneau"><img src="https://avatars.githubusercontent.com/u/1632238?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [kveroneau](https://api.github.com/users/kveroneau)**

---

Do you use Packer to build these boxes, or another technology? It would be really nice if the ability to build our own boxes with our own specifications(ie. disk sizes) were available. I am currently needing to roll my own CoreOS box for Vagrant for a work project, as the disk size of 20G which this GitHub project provides is much much too small for our project requirements. I searched around for an official Packer JSON, and was unable to locate one. I tried one suggestion of resizing the VMDK using VBoxManage, however VBoxManage is unable to resize VMDKs as of version 5.x.x.

**Comment by AlexNPavel** [comment]
We do not use packer to build the Vagrant boxes. Also, these boxes are no intended for a production environment (they are insecure, mainly due to the vagrant ssh key). Since we do not use packer, I will be closing this pull request. If you want to spin your own images, look at the coreos-sdk (https://coreos.com/os/docs/latest/sdk-modifying-coreos.html). There should be a couple of scripts there that can be modified to change the size of the disk.
