### ISSUE TITLE
OverlayFS Corruption

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1336]
<a href="https://api.github.com/users/kjvalencik"><img src="https://avatars.githubusercontent.com/u/2471970?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [kjvalencik](https://api.github.com/users/kjvalencik)**

---

I am mounting an ext4 data partition to `/var/lib/docker` for persisting images across `vagrant destroy; vagrant up` cycles. However, if the image is shutdown uncleanly, docker no longer works after the next `vagrant up`.

Running `vagrant halt` between cycles fixes the issue. If I use btrfs instead of ext4 for the data partition, I do not have the issue.

Sample output after corrupted data:

 core@e-coal ~ $ docker images
 REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
 <none> <none> 6941bfcbbfca 6 weeks ago 0 B
 busybox latest 8c2e06607696 6 weeks ago 2.43 MB

Thanks!

**Comment by vcaputo** [comment]
This sounds similar to https://github.com/coreos/bugs/issues/1309

The storage systems of virtual machines often employ tricks (or plain oversights) which improve VM performance but compromise ordering and durability correctness.

I'm uncertain if that's what's going on here, but seeing such errors from journaled filesystems after unclean shutdown suggests something in the underlying storage is interfering with the journaling mechanisms.

If this were an actual CoreOS kernel bug in ext4 or jbd I'd expect us to see it from more users across a variety of platforms.  At this time it seems to be specific to a couple vagrant users, which causes me to further suspect something specific to the virtualization stack in use.

**Comment by AlexNPavel** [comment]
This isn't really an issue with Container Linux or Vagrant. When you run `vagrant destroy`, you're doing the equivalent of pulling the power plug on a machine, which can corrupt data if that data is currently being used or written to. The reason btrfs does not have this issue is because it is a COW filesystem, so it is never left in an inconsistent state (except if you are having hardware issues). This isn't something we can fix, and it's not an issue with Container Linux and Vagrant.
