### ISSUE TITLE
There was a problem while downloading the metadata for your box

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1355]
<a href="https://api.github.com/users/jnuc093"><img src="https://avatars.githubusercontent.com/u/1922095?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [jnuc093](https://api.github.com/users/jnuc093)**

---

$ vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Checking if box 'coreos-beta' is up to date...
==> core-01: There was a problem while downloading the metadata for your box
==> core-01: to check for updates. This is not an error, since it is usually due
==> core-01: to temporary network problems. This is just a warning. The problem
==> core-01: encountered was:
==> core-01:
==> core-01: Failed connect to beta.release.core-os.net:80; No error
==> core-01:
==> core-01: If you want to check for box updates, verify your network connection
==> core-01: is valid and try again.
==> core-01: VirtualBox VM is already running.

**Comment by lucab** [comment]
This looks like a stale issue, possibly due to transient network errors, thus closing.

Anybody (including original reporter) hitting this recently, please feel free to open a new ticket.

**Comment by LexBel-co** [comment]
I have the same issue here a couple days ago:

`$ vagrant up
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: There was a problem while downloading the metadata for your box
==> homestead-7: to check for updates. This is not an error, since it is usually due
==> homestead-7: to temporary network problems. This is just a warning. The problem
==> homestead-7: encountered was:
==> homestead-7: 
==> homestead-7: The requested URL returned error: 404 Not Found
==> homestead-7: 
==> homestead-7: If you want to check for box updates, verify your network connection
==> homestead-7: is valid and try again.`

Any help would be appreciate

**Comment by Vishal-Gaur** [comment]
Having the same issue as @crawford.
Due to this issue i'm unable to ping as well.

vagrant up
Bringing machine 'ansible' up with 'virtualbox' provider...
==> ansible: Checking if box 'ubuntu/xenial64' is up to date...
==> ansible: There was a problem while downloading the metadata for your box
==> ansible: to check for updates. This is not an error, since it is usually due
==> ansible: to temporary network problems. This is just a warning. The problem
==> ansible: encountered was:
==> ansible: 
==> ansible: The requested URL returned error: 404 Not Found
==> ansible: 
==> ansible: If you want to check for box updates, verify your network connection
==> ansible: is valid and try again.
==> ansible: VirtualBox VM is already running.

**Comment by Soulwest** [comment]
I've got the same error.

$ vagrant halt && vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: There was a problem while downloading the metadata for your box
==> default: to check for updates. This is not an error, since it is usually due
==> default: to temporary network problems. This is just a warning. The problem
==> default: encountered was:
==> default: 
==> default: The requested URL returned error: 404 Not Found
==> default: 
==> default: If you want to check for box updates, verify your network connection
==> default: is valid and try again.

**Comment by lucab** [comment]
This ticket is attracting unrelated comments for non-coreos failures (respectively with "laravel" and "ubuntu" boxes), thus I'm locking this conversation to avoid piling up more unrelated items.

If anybody experiences persistent failures specifically with coreos boxes and endpoints, please open a new ticket. For other non-coreos boxes, please report to the specific provider.
