### ISSUE TITLE
systemd-sysusers segmentation fault

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1394]
# Issue Report #

## Bug ##

As reported by scole-scea on IRC, `systemd-sysusers` crashes, preventing the creation of the fleet user and group.

### CoreOS Version ###

1010.5.0

### Expected Behavior ###

`systemd-sysusers` runs and creates the fleet user and group.

### Actual Behavior ###

`systemd-sysusers` segfaults, yielding a [core dump](https://github.com/scole-scea/systemd-sysusers-coredump/blob/master/core?raw=true)

**Comment by mhenniges** [comment]
Let me know if you need help repro-ing this issue, I have several machines available were this segfault happens every time systemd-sysusers is run.

**Comment by mhenniges** [comment]
I've spent a little time trying to isolate this, and it seems the segfault (at least it my case) is caused by long entries in /etc/gshadow. 

With this example entry in gshadow, systemd-sysusers does not segfault. Add 1 more character to it and it segfaults every time.

sudo:*::somebody.a1,somebody.a2,somebody.a3,somebody.a4,somebody.a5,somebody.a6,somebody.a7,somebody.a8,somebody.a9,somebody.a10,somebody.a11,somebody.a12,somebody.a13,somebody.a14,somebody.a15,somebody.a16,somebody.a17,somebody.a18,somebody.a19,somebody.a20,somebody.a21,somebody.a22,somebody.a23,somebody.a24,somebody.a25,somebody.a26,somebody.a27,somebody.a28,somebody.a29,somebody.a30,somebody.a31,somebody.a32,somebody.a33,somebody.a34,somebody.a35,somebody.a36,somebody.a37,somebody.a38,somebody.a39,somebody.a40,somebody.a41,somebody.a42,somebody.a43,somebody.a44,somebody.a45,somebody.a46,somebody.a47,a123


Long entries in /etc/group do not seem to have the same effects.

**Comment by dylancarlson** [comment]
@mhenniges Working on it, thanks for reporting. We've repro'd the issue easily.  615+ chars triggers it.  We'll update when we have more.

#0  0x00007f62c4549266 in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=ap@entry=0x7fffd60f58f8) at vfprintf.c:1642
#1  0x00007f62c4550460 in __fprintf (stream=stream@entry=0x560a21994ff0, format=format@entry=0x7f62c4677b1c "%s%s") at fprintf.c:32
#2  0x00007f62c45f972e in putsgent (g=<optimized out>, stream=0x560a21994ff0) at putsgent.c:57
#3  0x0000560a1fc035dc in putsgent_with_members (sg=0x7f62c48aaac0 <resbuf>, gshadow=0x560a21994ff0)
    at ../systemd-229/src/sysusers/sysusers.c:338
#4  0x0000560a1fc06103 in write_files () at ../systemd-229/src/sysusers/sysusers.c:490
#5  0x0000560a1fc024eb in main (argc=<optimized out>, argv=<optimized out>) at ../systemd-229/src/sysusers/sysusers.c:1891

**Comment by scole-scea** [comment]
Hey, wow, I didn't even realize this bug had been created based on my report. Thanks for speeding this into the stable build.
