### ISSUE TITLE
Docker 1.11.2

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1414]
Bump Docker to 1.11.2

/cc @aaronlevy

**Comment by pmoust** [comment]
Experiencing memory issues as described in https://github.com/docker/docker/issues/20586#issuecomment-187898092
Looking forward to 1096.0.0 having 1.11.2 in.

**Comment by dhawal55** [comment]
The memory issues mentioned in [docker/docker#20586 (comment)](https://github.com/docker/docker/issues/20586#issuecomment-187898092) was in docker v1.10.1 and because of logspout. As mentioned in comments on the same issue, 1.11.2 seems to be working fine. 

I can't understand why CoreOS is still using a 3 month old release. At least the alpha channel should have a quicker update cycle. Is there anyway to upgrade docker manually and has anyone tried it?

**Comment by Sebas-** [comment]
Not to mention 1.12 is just around the corner, and 1.12 has some nice features that would work really well with coreos.

Would be nice to see 1.12 in the alpha channel since it is currently in feature freeze status.

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/coreos-overlay/pull/2023.
