### ISSUE TITLE
oem-cloudinit.service ordering is not explicit

### ISSUE THREAD

**Issue by a86c6f7964** [coreos/bugs#1427]
# Issue Report
## Bug

oem-cloudinit.service ordering is not explicit, so anything that is added to something that exists in the OS itself such as the instructions for using attached storage for docker https://coreos.com/os/docs/latest/mounting-storage.html only work by chance.
### CoreOS Version

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1010.5.0
VERSION_ID=1010.5.0
BUILD_ID=2016-05-26-2225
PRETTY_NAME="CoreOS 1010.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment

What hardware/cloud provider/hypervisor is being used to run CoreOS?
AWS r3.large
### Expected Behavior

docker.service should only run after oem-cloudinit.service 
### Actual Behavior

docker.service runs at the same time as oem-cloudinit.service
### Reproduction Steps
1. Use https://coreos.com/os/docs/latest/mounting-storage.html and then make a docker service in systemctl that runs on boot.
2. Delete the `10-wait-docker.conf` (which IMHO should not matter since oem-cloudinit.service should re-create it)
3. Restart the machine
### notes

I had added `Before=docker.service` to the `var-lib-docker.mount` instead of creating `10-wait-docker.conf`, I am assuming that the reason that this did not work has something to do with the ordering. I made the bug because I feel like this could creep up into all kinds of other strange cases, where people are mutating something in the cloudinit without realizing that it has already started.  (I was running on the assumptions that the cloudinit would happen as early on in the process as possible)

**Comment by crawford** [comment]
Unfortunately, this is a shortcoming of coreos-cloudinit. We cannot explicitly add an ordering dependency between it and Docker because there may be a service which coreos-cloudinit tries to start, which in turn depends on Docker starting. This dependency loop would hang the boot.

The "proper" way to use coreos-cloudinit is to start all of your services via it and avoid using `runtime: false` and `enable: true`. There are some cases where this can't be avoided however, so you'll have to be careful.

> I had added `Before=docker.service `to the `var-lib-docker.mount` instead of creating `10-wait-docker.conf`, I am assuming that the reason that this did not work has something to do with the ordering.

`var-lib-docker.mount` will need to activate `docker.service` using a `Requires` or `Wants`.

 I don't think there is anything we can do to fix coreos-cloudinit in this case. There is hope though! We've been investing in [Ignition](https://coreos.com/ignition/docs/latest/) for a while now and it's beginning to shape up. If you are having too much trouble with coreos-cloudinit, I would give Ignition a shot. The execution model is dramatically simpler and yet so much more powerful.

**Comment by a86c6f7964** [comment]
The documentation for how to setup a docker mount that I linked only works
because nothing uses the docker socket. If anything were to try and use the
docker socket before cloudinit runs then it would break.

**Comment by crawford** [comment]
Correct. Because coreos-cloudinit is effectively an init system (albeit a terrible one), you have to make a choice between using coreos-cloudinit and systemd for your setup. Neither coreos-cloudinit or systemd are aware of what the other is doing, so in order to use both, you need to ensure that there is no interdependence between what each one is starting. Because this is quite difficult, you are forced to use one or the other.

**Comment by simonvanderveldt** [comment]
@crawford we ran into pretty much the same order issues as in this issue, in our case it was the `update-engine`. We've disabled `update-engine` in our cloud-config, yet it's still being started on boot and only after some time when the cloudinit unit gets run it gets disabled/masked.
We expected cloudinit to pretty much be the first thing to run before any other unit (or at least the majority of other units) would be started.
Note that technically nothing's failing for us, but we now do get error logs during bootup, which we obviously don't want :)

> Unfortunately, this is a shortcoming of coreos-cloudinit. We cannot explicitly add an ordering dependency between it and Docker because there may be a service which coreos-cloudinit tries to start, which in turn depends on Docker starting. This dependency loop would hang the boot.

Isn't this simply the responsibility of the user to define the correct dependencies in the units they're adding using cloudinit?
If cloudinit would start as on of the first units and we correctly declare our units I think our issue/use case would be solved. Or am I missing something?

**Comment by crawford** [comment]
The underlying issue is that coreos-cloudinit is trying to be its own init system on top of systemd. systemd doesn't recognize coreos-cloudinit as being special and cores-cloudinit doesn't understand systemd dependencies. The result is a complete breakdown whenever you try to do anything much more than the simplest operations.

We cannot reasonably expect the user to understand the implementation details and construct configs that are compatible. There is just too much going on.

The solution is to just use Ignition. It actually runs before systemd and fully leverages systemd to start all of the services.
