### ISSUE TITLE
Network intf name changed from 1010.6.0 to 1068.6.0 on ESXi

### ISSUE THREAD

**Issue by jcmoraisjr** [coreos/bugs#1462]
# Issue Report
## Bug

After upgrade from 1010.6.0 to 1068.6.0, the network interface changed it's name from eno16780032 to ens192. Using VMware ESXi 6. 
### CoreOS Version

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1068.6.0
VERSION_ID=1068.6.0
BUILD_ID=2016-07-12-1826
PRETTY_NAME="CoreOS 1068.6.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment

VMware ESXi 6 virtual machine. Tested on network with and without DHCP.
### Expected Behavior

An immutable network interface name between OS updates, otherwise fixed IPs on machines with more than one en\* interface won't work.
### Actual Behavior

Interface name changed between 1010.6.0 and 1068.6.0.
### Reproduction Steps
1. Boot a VMware ESXi 6 VM with 1010.6.0 iso and check that the network interface is eno16780032.
2. Reboot the same VM with 1068.6.0 iso and note that now the interface name is ens192.

**Comment by crawford** [comment]
It looks like this was due to a fix for https://github.com/systemd/systemd/issues/2407. I guess the VMware hypervisor doesn't advertise hardware properly. Since the long interface names are problematic for some users, we have to go with the newer, shorter names. Sorry for the friction, but I don't think there is anything we can do here - this is a VMware bug.

As a workaround, it is possible to [match](https://www.freedesktop.org/software/systemd/man/systemd.network.html#%5BMatch%5D%20Section%20Options) on other properties of the interface.
