### ISSUE TITLE
PXE boot without using dracut

### ISSUE THREAD

**Issue by jgunthorpe** [coreos/bugs#1473]
I'm not sure how folks will feel about this, but throwing it out..

Currently PXE booting fetches a vmlinux, which includes a linked in initramfs (CONFIG_INITRAMFS_SOURCE="bootengine.cpio")  which has dracut and all the kernel modules. It also fetches a cpio containing a squashfs and another copy of all the modules. Presumably this follows other coreos boot schemes, but honestly, it is really weird to link the modules into the kernel inside a linked in ramfs, let alone do that when PXE booting.

For PXE, this it totally wasteful. It means booting sucks down another 25M of stuff, and increases the system complexity. PXE does not need the linked in ramfs at all, it just needs a small statically linked program inside the cpio that mounts usr.squashfs to usr/ and starts systemd directly. PXE reliably delivers the root file system without needing additional modules or otherwise, there is no need for something like dracut to locate and mount the root filesystem.

My motivation for this is two fold.

First I need to compile some additional upstream modules that coreos does not enable for a some special needs I have, and I need to backport some upstream patches that have not yet made it coreos. Both of these need to be delivered to my cluster...

Second I need to do a bit of kernel hacking on a coreos environment, so building a new vmlinux and modules is necessary.

The big stumbling block to this is the bootengine.cpio, this is very hard to rebuild without going into a full coreos distro build process, which I'd rather not do :|

On the other hand, if dracut was not involved then it is fairly simple. Unpack the squashfs, replace the module(s), repack the squashfs, PXE boot.

**Comment by dm0-** [comment]
I've uploaded some kernel notes that might give you a workaround for the time being, since you're already building your own kernel.

https://gist.github.com/dm0-/1f656b68491cd22e65ae0f33d4f1dd25

This procedure builds a PXE-compatible CoreOS kernel omitting things I don't need from the initramfs, like the modules and Ignition.  (If you need Ignition, add it to the `emerge` command.)  The dracut-based initramfs is still used in this setup, but it will result in a smaller kernel without so much stuff in it.

**Comment by jgunthorpe** [comment]
Interesting, creating a non-modular bootimage.cpio certainly would help for now.. Thanks for the directions.

Hopefully we can see a future version that does not have bootimage.cpio linked to the vmlinux, as would be a more typical boot flow..

**Comment by crawford** [comment]
We include the initramfs in the kernel itself so we can secure boot CoreOS. The initramfs also includes modules so that networking firmware/modules are available to Ignition. Theoretically, we could limit the modules that end up in the initramfs, but that's not a priority for us right now. We can revisit this eventually, as I imagine this scheme will change over time. I'm going to close this issue though, since it looks like you have a workaround.

**Comment by jgunthorpe** [comment]
It is a bit of a work around, but to be clear, but your arguments seem off. Every distro can secure boot and none of them use a linked-in cpio, they all use an external initramfs. I have no idea what motivated such a strange scheme for CoreOS.

In particular, when looking at PXE:
1) Secure boot with PXE is different than normal. The TPM PCRs should already include both the kernel and initramfs, and (ideally) the PXE loader should have done a secure transfer of both items. Nothing should be needed prior to mounting the root filesystem. 
2) When PXE booting Ignition/etc can run after mounting the root filesystem, ideally as part of the normal boot flow - when PXE booting the root fileystem doesn't come from storage so there is no need to sequence ignition before mounting root and running the main systemd.
3) Any other case that requires stuff to happen prior to running /sbin/init can be always be done after mounting the root filesystem. The root filesystem is always instantly available because in PXE mode the kernel sticks it into the / tmpfs.

Really, the trick here is to follow a more normal boot path, the external initramfs should have the modules and dracut for all boot modes. For PXE the external initramfs should omit dracut and just start the main systemd directly. No mode should use a built-in cpio.
