### ISSUE TITLE
Bug in bash version is causing problems to cli tools

### ISSUE THREAD

**Issue by hectorj2f** [coreos/bugs#1477]
I am experiencing some issues due to a bug in `bash v4.3` that causes some of the command line tools to fail. The bug is reported in https://bugs.archlinux.org/task/39533

For instance, my `calicoctl` tool is failing but I am aware of other cli tools that fail as well.

```
 $  sudo ETCD_AUTHORITY=172.17.8.102:2379 calicoctl status
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
calico-node container is running. Status: Up 2 hours
Running felix version 1.4.0rc2

IPv4 BGP status
IP: 10.1.100.2    AS Number: 64511 (inherited)
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook
Couldn't connect to bird.
IPv6 BGP status
No IPv6 address configured.
```

My machine uses the following release:
```
NAME=CoreOS
ID=coreos
VERSION=1068.8.0
VERSION_ID=1068.8.0
BUILD_ID=2016-07-18-0616
PRETTY_NAME="CoreOS 1068.8.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by dm0-** [comment]
I don't think I would necessarily call this a bash bug.

What seems to be happening is that the `calicoctl` binary from http://www.projectcalico.org/builds/calicoctl extracts a bunch of libraries including libreadline to a temporary directory (e.g. `/tmp/_MEIpFhcZH/libreadline.so.6`) as a method of bundling Python into a single executable.

Our bash program is linked against the version under `/lib64` which defines `rl_signal_event_hook`, while the libreadline extracted into `/tmp` does not define it.  While `calicoctl` is executing, it sets the `LD_LIBRARY_PATH` environment variable, causing subprocesses to load the libraries found in `/tmp`.  The dynamic linker then prints those error messages when it can't resolve the symbol.

The reason other distros like Debian and Fedora don't have this error is because they have a copy of readline built into bash instead of linking it with the installed system library.  Unless there are objections or other suggestions, maybe we could do the same.

**Comment by vcaputo** [comment]
Debian uses dash for /bin/sh.

It seems inappropriate to me for calicoctl to bundle its dynamically-linked dependencies, supplant the host's for their own via LD_LIBRARY_PATH, then execute the host's dynamically-linked shell expecting everything to be happy.  They should probably bundle a shell linked against their bundled libraries and use it instead, if they **must** shell out for this stuff at all.

**Comment by crawford** [comment]
Agreed. This is a bug with calicoctl. We'll follow up with them offline to make sure they correctly package their dependencies.
