### ISSUE TITLE
CoreOS stable (1068.8.0) The unit files have no [Install] section.

### ISSUE THREAD

**Issue by Jenkler** [coreos/bugs#1512]
# Issue Report #

## Bug ##

I get this message even if I have the Install section. It worked fine in previous CoreOS version but when updated to  CoreOS stable (1068.8.0) it broke. No changes made to the service file

I have:

[Install]
WantedBy=multi-user.target

In the file. What have changed in 1068.8.0 release?

everything works but i get this stupid error!

Created symlink from /etc/systemd/system/multi-user.target.wants/minecraft.service to /home/core/system/systemd/services/minecraft.service.
Created symlink from /etc/systemd/system/minecraft.service to /home/core/system/systemd/services/minecraft.service.
The unit files have no [Install] section. They are not meant to be enabled
using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).

### CoreOS Version ###

CoreOS stable (1068.8.0)

### Environment ###

Digital oceans standars VPS

### Expected Behavior ###

No error

### Actual Behavior ###

Error message 

### Reproduction Steps ###

Enable a service file from a non standard dir.

**Comment by mischief** [comment]
the message you see is actually a warning, not an error. as far as i can tell, it still works fine.

**Comment by mischief** [comment]
i'm assuming you updated from the previous stable version, 1010, which had systemd 225. now 1068 has systemd 229.

**Comment by Jenkler** [comment]
Thanks for the reply!

Yes, I know its a Warning :) But the warning is bogus ie that I have an install section.
Yes previous was 1010 and now I am at 1068.

Is there any way to disable this warning except piping everything to /dev/null. Should the Install section be different with systemd 229 ?

**Comment by dongsupark** [comment]
Actually I have been looking into a similar issue, https://github.com/coreos/fleet/pull/1655. My theory is that EnableUnitFiles was broken at some point between systemd v225 and v229, and this issue was already solved from upstream. See https://github.com/systemd/systemd/commit/3de1521427dee61000c1c124a521182b301a50de , which is available since systemd v230. Just a guess. What I'm sure is only that it works again with systemd v231 + CoreOS 1122, the most recent developer image built by CoreOS SDK.

I can see that the current coreos-overlay has already updated systemd to v231, but that's not available even in the current CoreOS alpha 1122, where still systemd v229 is included. Either we should wait until systemd v231 could be available, or backport proper patches to coreos-overlay, i.e. sys-apps/systemd/systemd-229*.ebuild.

**Comment by Jenkler** [comment]
dongsupark <-- Sound like a good idea! Thanks for the info :)

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/2164.
