### ISSUE TITLE
cloudinit VMWare OEM trying to fetch cloud-config before configuring network

### ISSUE THREAD

**Issue by rikatz** [coreos/bugs#1514]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.0.0
VERSION_ID=1122.0.0
BUILD_ID=2016-07-27-0739
PRETTY_NAME="CoreOS 1122.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

```

### Environment ###

VMWare vSphere 6 Update 2

### Expected Behavior ###
Using the guestinfo on the VMX  occurs sucessfully, configuring the networking throgh the information on VMX file (guestinfo.*) as documented on https://coreos.com/os/docs/latest/vmware-guestinfo.html, and then fetches the remaining configurations from cloud-config.yaml described on 'guestinfo.coreos.config.url'

### Actual Behavior ###
Using the guestinfo on the VMX file with the directive 'coreos.config.url' fails, as the 'coreos-cloudconfig -oem=vmware' tries to fetch the file from http server before configuring the network interface
### Reproduction Steps ###

  1. Deploy the OVA
  2. Before start the OVA, put the 'guestinfo' information on the VMX:

```
guestinfo.hostname = "katzcoreos11"
guestinfo.interface.0.name = "ens192"
guestinfo.interface.0.dhcp = "no"
guestinfo.interface.0.ip.0.address = "10.200.82.27/21"
guestinfo.interface.0.route.0.gateway = "10.200.80.1"
guestinfo.interface.0.route.0.destination = "0.0.0.0/0"
guestinfo.dns.server.0 = "10.30.0.235"
guestinfo.coreos.config.url = "http://10.200.84.222/cloud-config.yaml"
```
  3. Reload the VMX
  4. Start the VM. After some time (when trying to reach the config.url times out) the VM changes its IP address to respect the directives of VMX file
  5. To see the error, start the VM again with 'coreos.autologin' and inspect the oem-cloudinit.service. After the VM acquires the right IP, you can exec 'coreos-cloudinit -oem=vmware' again and it works fine, as the VM have the right IP address

### Environment ###

VMWare vSphere 6 Update 2

**Comment by rikatz** [comment]
Confirmed also with the stable version: Deployed a fresh OVA, changed the VMX before powering on the, after power on the hostname and the IP got changed just before trying to fetch the cloud-config from remote server.

**Comment by rikatz** [comment]
Corrected on https://github.com/coreos/coreos-cloudinit/pull/433

**Comment by crawford** [comment]
The `coreos.config.url` guest variable is not designed to be used with the network-config variables - it assumes you already have a working network. What you can do instead is provide an Ignition config (via `coreos.config.data`) to set up your network. Then you should be able to additionally supply `coreos.config.url`, which coreos-cloudinit will use to fetch the config. This works because Ignition is designed as a provisioning utility. It runs long before your application, coreos-cloudinit, and even networkd.

**Comment by rikatz** [comment]
@crawford Tks for the reply. 

The docs are unclear about this: https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/vmware-guestinfo.md

Although I think this would be really useful. If you have DHCP on your network the config.url works fine, why can't we do this a feature also for static IP addresses? :)

I know this is not the most elegant way to do this (a loop that executes the config flow two times on 'ds.Type vmware') but this solves the problem. And this way we make the solution viable to users using Ignition and guestinfo, so I can make a flow (like here in my company) that deploys the OVA, configures network and gets the remaining config from remote cloud-config.yaml all in one shot.

Thanks

**Comment by crawford** [comment]
> The docs are unclear about this: https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/vmware-guestinfo.md

Yeah, I agree. It's really a side-effect of the implementation. We've decided to invest our efforts in improving Ignition instead of coreos-cloudinit at this point. That's why I'm not keen on making large changes to the core operation at this point.

Since you are using VMware, it would also be possible for you to exclusively use Ignition for your deployments. That would definitely simplify the configuration you pass to the VMs. I'd be happy to help you through that transition if you are interested.

**Comment by rikatz** [comment]
@crawford Never mind, I was able to transition this. Doing some experiments here with Ignition and having success.

Is cloudinit going to be discontinued? Or I'll be able to  make the networking config through Ignition and the rest of the config through coreos.config.url without any problem in the future? So this way I can have the initial config (as selected / orchestrated by the user) and from there, configure the rest of the components (Kubernetes, Flannel, Calico) with a remote file.

If this is going to be discontinued, how does this (https://coreos.com/ignition/docs/latest/examples.html#replacing-the-config-with-a-remote-config) works? It configures the IP address first and then gets the Remote Config?

Thanks again!

**Comment by crawford** [comment]
> Is cloudinit going to be discontinued? Or I'll be able to make the networking config through Ignition and the rest of the config through coreos.config.url without any problem in the future? 

For backward compatibility, we are going to need to keep coreos-cloudinit around for some time. You should be fine using it for the foreseeable future.

> If this is going to be discontinued, how does this (https://coreos.com/ignition/docs/latest/examples.html#replacing-the-config-with-a-remote-config) works? It configures the IP address first and then gets the Remote Config?

Ignition fetches all of the chained configs and merges them before applying them. This means you can't affect Ignition's environment from Ignition itself. In your case, that presents a problem since you don't have DHCP. It is possible to configure the network via kernel parameters, but that doesn't buy us much since there's no good way (that I'm aware of) to specify kernel parameters from a VM definition.

The other option is we add some more guest variables that can be used to configure Ignition's environment. I'd have to think about this one a bit more before I can commit to the approach.

**Comment by rikatz** [comment]
Hey @crawford, me again :)

Testing with Ignition works fine, except for this line on the code:

case initialize.ErrIgnitionConfig:
                fmt.Printf("Detected an Ignition config. Exiting...")
                os.Exit(0)

When cloudconfig finds Ignition it skips the rest of the config. This includes the config.url data, and then it doesn't download the rest of the Configuration :(

So, is there another solution for this? 

Thanks :D

**Comment by rikatz** [comment]
And even without this restriction, there is another part of the code that limits the execution of cloudinit with url directive, as there is coreos.config.data on the code:

```
        data, err := v.readConfig("coreos.config.data")
        if err != nil {
                return nil, err
        }

        // Try to fallback to url if no explicit data
        if data == "" {
  url, err := v.readConfig("coreos.config.url")
                if err != nil {
                        return nil, err
                }

                if url != "" {
                        rawData, err := v.urlDownload(url)

```

**Comment by crawford** [comment]
@rikatz hmm, I forgot about that. Okay, plan B: Ignition writes and enables a service unit which runs `coreos-cloudinit --from-url <your url>`.

**Comment by rikatz** [comment]
Ok, I'm on a business travel, but will be able to test when I come back on friday!

Thanks!

**Comment by rikatz** [comment]
@crawford Nice one :D Just tested here and worked. 

Created an oneshot unit, inserted it on the 'ignition' config (on my VMX) and It's working fine!

Probably going to document this one as a solution to VMWare OVA + Static IP + Remote Cloud Config, so other people can use this as an alternative solution.

Thanks!

**Comment by crawford** [comment]
Excellent! Thank you for your persistence.

**Comment by jknsware** [comment]
I know this is old but I'm trying to reinvent this very wheel and was hoping that I could jog @rikatz 's brain on what he did. Don't see anything specifically in your gitrepo. @rikatz, any chance you could comment or email me? Thanks.
