### ISSUE TITLE
docker.socket drop-in unit from cloud config fails

### ISSUE THREAD

**Issue by stelund** [coreos/bugs#1539]
# Issue Report #

## Bug ##
Regression bug in build 1151.
Using docker.socket drop-in unit from cloud config to open docker TCP socket fails.

### CoreOS Version ###
VERSION_ID=1151.0.0
BUILD_ID=2016-08-25-0937

### Environment ###
VMWare in local esx instances. PXE-boots with cloud config.

### Expected Behavior ###
The TCP port should be listened to by systemd and forward connections to dockerd.
### Actual Behavior ###
Systemd does not listen to the tcp port.

docker.socket logs:
Aug 26 06:00:35 localhost systemd[1]: Starting Docker Socket for the API.
Aug 26 06:00:35 localhost systemd[1]: Listening on Docker Socket for the API.
Aug 26 06:00:37 rnd-coreos-mem08 systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, and some socket file descriptors have not been opened yet. The socket unit is not ful..

Supposedly the unit starts too early before the cloud config has been written properly. Looking at the hostname localhost change to rnd-coreos-mem08 in the log file hints of other issues too.

Restarting docker.socket makes systemd start to listen to the tcp port again and forward it correctly to dockerd.

### Reproduction Steps ###

From our cloud config.
coreos:
  units:
  - name: docker.socket
      drop-ins:
        - name: tcp.conf
          content: |
            [Socket]
            ListenStream=4243
    - name: docker.service            # if it matters, i doubt it
      drop-ins:
        - name: rnd-dns.conf
          content: |
            [Service]
            Environment="DOCKER_OPTS=--dns 10.22.0.15 --dns 10.22.0.16"

### Other Information ###
Maybe related to systemd upgrade but did not find anything on systemd's issues which seems to relate to it.

**Comment by crawford** [comment]
If `docker.service` is starting before coreos-cloudinit, it's because either it is enabled or something that depends on it (or socket-activates it) is enabled. You'll have to track down who is starting it using `systemctl list-dependencies`.

Alternatively, you can sidestep the issue entirely if you are willing to using Ignition (supported on VMware and PXE environments). Ignition will run before systemd, so you'll have control over all of the running services.

**Comment by stelund** [comment]
@Crawford okey, we probably have other services which depends on docker.service.

But how is one to ensure cloud config changes are done in the correct order? Shouldn't it write all unit changes before starting systemd?

**Comment by crawford** [comment]
> But how is one to ensure cloud config changes are done in the correct order?

coreos-cloudinit executes units serially, in the order listed. So if your config starts two services (`example1.service` and `example2.service`), coreos-cloudinit will start the first (`example1.service`) and only once it's started (or failed) will start the second (`example2.service`).

> Shouldn't it write all unit changes before starting systemd?

coreos-cloudinit is started by systemd and is typically run long after networkd and journald have started. Ignition, on the other hand, does run before systemd. You will need to convert your cloud-config into an Ignition config (usually a pretty trivial mapping) in order to leverage that tool. If you are interested in that route, I can give you more information.

**Comment by stelund** [comment]
Thanks! I'll have a look at the dependencies on Monday.

**Comment by stelund** [comment]
Here we have it, systemd change.
https://github.com/systemd/systemd/commit/01a8b4675739463b8d6abf0931099b244c6f072b

I've looked more closely at journal and the dependencies. The dependencies looks fine and in journal we can see that nothing has changed really. The Docket.socket starts before cloudinit. Cloudinit writes it's changes and then issues a systemd daemon reload. Then then in journal it spits out:
systemd[1]: docker.socket: Socket unit configuration has changed while unit has been running, and some socket file descriptors have not been opened yet. The socket unit is not fully functional until restarted.

I'll see if I can trigger an restart from cloud config before abandoning all hope and look at ignotion.

**Comment by stelund** [comment]
Yay, great success.

For the future references:
 - name: docker.socket
      drop-ins:
        - name: tcp.conf
          content: |
            [Socket]
            ListenStream=4243
      command: restart

Did the trick!

**Comment by crawford** [comment]
That is a very racy solution. You are restarting the socket long after the service has started, potentially while other processes are trying to use it. The proper solution is to understand the reverse dependency graph for Docker and stop it from running before coreos-cloudinit.

**Comment by stelund** [comment]
We don't use the local docker socket before that. So it will be good enough for now.

Using an different unit for the socket as suggested in Coreos guide "Enable the remote API on a new socket" it recommends to restart the service to take the new socket unit into use manually. Wont that be the same effect with the cloud config? Doesn't look from systemds perspective like it should be necessary tough.

I rather not go into ignition unless I have to. The current cloud config solution is working is working fine.
