### ISSUE TITLE
[coreos/scripts] Add ability to define more forwarding ports

### ISSUE THREAD

**Issue by dol** [coreos/bugs#1556]
# Issue Report

The [qemu-tempalte](https://github.com/coreos/scripts/blob/b84a12ee65664b9537ba85ca7e102159f2e13654/build_library/qemu_template.sh#L203) sets up a user network-
It would be useful to define additional port forwarding like:

```
        qemu-system-x86_64 \
            -name "$VM_NAME" \
            -m ${VM_MEMORY} \
            -net nic,vlan=0,model=virtio \
            -net user,vlan=0,hostfwd=tcp::"${SSH_PORT}"-:22,hostfwd=tcp::8000-:80,hostname="${VM_NAME}" \
"$@"
```

The 'coreos_production_qemu.sh' supports to pass additional Qemu args, but when adding  `-net user,vlan=0,hostfwd=tcp::8000-:80` as addition args the SSH port is not accessable.

```
$ ./coreos_production_qemu.sh -- -net user,vlan=0,hostfwd=tcp::8000-:80
```
# How to fix this issue

Add an additional variable to customize the networking parameters.

```
        qemu-system-x86_64 \
            -name "$VM_NAME" \
            -m ${VM_MEMORY} \
            -net nic,vlan=0,model=virtio \
            -net user,vlan=0,hostfwd=tcp::"${SSH_PORT}"-:22,${QEMU_NETWORK_ARGS},hostname="${VM_NAME}" \
"$@"
```

**Comment by ccomb** [comment]
It would be nice to have but in the meantime, since you have the ssh access to coreos, you can easily create a tunnel to forward a port without changing the script parameter and rebooting :

Say you have a container with http service exposing its port 80 to the port 32768 of the coreos intermediate host, you can access it through the port 8000 of the physical host with:

`ssh -l core -p 2222 -L 8000:localhost:32768 localhost`

And if you set up your `~/ssh/config`, it ends up as just :

`ssh -L 8000:localhost:32768 coreos`

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
