### ISSUE TITLE
iputils use flag for arping

### ISSUE THREAD

**Issue by themicster** [coreos/bugs#1572]
I would like to see arping included in CoreOS as I used it to make sure my gateway knew of ip addresses that have moved to a new machine so my containers can float around my cluster. It used to be included because of a bug in iputils but since has been fixed and the USE flag needs to be set to get it included now.

**Comment by crawford** [comment]
Do you know which version of CoreOS used to include this?

**Comment by johan-adriaans** [comment]
I have the same problem. I updated from 1010 to 1122

**Comment by johan-adriaans** [comment]
I'm not sure if it helps, but 1010.6.0 used to have arping. I have the same problem.

**Comment by johan-adriaans** [comment]
BTW, this is a reasonable workaround: 

    docker run --net=host --entrypoint /usr/sbin/arping --rm alpine:3.4 -c 10 -U -I eth0 123.123.123.123

**Comment by themicster** [comment]
It was in 1010.6.0. That looks like a good work around. But it is a bit slower.

**Comment by coresolve** [comment]
Another point on this. 
When deploying to aws we have public and private subnets. If you are troubleshooting connectivity on a private subnet and have managed to blackhole your traffic. It's useful to have tracepath available without the need to start a toolbox. Since starting a toolbox expects that you have network connectivity.
