### ISSUE TITLE
VirtualBox support in Ignition

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1573]
# Issue Report
### Environment

VirtualBox
### Desired Feature

Ignition should use the Guest Properties interface of VirtualBox to read the user-provided Ignition config.

**Comment by AlexNPavel** [comment]
This has been completed. The current design uses a gpt-formatted raw disk mounted to the machine. The Disk has a partition with GUID="99570A8A-F826-4EB0-BA4E-9DD72D55EA13" and label="Ignition Config Drive". Ignition looks for the partition with the correct GUID in /dev/disk/by-partuuid and the reads the partition as raw data, stripping the ending null bytes that are used as padding (if this is not done, golang's json deserializer crashes). This is done automatically in vagrant via https://github.com/coreos/vagrant-ignition, but will have to be done manually for non-vagrant VirtualBox instances (we should create docs for that).

**Comment by ineentho** [comment]
This issue is the only information that I find on Google when searching for Ignition in Virtualbox, so I'll hijack this issue.

I extracted the vagrant-ignition script into a standalone script if somebody is interested: https://github.com/ineentho/scripts/blob/e22b7f1017021ad98ad5f1a24b1e94fa5d5c3826/virtualbox-coreos/ignition-disk-gen

Using the script I successfully can create a configdrive vmdk ready to attach to virtualbox:
```
cat container-linux-config | ct | ignition-disk-gen > configdrive.img
vboxmanage internalcommands createrawvmdk -filename configdrive.vmdk -rawdisk configdrive.img
```
Also make sure you get the virtualbox version of coreos, I spent some time banging my head against the wall until I realized not all coreos distributions checked for the config drive disk.
