### ISSUE TITLE
parted vs. cgpt - boot issues on bare metal

### ISSUE THREAD

**Issue by tomgillett** [coreos/bugs#159]
**Background information**

> I've got a bizarre issue running CoreOS on bare metal - problem is apparent on 4x machines.
> 
> After a clean install on dedicated hardware I have to run parted over the disk to ensure that the backup GPT is on the end of the disk. Without doing this, the machine hangs on reboot.
> 
> If I run parted, CoreOS will boot once - and only once. Any reboot after that stage fails to come back up. I have to contact my provider to find out why and apparently the message displayed on screen is "no boot devices, sda ok, hardware ok".

**Debugging**
After some debugging with @marineam on IRC:
- Experiment 1: run `cgpt add -i 1 -B0 /dev/sda`. Reboot exhibits same problem.
- Experiment 2: run `cgpt -i3 -S0 -P0 -T0 /dev/sda` and `cgpt -i4 -S0 -P0 -T0 /dev/sda`. Reboot exhibits the same problem...
- Experiment 3: run `parted /dev/sda name 7 OEM-CONFIG-TEST`. Reboot came back up perfectly! Yay!

**Conclusion**

> marineam: mr-spoon: ok, for the time being you aren't going to be able to do normal upgrades. I will review the differences between what parted and what cgpt spits out and see if I can figure out what may be going on.

**Comment by andypost** [comment]
Confirm he trouble after update there's no way to reboot.
on bare metal server (online.net PowerEdge R320) I always got "no such partition" from grub
the next reboot does not find grub
PS: checked on 2 servers

**Comment by crawford** [comment]
@marineam is there anything more to be done with this?

**Comment by marineam** [comment]
In the current beta and alpha versions a major corruption bug in GRUB has finally been fixed and cgpt repair has also been greatly improved. I don't know for sure if those changes fix this issue or not but at the very least troubleshooting further should be easier.

I'm closing this bug due to its old age but feel free to retest and reopen if there is still a problem on these systems.

**Comment by nailgun** [comment]
@marineam 

Unfortunately I'm experiencing the same issue on OVH dedicated server. I'm ready to debug this. Can you direct me what should I do?  I've already tried to install CoreOS from stable, beta and alpha channels with no luck. Fixing GPT table using `parted` or `cgpt repair` didn't help too.

Now I've ordered an KVM-over-IP interface and waiting for it to be installed.

BTW. I don't believe in that now, but my first installation on the same machine did boot well. After that I've reinstalled CoreOS and the second installation as well as any following didn't boot. It's quite weird.

**Comment by nailgun** [comment]
I've got an access to the bare-metal terminal. But it's only for 1 day. So any help in debugging is highly appreciated.

**Comment by nailgun** [comment]
OK, here is my report. :) The problem is actually GPT.

I will start from the beginning. From your hosting control panel you can setup boot source for any server. It can be Hard disk, iPXE, Rescue image and Rescue kernel.

By reading BIOS boot messages I've found that server is always configured to boot from PXE, even if you selected *Hard disk* source. The only thing changes is which PXE image datacenter's DHCP server returns. In case if you selected *Hard disk*, returned PXE image just tries to boot from local disk.

Looks like this PXE image determines that CoreOS boot partition is not valid and hangs asking you to insert valid bootable media. I've recorded [video](https://youtu.be/6zfX3Re6sqI) with these BIOS messages.

If I manually select hard drive in boot menu, the system boots normally. I don't know implementation details about how GPT works, but looks like it's boot code is in the [same location](https://en.wikipedia.org/wiki/GUID_Partition_Table#Hybrid_MBR_.28LBA_0_.2B_GPT.29) as in MBR.

I don't like to contact OVH tech support. I'm sure they won't change their production solution for a lone hacker. Another solution is to change BIOS config for every server to boot from HDD by default, but this is time and cost ineffective. I've found quite a simple workaround.

I've tried to use iPXE bootloader's command `sanboot` with no luck. It also checks MBR magic bytes like a PXE.

Also I've tried to dump first 512 bytes of an HDD and use them as an image in iPXE's `chain` command. This just prints `GRUB` to the terminal and nothing more.

For now I don't have any ideas how to deal with GPT on OVH.

**Comment by crawford** [comment]
@nailgun unfortunately, @marineam is on holiday until December. I'll re-open this and assign it to him.

**Comment by nailgun** [comment]
[I've asked](http://stackoverflow.com/questions/40418002/boot-from-local-gpt-drive-using-ipxe) Stack Overflow for the help.

**Comment by crawford** [comment]
I looked at this again a bit more closely and now I'm quite confused. CoreOS Linux supports a hybrid boot pattern (either MBR or GPT will work). If you dump the first 512 bytes of the disk (`xxd -l 512 -g 1 /dev/vda`), you'll see the GRUB stage-1 and the 0x55 0xAA boot signature. If you mount the first partition, you'll also see the `EFI/boot` directory containing an EFI application (GRUB, in this case). If your provider thinks this image is unbootable, either its firmware is confused by the hybrid pattern or it's looking at the wrong disk. Is there just one disk attached to this machine? Can you confirm that these machines are supposed to be able to boot MBR and/or GPT? You might need to file a bug with them if this turns out to be a firmware issue.

**Comment by nailgun** [comment]
After some struggling I came to the same. Looks like it's firmware issue. I've filed a ticket to OVH support and waiting for answer.

Anyway I am confused why iPXE can't boot from the disk. I tried this command `sandisk --no-describe --drive 0x80`. Does it still depend on firmware?

> Can you confirm that these machines are supposed to be able to boot MBR and/or GPT?

The server is legacy BIOS, so it able to boot MBR drives. There is no problem with classic MBRs.

> If you dump the first 512 bytes of the disk (xxd -l 512 -g 1 /dev/vda), you'll see the GRUB stage-1 and the 0x55 0xAA boot signature. If you mount the first partition, you'll also see the EFI/boot directory containing an EFI application (GRUB, in this case).

Yeah, I've checked this too. So it's very confusing.

> Is there just one disk attached to this machine?

There're 3 SSD disks. But I've installed other OSes on the first drive and they did boot.

**Comment by crawford** [comment]
Does the suggestion listed on http://www.syslinux.org/archives/2006-August/007139.html help at all? Not sure if you have control over the PXE menu.

**Comment by nailgun** [comment]
I have a limited control over PXE server. I can select one of 4 PXE configs:
 * boot from hard drive (resulting [PXE config contains exactly `localboot 0`](https://gist.github.com/nailgun/38e65fb64c0015b7cb88ef2b7614b622))
 * chain boot iPXE with custom config
 * [boot rescue image](https://gist.github.com/nailgun/83026d55273f2db41f70403d7f15b074)
 * boot selected kernel with selected root partition.

PXE configs from the links above I've got from datacenter's DHCP server using tftp client.

Nor PXE's `localboot 0` nor iPXE's `sandisk --no-describe --drive 0x80` don't work. They don't identify drive as bootable for some reason. At [this video](https://youtu.be/6zfX3Re6sqI) I'm trying to boot using PXE's `localboot 0`. iPXE gives the same result.

Also I have tried to reproduce the same setup on VirtualBox. I've installed CoreOS on a disk, then used iPXE iso image to boot with `sandisk` command. And it works well. So looks like iPXE still depends on firmware to boot from a disk.

**Comment by crawford** [comment]
Okay, thanks for digging in. I don't think there is much we can do here without more info from the provider. It looks like something is wrong with the firmware on those machines.

**Comment by nailgun** [comment]
Yeah. I spent 25 euros :) and many hours to understand how their servers boot. Hope they will try to do something with this.

**Comment by felixkrohn** [comment]
Hi,
This particular mainboard has already caused plenty of headache, it is indeed broken in relation to GPT. (many issues)
If you want to use this server, try and install it in MBR format, not GPT.
Other possibility would be to use another server with a compatible mainboard, in which case you can simply install coreOS from the OVH customer interface ("stable" and "alpha" channels are available)
The setting that the server first tries to boot from the NIC is wanted and needed, without this you won't be able to reboot in rescue (nor reinstall the server).

**Comment by nailgun** [comment]
@felixkrohn thanks! Can you please give an advice on OVH server that I can order that is comparable to E3-SSD-3 about performance and cost and which is compatible with CoreOS?

**Comment by crawford** [comment]
@felixkrohn thanks for confirming. Sounds like this is an OVH-specific issue. I'm going to close this out.

**Comment by felixkrohn** [comment]
@nailgun My colleague sent you a list this morning, hope you were able to pick one of your liking.
@crawford  ACK for closing (Just want to add for future search karma: it's not purely OVH-specific but Intel DH67BL/DH61AG/DH67VR-specific - of which we happen to have a certain number)

**Comment by nailgun** [comment]
@felixkrohn 

I've found that setting **Boot -> UEFI Boot** BIOS option to **Enabled** fixes all issues. And this doesn't break legacy MBR boot sequence. See [screenshot of the option](https://monosnap.com/file/TzwBr6VNjWRIzEt57M7XXhEygrjQvP).

Is it possible to request setting this option before server installation? Ordering KVM-IP for every installation is too expensive and too long.

**Comment by felixkrohn** [comment]
@nailgun it actually does break things, because when the firmware finds a GPT partition table on disk it will skip netboot, and thus thwart all future attempt to boot in rescue (or reinstallation) mode :-(

**Comment by nailgun** [comment]
Sorry, you're right.

**Comment by nailgun** [comment]
Anyway I don't understand why iPXE [doesn't detect](https://monosnap.com/file/iGRCDb1uBTaDzNb4p0ZolAVTR4i0jx) MBR on disk. This is output of my custom built iPXE image with debug enabled. This is the [source code](https://git.ipxe.org/ipxe.git/blob/master:/src/arch/x86/interface/pcbios/int13.c#l1749) of MBR check.

**Comment by crawford** [comment]
@felixkrohn excellent. I'll add those machines to my blacklist.
