### ISSUE TITLE
On AWS, allow ignition to use IAM credentials to fetch files from S3

### ISSUE THREAD

**Issue by Sodki** [coreos/bugs#1631]
### Environment

AWS
### Desired Feature

Ignition can fetch files from a remote location. A good use case is to have a protected S3 bucket that the instance has access in order to - securely - store it's config. It would be good if Ignition could use the information in metadata to automatically fetch files from S3 with the right credentials.

**Comment by crawford** [comment]
Related to https://github.com/coreos/bugs/issues/1067.

**Comment by cemo** [comment]
Is this issue also solving user-data limit on AWS right now, isn't it? I have no idea about ignition but AWS is imposing 16K user data limit on instances. I have to stick with cloud init right now since I can not find a way to move ignition because of user data limit.

**Comment by crawford** [comment]
@cemo the 16K userdata limit is imposed on both Ignition Configs and cloud-configs. Are you compressing your cloud-configs to avoid the limit? With Ignition, you can use the `ignition.config.replace` option to bypass the userdata limit. You'll need to host the full config somewhere that is accessible by your instance (I recommend S3 with a signed URL to protect the config from unauthorized access).

**Comment by kim** [comment]
@crawford what do you recommend for autoscaling groups?

**Comment by crawford** [comment]
@kim if you can fit the full config in the userdata, that is definitely the way to go. What issues are you running into?

**Comment by cemo** [comment]
He has probably same issue as me. It can not fit into userdata and autoscale can run anytime. Current state of ignition is not helping us at all.

**Comment by kim** [comment]
Yes, presigned V4 S3 URLs don't help much with ASGs if the userdata limit is exceeded, as their maximum validity is seven days.

What are the concerns against introducing "native" S3 support? Larger dependency footprint, especially since other cloud providers may have to be supported as well down the road? Want to encourage people to use higher-level orchestration such as kubernetes for anything more involved than the bare necessities to bootstrap an instance?

I'd argue that, for some, the latter is too intrusive / too much overhead to get started with. Perhaps support for etcd as a source for the replace feature would be something you'd be willing to consider? This based on the reasoning that etcd is kind of implied when running a Container Linux cluster, and this could be something to standardise on as opposed to supporting N cloud storage APIs. What do you think?

**Comment by saracen** [comment]
I've hit this issue too.

I don't have the chance to test at the moment, but I was thinking in the short term I could use some basic ignition configuration to setup a lightweight HTTP server for accessing configuration from different sources.

Then I'd be able to use `ignition.config.append` to pull in from the locally running server any additional config. In this instance, I could have https://github.com/cllunsford/aws-signing-proxy running in a docker container which will sign the requests using IAM credentials automatically.

Has anybody tried something similar? It might not work because I'm not entirely sure when ignition will attempt to pull in additional remote config. If it's before any other setup, the docker container won't be running. Even if it's executed after, will ignition poll the remote config URL until the reverse proxy container is up and running?

**Comment by kim** [comment]
@saracen you can't use ignition to provision (prerequisites for) ignition, so, unless you boot from a custom initramfs, this approach would only work if you run the proxy on a separate instance. Unless you require access control for the remote ignition configs (eg. via IAM policies), that's a perfectly fine workaround.

**Comment by saracen** [comment]
@kim Thanks for the heads-up. Creating additional instances to support this would be a shame :(

**Comment by crawford** [comment]
> What are the concerns against introducing "native" S3 support?

@kim there are no concerns, which is why we are [working on it](https://github.com/coreos/ignition/pull/382). :smiley:

> It might not work because I'm not entirely sure when ignition will attempt to pull in additional remote config.

@saracen as @kim mentioned, this won't work because Ignition will fully render its config before it attempts to start executing it. Since Ignition runs before the rest of the system, you won't be able to do what you described.

**Comment by cemo** [comment]
BTW, Does Ignition support gzip+base64 for whole file?

**Comment by cemo** [comment]
@crawford BTW, Does Ignition support gzip+base64 for whole file?

**Comment by kim** [comment]
> there are no concerns, which is why we are working on it. 

Ha! 😁
Much appreciated, thanks!

**Comment by crawford** [comment]
@cemo No, it does not. We decided not to implement that in Ignition and instead opt for the more robust solution.
