### ISSUE TITLE
No network after upgrading from 1122.3.0 to 1185.3.0

### ISSUE THREAD

**Issue by klausenbusk** [coreos/bugs#1649]
# Issue Report #
One of my node rebooted today to update from 1122.3.0 to 1185.3.0, as my reboot window is today.
```
Environment="LOCKSMITHD_REBOOT_WINDOW_START=Sat 14:00"
Environment="LOCKSMITHD_REBOOT_WINDOW_LENGTH=2h"
```
## Bug ##
The node rebooted successful, but network isn't configured it seems (I can't ssh/ping it).

### CoreOS Version ###
Stolen from similar not upgraded node.
```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.3.0
VERSION_ID=1122.3.0
BUILD_ID=2016-10-20-2045
PRETTY_NAME="CoreOS 1122.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###
DigitalOcean

### Expected Behavior ###
That it just reboot, get network and connect to the cluster.

### Actual Behavior ###
Node was started without network.

### Reproduction Steps ###
  1. Upgrade a node hosted at DigitalOcean from 1122.3.0 to 1185.3.0

### Other Information ###
None

**Comment by bkleef** [comment]
My two upgrades to 1185.3.0 are stuck in grub at DO.

**Comment by klausenbusk** [comment]
I have opened a DO ticket asking for the node to be started in recovery mode. Then I change change the pw and hopeful debug what is going on..

**Comment by crawford** [comment]
@klausenbusk I'm guessing your machines are particularly old. A little while back we had to change the way CoreOS configures its network on DigitalOcean (they don't support DHCP yet). You'll need to add `coreos.oem.id=digitalocean` to your kernel parameters in order to get the network going again. You can add this parameter to your GRUB or SYSLINUX config (depending on how old the machine is). What was the original version that was booted?

@bkleef that sounds like a different issue. Would you mind filing a new bug report with more info?

**Comment by klausenbusk** [comment]
@crawford That particular node and most of my nodes started as 766.4. They around 1 year old..

DO support just responded back, let see if coreos.oem.id=digitalocean works..

**Comment by crawford** [comment]
With 766.4.0, you'll be able to add the following to `/usr/share/oem/grub.cfg`:

```
set oem_id="digitalocean"
```

You can remount `/usr/share/oem` read/write (`mount -o remount,rw /usr/share/oem`) so that you can add or change that file.

**Comment by klausenbusk** [comment]
> set oem_id="digitalocean"

Didn't help sadly, but I access to the core user from DO console now so..

**Comment by klausenbusk** [comment]
@crawford I finally got it working.

It seems like `oem_id` isn't working, or dosen't work in cooperation with `linux_append`.
First I tried:
```
set oem_id="digitalocean"
set linux_append="coreos.autologin=tty1"
```
`linux_append` just for autologin if network didn't work.

Then I tried:
```
set oem_id="digitalocean"
set linux_append="coreos.autologin=tty1 coreos.oem.id=digitalocean"
```
Which worked, so.. Is oem_id broken?

It isn't ideal that old CoreOS installs just suddenly break, but I'm not sure what could be done about it.. :/

**Comment by crawford** [comment]
> Which worked, so.. Is oem_id broken?

Sorry, that was my mistake. `oem_id` didn't exist yet. You should be able to just get away with:

```
set linux_append="coreos.oem.id=digitalocean"
```

> It isn't ideal that old CoreOS installs just suddenly break, but I'm not sure what could be done about it.. :/

Agreed. We have canary machines that run on all of our supported platforms, but evidently they weren't old enough to catch this issue. We also didn't see anyone effected by this issue while the change worked its way through Alpha and Beta.

Glad you got the node working again. Thanks for your patience.

**Comment by klausenbusk** [comment]
> Sorry, that was my mistake. oem_id didn't exist yet. You should be able to just get away with:

So support for oem_id depends on the initial version of CoreOS?
If I login into to one of my most recent node, they already contain a grub.cfg file with:
```
# CoreOS GRUB settings

set oem_id="digitalocean"
```

**Comment by crawford** [comment]
> So support for oem_id depends on the initial version of CoreOS?

Correct. The automatic updates don't update the bootloader. When I was looking at the history of the GRUB configuration in our repos, I hadn't gone back far enough.

**Comment by berry2012** [comment]
@crawford i have similar issue but with an extra issue as well. Can't SSH/Ping my critical servers and can't send Ctrl + Alt Delete to the console so as to reset the password.

This is all could find in one of the servers that I could still access
core@mainserver /usr/share/oem $ ls
cloud-config.yml  lost+found  oem-release

I want to set linux_append="coreos.oem.id=digitalocean" for this server. How do I achieve this in  a step by step approach.


Also Can anyone assist on how to send Ctrl + Alt Delete to the console so as to reset the password?

**Comment by klausenbusk** [comment]
> @crawford i have similar issue but with an extra issue as well. Can't SSH/Ping my critical servers and can't send Ctrl + Alt Delete to the console so as to reset the password.

That sound exactly like the issue I had. What I did was to contact DigitalOcean support and asked them to boot the server with their recovery image.
I then mounted the oem partition, created grub.cfg containing `set linux_append="coreos.autologin=tty1 coreos.oem.id=digitalocean"` (coreos.autologin=tty1 shouldn't be needed, but autologin is useful if network still isn't working), saved it and unmouted the oem partition. I then asked DO to reboot the server without the recovery image and the server got network again :)

> I want to set linux_append="coreos.oem.id=digitalocean" for this server. How do I achieve this in a step by step approach.
```
sudo mount -o remount,rw /usr/share/oem
vi /usr/share/oem/grub.cfg
insert set linux_append="coreos.oem.id=digitalocean"
voila
```

**Comment by berry2012** [comment]
Hi, @klausenbusk doesn't look like i can mount /usr/share/oem 

release is 766.5

<img width="612" alt="screen shot 2016-11-13 at 12 54 05 pm" src="https://cloud.githubusercontent.com/assets/10167641/20245579/8e29268c-a9a4-11e6-867f-324a47fb0356.png">

**Comment by klausenbusk** [comment]
> Hi, @klausenbusk doesn't look like i can mount /usr/share/oem

Hi @berry2012, that remount command only work for a running CoreOS server.
In the recovery environment you need to mount the oem partition somewhere and add a grub.cfg file.
I think it is `/dev/vda6` that at least what it is on my running CoreOS system.
So something like `mount /dev/vda6 /mnt`, maybe something is already mounted on `/mnt`, if that is the case just umount it first `umount /mnt`.

**Comment by berry2012** [comment]
@klausenbusk looks like it /dev/vda9 in my case.

<img width="721" alt="screen shot 2016-11-13 at 3 50 30 pm" src="https://cloud.githubusercontent.com/assets/10167641/20246538/f424a010-a9b8-11e6-978f-ff01aab328c5.png">

**Comment by berry2012** [comment]
This is what i discovered.
No such folder as oem in my `/usr/share` folder. So I manually created oem. 
`/mnt` is currently mounted. `unmount /mnt` gives command not found.
<img width="637" alt="screen shot 2016-11-13 at 4 04 18 pm" src="https://cloud.githubusercontent.com/assets/10167641/20246626/fa2e0256-a9ba-11e6-990d-b0c619693458.png">

**Comment by klausenbusk** [comment]
> @klausenbusk looks like it /dev/vda9 in my case.

It only show that `/dev/vda9` is already mounted, `/dev/vda9` is for `Stateful partition for storing persistent data` (https://coreos.com/os/docs/latest/sdk-disk-partitions.html)..

> /mnt is currently mounted. unmount /mnt gives command not found.

`umount` not `unmount`.

> No such folder as oem in my /usr/share folder. So I manually created oem.

Why? :) You should just mount `/dev/vda6` somewhere and create `grub.cfg`.
Creating `/usr/share/oem` change nothing.. :) `/usr/share/oem` is a mount point in CoreOS, but in that recovery environment it is nothing..

**Comment by berry2012** [comment]
@klausenbusk been able to resolve this thanks to your help.
Can ping and SSH into the servers now.

mounted `/mnt` on `/dev/vda6` and created grub.cfg

cheers

**Comment by nponeccop** [comment]
JFYI I had the same problem but my original version was around 540 so I suppose it was too old for the workarounds above.

What I had to do:

- Requested suport to boot from the recovery ISO
- Entered the shell (option 6)
- Used blkid to identify the EFI partition
- Mounted it
- Changed timeouts in `syslinux/syslinux.cfg` - the default timeout was 0.1 second which made impossible for me to see the boot menu in the web shell. I found that a value as large as 150 (15 seconds) is necessary.

This step sort of future-proved my CoreOS installation so I can recover from more scenarios without asking for the ISO. After that I could manually add `coreos.oem.id=digitalocean` by pressing `e` in the standard CoreOS boot menu.

Also, you can test boot your droplet without disabling the recovery ISO. To test boot:

- Enter the shell from web console
- Enter `reboot`
- With this approach the web console is kept open and runs across reboots, unlike power cycling from the DigitalOcean panel. So the latency is lower and you can see the blue boot menu of the recovery ISO.
- That menu has an option to boot off the hard drive, but it's wrong as CoreOS uses GPT instead of MBR.
- So you need to press `c` and enter 3 chainloading commands:
   - `set root=(hd0)`
   - `chainloader +1`
   - `boot`

Note that the root has no indication of the boot partition and only mentions the drive.

I already told DO about this issue so their ISO boot menu may be fixed in the future.
