### ISSUE TITLE
/etc/environment not populated correctly when using ignition in aws/ec2

### ISSUE THREAD

**Issue by r0p0s3c** [coreos/bugs#1699]
# Issue Report #

### CoreOS Version ###
1185.3.0
### Environment ###
AWS/ec2

### Expected Behavior ###
/etc/environment is populated with provider metadata by coreos-metadata, as occurs when using cloud-config 

### Actual Behavior ###
/etc/environment is empty

### Reproduction Steps ###

  1. provide empty or simple ignition configuration via user-data when creating instance
  2. check /etc/environment

### Other Information ###
Sample configs used are as shown at https://gist.github.com/r0p0s3c/3d4a74501f2ca2f284bad968d7c57dc4

I have also tried an ignition configuration as follows to ensure there's no corner case involving an "empty" ignition configuration (taken from examples in documentation), with the same results:
```
{
  "ignition": { "version": "2.0.0" },
  "storage": {
    "files": [{
      "filesystem": "root",
      "path": "/home/coreos/testfile",
      "contents": { "source": "data:,example%20file%0A" }
    }]
  }
}
```

Running coreos-metadata manually seems to do the right thing:

``` 
$ coreos-metadata --provider ec2 --attributes /dev/stdout
fetching "http://169.254.169.254/2009-04-04/meta-data/instance-id": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/public-ipv4": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/local-ipv4": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/hostname": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/public-keys": attempt #1
fetching "http://169.254.169.254/2009-04-04/meta-data/public-keys/0/openssh-key": attempt #1
COREOS_EC2_IPV4_PUBLIC=54.175.24X.XXX
COREOS_EC2_HOSTNAME=ip-172-31-XX-XXX.ec2.internal
COREOS_EC2_INSTANCE_ID=i-032395c2e55XXXXX
COREOS_EC2_IPV4_LOCAL=172.31.XX.XXX
```

According to logs, using either cloud-config or ignition config proceeds normally until the following is logged:

```
coreos-cloudinit[914]: Detected an Ignition config. Exiting...
```

**Comment by r0p0s3c** [comment]
One other thing, /run/metadata/coreos is not being populated when running with ignition either. Manually starting the coreos-metadata service does populate that file

**Comment by crawford** [comment]
`/etc/environment` is a construct of coreos-cloudinit. `coreos-metadata` uses the runtime location `/run/metadata/coreos` instead to allow namespacing. This service does not start by default since it may not be needed. If your service requires that information, you'll need to use `Requires=coreos-metadata.service` and `After=coreos-metadata.service` to ensure that data is available when it's needed.

> According to logs, using either cloud-config or ignition config proceeds normally until the following is logged:

userdata can either be an Ignition config (preferred) or a cloud-config. If either tool detects a config meant for the other, it will ignore the config and log a message to that effect.

The recommended path forward is Ignition + coreos-metadata. You can find some examples in the [documentation](https://coreos.com/ignition/docs/latest/metadata.html).

**Comment by r0p0s3c** [comment]
Thanks for the clarification. Given the number of examples using /etc/environment, might be something worth documenting

**Comment by crawford** [comment]
Agreed. I'm working on overhauling our documentation, but it's a slow process :(

Can I close this out or are you still having trouble?

**Comment by r0p0s3c** [comment]
Feel free to close, thanks
