### ISSUE TITLE
Ignition - create directories - old PR not merged?

### ISSUE THREAD

**Issue by felixsanz** [coreos/bugs#1709]
#1290 is closed but it's only merged onto the `spec` branch, not inside `master`. What does that mean? Apparently the feature is not implemented on CoreOS stable because it doesn't seem to work.

**Comment by crawford** [comment]
Ignition's implementation is driven by a versioned specification. In order to add new functionality like the one you mentioned, we need to release a new version of the spec. Instead of going through the effort of releasing a new spec revision every time we want a feature, we batch them together in a branch (the `spec` branch). The current list of features we'd like to include in the next spec bump can be seen in our milestones (https://github.com/coreos/bugs/milestone/46).

I agree it's a little confusing that the bug is closed before the functionality is available, but that is how just about everyone does it (and I can't think of a better way).

**Comment by felixsanz** [comment]
@crawford That makes sense, thanks.

But here is a request. Can the team consider faster release cycles of the spec? The list starts almost 1 year from now. Waiting 1 year for features is way too much i think. I agree that batching is good and some trivial features are not worth pushing of the spec version, but shouldn't the team agree on a release cycle? Like pushing the spec version every 3 or 6 months?

And also, any plans to do it soon?

I would love having those features pushed because i'm waiting for some of them, but apart from personal motivation i think what i propose is a good idea.

I'm gonna close this since the question is solved but feel free to re-open if you consider so (discussion or something)
