### ISSUE TITLE
Ship an updated etcdctl

### ISSUE THREAD

**Issue by brianredbeard** [coreos/bugs#1717]
# Issue Report #
Please ship an updated etcdctl as it includes support for both API versions via the `ETCDCTL_API` variable.

**Comment by crawford** [comment]
We are going to hold off on this until etcd0 has been removed from the OS (May 7th). Then we can easily bump to the latest v2 binary and not have to worry about backward compatibility.

**Comment by dm0-** [comment]
The last alpha shipped the etcd2 version of `etcdctl`.

**Comment by crawford** [comment]
We actually need the v3 version of etcdctl. This will support both v3 and v2. Since we are going to be removing etcd2 early next year, I think we should instead ship etcd and etcdctl together, independent of the OS. Right now, it's looking like torcx will be the answer to this. That will allow users to install whichever version of etcd they'd like and get a matching etcd and etcdctl.

**Comment by shamalco** [comment]
Is there yet an expect time period or release for this enhancement ?

**Comment by dm0-** [comment]
This is merged for the next alpha in coreos/coreos-overlay#2720.
