### ISSUE TITLE
sys-boot/grub-2.02_beta2_p20151217-r10: Enable powerpc64le platform in grub-core/net/bootp

### ISSUE THREAD

**Issue by houstar** [coreos/bugs#1723]
# Issue Report #

### CoreOS Version ###
1248.0.0
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1248.0.0+2016-12-17-1006
VERSION_ID=1248.0.0
BUILD_ID=2016-12-17-1006
PRETTY_NAME="CoreOS 1248.0.0+2016-12-17-1006 (Ladybug)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
#uname -a
Linux coreos 4.9.0-coreos #1 SMP Fri Dec 16 06:37:47 2016 ppc64le POWER8E (raw), altivec supported CHRP IBM pSeries (emulated by qemu) GNU/Linux

### Environment ###
On powerpc64le platform

### Expected Behavior ###
emerge grub successfully
### Actual Behavior ###
failed with emerge grub which coreos developed
### Reproduction Steps ###

  1. #emerge grub
  2.  failed with below log
/var/tmp/portage/sys-boot/grub-2.02_beta2_p20151217-r10/work/grub-2.02_beta2_p20151217/grub-core/net/bootp.c:35:2: error: #error "unknown bootp architecture"
 #error "unknown bootp architecture"
  ^

### Other Information ###

I commented this issue in 
https://github.com/coreos/grub/commit/fbf65674a471d12e43f4050086969f417e00891f

**Comment by houstar** [comment]
@mischief  @marineam  

I've opened new issue to track the grub issue

**Comment by mischief** [comment]
@houstar, this can be fixed, but it should be fixed with the correct code.

this code implements the bootp protocol. it needs to send the architecture option (93) to the remote server so that it knows what files to send back based on the architecture of the machine.

it appears there's some standardized codes at http://www.iana.org/assignments/dhcpv6-parameters/dhcpv6-parameters.xhtml#processor-architecture for POWER/PowerPC, but i can't find anything for UEFI, and it appears that PPC64LE support for UEFI is not standardized by UEFI.org yet..

**Comment by houstar** [comment]
@mischief Yes. There is no UEFI for powerpc. We're using this fireware:

0x00 0x0e	POWER OPAL v3	[Jeremy_Kerr]

Could you define this for net/bootp? thanks

**Comment by houstar** [comment]
@marineam @mischief  

This [PR#43](https://github.com/coreos/grub/pull/43) works fine with me.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
