### ISSUE TITLE
Ignition to handle octal file modes

### ISSUE THREAD

**Issue by jhmartin** [coreos/bugs#1729]
# Issue Report #

### Environment ###

EC2

### Desired Feature ###
Ignition requires that file modes be passed in decimal form, which is not how most admins will be used to viewing them. This causes confusion when viewing ignition configurations and is against 'least surprise'.  It should accept file modes in the same form as chmod.

**Comment by crawford** [comment]
JSON does not support octal numerals, so decimal is required. The Ignition configs themselves should be treated as an intermediate representation and therefore not easily readable by humans. We recommend using [ct](https://github.com/coreos/container-linux-config-transpiler) (which is still under very active development) to generate the Ignition configs. Because ct uses YAML, it's possible to use octal to represent file modes.

**Comment by jhmartin** [comment]
The mode could be passed as string.

**Comment by crawford** [comment]
If we were to do that, it would defeat the advantage of JSON's type system and make it more difficult to generate the configs (both of which are major goals of the project). We made the mistake of allowing strings or numerals to represent file modes in coreos-cloudinit and I'm not keen to repeat it.

What problem are you trying to solve by allowing octal file modes? Reading or writing configs?

**Comment by jhmartin** [comment]
@crawford Human interaction -- seeing a 'modes' field that takes a numeric feels like it should support the same input as chmod.  I didn't notice the decimal requirement the first time. Certainly it was easy to pull up calc and get the correct number after I realized my mistake, but I foresee that other people on my team who aren't familiar with ignition will see 'mode' : 384 and be confused.  Decimal is 'close enough' to octal that it isnt immediately obvious it is different.  It is just so common to see file modes expressed on chmod octal, symbolic, or umask format that seeing them in decimal is very surprising.  The lack of commenting in json means I can't leave a contextual crumb for the next person either.

Further, when looking at a node and trying to understand its configuration the reader will have access to the EC2 userdata / json and not the input ct, so an easier to understand ct representation won't help them in reading it and understanding what is happening and troubleshoot whatever issue drew their attention in the first place.  However if something did break, this odd looking field would be distracting from the real issue since it 'looks' wrong. 

This isn't a problem in the sense that I can't make the appropriate conversions, but I do believe it is a usability gotcha.

**Comment by crawford** [comment]
These are all fair points and ones that I really don't have great answers for. I think it's going to be a matter of making our documentation really solid. Admins shouldn't need to look at the raw Ignition config often (if they do, we need to address that separately), so I'm not as concerned about this use case as I am about the generation of the config.

> Renaming the field to 'decimalmode' or something like that might cover it; 'mode' instantly brings to mind chmod syntax.

`chmod` actually refers to the "mode" string as "octal-mode", so Ignition using "mode" seems more correct than "decimalmode". Adding an extra field would require a minor spec version bump and would allow a conflict between "mode" and "decimalmode". Replacing the field completely would require a major spec version bump and would making programmatic generation more difficult, going against the original goals of the project.

**Comment by f0o** [comment]
This is ridiculous - anything trying to incorporate ignition is taking your docs literal so all of a sudden an average system administrator will write octal as mode into for example terraform and completely mess up the ignition file in unforeseen ways.

With the recent release of ignition 2 this is still something I had to fix manually from my junior because, and I have to agree with him, it makes no sense whatsoever calling a decimal representation of chmod's mode merely `mode`. It's wrong even on a semantical level.
