### ISSUE TITLE
container-linux-config-transpiler: binary release process

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1778]
## Feature Request ##

container-linux-config-transpiler is a user facing tool and should have signed releases made available for every platform (linux, windows, osx) just like other tools under github.com/coreos like etcd.

**Comment by danderson** [comment]
It would also be nice to make the tool `go install`able. As it stands, installing and maintaining the installation if you don't care about having a specific version (as I don't) is irritating enough that I just write json ignition configs instead :)

**Comment by dgonyeo** [comment]
I'll make sure the next release has signed binaries for every platform.

I'm not sure making the tool `go install`able is ideal, we wouldn't be able to set the flags we do in the build script (since `go install` is not configurable from the project's side) and other CoreOS projects (like etcd and rkt) are not `go install`able.

**Comment by dgonyeo** [comment]
The [most recent ct release](https://github.com/coreos/container-linux-config-transpiler/releases/tag/v0.2.0) has signed binaries for windows, linux, and macos available.
