### ISSUE TITLE
ignition: user creation no longer also creates group

### ISSUE THREAD

**Issue by euank** [coreos/bugs#1787]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.1.0
VERSION_ID=1298.1.0
BUILD_ID=2017-01-20-0552
PRETTY_NAME="Container Linux by CoreOS 1298.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

GCE

### Expected Behavior ###

Creating a user with ignition also creates a group with the same name

### Actual Behavior ###

It worked up until 1284. Post-1284 (with the shadow-4.4 update presumably), a group is no longer created.

### Reproduction Steps ###

1. Boot a machine using the following user-data: `{"ignition":{"version":"2.0.0","config":{}},"storage":{},"systemd":{},"networkd":{},"passwd":{"users":[{"name":"foo","create":{}}]}}`
2. grep foo /etc/group

**Comment by dm0-** [comment]
This is from a [shadow commit](https://github.com/shadow-maint/shadow/commit/65c261714027d6d2bcf10cd103c5209ae9f7617f#diff-be0041ab36b03b95f538f6a87a99b457R1997) that loads the default configuration files before changing into the target root directory.  This change in behavior in shadow probably wasn't intentional, but I've updated our initramfs anyway at coreos/bootengine#102 to carry the same defaults for `useradd`.
