### ISSUE TITLE
coreos-cloudinit - requesting to mirror more features of the python implementation 

### ISSUE THREAD

**Issue by signull** [coreos/bugs#1790]
# Issue Report #

Would love the features like `ca-certs` and `runcmd` or `bootcmd` from the python cloud-init version included in coreos version.  For instance for `ca-certs` sure i could use `write-file` and then create a unit definition in systemd just to run `update-ca-certificates` which is really over the top just to get my docker trusted authority working as well as other internal sites. For something like `runcmd` or `bootcmd` i would love the ability to make a run once few line bash script without wastefully creating a whole unit file to have that set to run once and never again. 

## Bug ##

```
Feb 02 15:45:37 core-01 coreos-cloudinit[1356]: 2017/02/02 15:45:37 line 9: warning: unrecognized key "runcmd"
Feb 02 15:45:37 core-01 coreos-cloudinit[1356]: 2017/02/02 15:45:37 line 46: warning: unrecognized key "ca_certs"
```

### Container Linux Version ###

```
core-01 ~ # cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.1.0
VERSION_ID=1298.1.0
BUILD_ID=2017-01-20-0552
PRETTY_NAME="Container Linux by CoreOS 1298.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
core-01 ~ #
```

### Environment ###

AWS and Vagrant

### Expected Behavior ###

That cloud-init may be a bit more flexible and run some features found in the python version.

### Reproduction Steps ###

  1. Use coreos-cloudinit.
  2. Assume you have the same options as the original python implementation.
  3. facepalm as you reallize you have to wastefully create systemd services.
  4. hopefully understand my humor.

### Other Information ###

Here's a picture of a cute cat to sway you:
![cute kitty wanting feature](http://i.imgur.com/i9lRNhA.jpg "I can haz features?")

## Feature Request ##

- `ca-certs`
- `runcmd` or `bootcmd`

### Environment ###

AWS and Vagrant

### Desired Feature ###

- `ca-certs`
- `runcmd` or `bootcmd`

### Other Information ###

Love all your stuff, I want some wiggle room to sway the company i work for to use it so we can go tectonic one day soon.

**Comment by crawford** [comment]
The biggest disservice we did was naming the thing "cloud-init". It is nothing like Canonical's cloud-init and only causes confusion and frustration. Because of the poor design, we've decided to cease further development on coreos-cloudinit and instead invest in [Ignition](https://coreos.com/ignition/docs/latest/) and [CT](https://coreos.com/os/docs/latest/overview-of-ct.html). I think it's perfectly reasonable to add this functionality to CT and potentially Ignition. What do you think?

And god dammit that is a cute kitten.

**Comment by bgilbert** [comment]
I've filed the `ca-certs` part as https://github.com/coreos/bugs/issues/2071.

I don't think adding CT sugar equivalent to `runcmd` or `bootcmd` is a good idea, since we'd eventually want a way to specify dependencies between those commands and other units, and soon we'd find ourselves reimplementing unit files piece-by-piece inside CT.  If you want to run arbitrary commands at boot, please just create a systemd unit for them; that's what CT would do behind the scenes anyway.

coreos-cloudinit is no longer actively developed, so I'll close.
