### ISSUE TITLE
Package.use why are values masked?

### ISSUE THREAD

**Issue by pgburt** [coreos/bugs#1822]
### Environment ###

Latest build 

### Desired Feature ###

Urzds in IRC asks: 
> Why are RESTRICT=mirror and RESTRICT=bindist ebuilds masked in CoreOS SDK? And how do I unmask them?

For the `package.use` in https://github.com/coreos/coreos-overlay/tree/master/profiles/coreos

### Other Information ###

Do we have docs for the SDK, that I can direct future customers too?

**Comment by pgburt** [comment]
Customer solved their own issue:

> Talking with #gentoo, I already figured out that ACCEPT_RESTRICT is set in coreos-overlay/profiles/coreos/base/make.defaults. Removing that line allows me to include binary no-distribute packages in my CoreOS CL image.

**Comment by urzds** [comment]
I came from the the [modifying CoreOS](https://coreos.com/os/docs/latest/sdk-modifying-coreos.html) and [tips and tricks](https://coreos.com/os/docs/latest/sdk-tips-and-tricks.html) docs, importing a binary package from the Gentoo main repository. Trying to emerge it, I ran into `masked by: bindist mirror in RESTRICT`, which I had not encountered before while using Gentoo. It turned out that `ACCEPT_RESTRICT` is set in `coreos-overlay/profiles/coreos/base/make.defaults`. To build my own, private CoreOS CL image containing that package, it was enough to remove `ACCEPT_RESTRICT="* -bindist -mirror"` from `make.defaults` to remove the mask.
