### ISSUE TITLE
"stage1: failed to setup network: failed to create ipvlan: operation not supported" -  after update to 1298.5.0

### ISSUE THREAD

**Issue by f0** [coreos/bugs#1843]
after updating to 1298.5.0 i can no longer run container with ipvlan 
```
/opt/bin/rkt --insecure-options=all run --net=default-restricted,vlan-2880:IP=10.62.0.110 aci.example.net/aci-base:3
stage1: failed to setup network: failed to create ipvlan: operation not supported
```

after rollback to 1235.9.0 , it does work without errors

i use rkt 1.25 with both

**Comment by squeed** [comment]
This is because CoreOS Container Linux is missing the `NET_L3_MASTER_DEV` kconfig (see the [fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=1428530)). This dependency was added in kernel 4.9 in [this commit](https://github.com/torvalds/linux/commit/4fbae7d83c98c30efcf0a2a2ac55fbb75ef5a1a5).

So, we need to set `NET_L3_MASTER_DEV=y` and consider bringing this fix to the other channels.

**Comment by lucab** [comment]
Seems to be coming from the new dependency added in http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=4fbae7d83c98c30efcf0a2a2ac55fbb75ef5a1a5 for 4.8.

**Comment by dm0-** [comment]
This was auto-closed by the PR against master.  I'm also pushing the fix to the beta and stable branches.

**Comment by f0** [comment]
@dm0-  big thx for fixing this, is there a known rollout date for stable?

**Comment by dm0-** [comment]
@f0 Unless there are any critical security fixes before then, we should release a patched stable version on Wednesday of next week (and a new alpha is scheduled for Thursday).

**Comment by f0** [comment]
@dm0-   ok thx
