### ISSUE TITLE
docker flags sugar

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1851]
# Issue Report #

### Environment ###

All

### Desired Feature ###

CT provides sugar for configuring docker flags (e.g. `--insecure-registry`). I don't know to what degree we break out these flags individually, for example:

```yaml
docker:
  flags: --insecure-registry=10.0.0.200
```

vs.

```yaml
docker:
  insecure_registry: 10.0.0.200
```

**Comment by dgonyeo** [comment]
Not breaking them out (your first example) would be easier to write, and doesn't require ct to constantly chase changes to the docker flags, but the second one allows us to sanity check the flags for users.

You talked at one point about having ct be aware of what version of CL it's generating a config for, I'd be ok with the latter approach if we added that, so we could do something like only throw a warning if a new docker version comes out, makes it into CL, ct isn't aware of a version of CL that new yet, and the user is using some unknown flag. Just making sure we don't block users from using a new alpha because we're a day late in releasing a ct update.

**Comment by dgonyeo** [comment]
Just implemented the first approach, I can change the PR if we want the latter syntax (but as mentioned, I think it'll require more extensive changes for ct for me to be happy with it).

https://gist.github.com/dgonyeo/391839ee96aa21112a0bd660cb7e008d

**Comment by dgonyeo** [comment]
Oh, and I'll make the PR if you're happy with it once https://github.com/coreos/container-linux-config-transpiler/pull/18 lands.
