### ISSUE TITLE
AMIs don't have ENA enabled

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1853]
# Issue Report #

### Container Linux Version ###

`CoreOS-stable-1298.5.0-hvm (ami-fd92109d)`

### Environment ###

EC2

### Other Information ###

[User reported](https://github.com/coreos/coreos-overlay/pull/2331#issuecomment-283403128) that we were missing the instance attribute.

**Comment by euank** [comment]
This might not be as trivial as it seems since, iirc, the ancient ec2-utils package we're using doesn't have the flag we need. It didn't the last time I glanced at this.

Changing it to use the aws cli (or getting plume in shape) does fix the problem, but isn't quite so trivial.

Hopefully my memory is wrong and the ec2-utils cli does have the flag.

**Comment by bgilbert** [comment]
Fixed in https://github.com/coreos/mantle/pull/540.

**Comment by joelittlejohn** [comment]
@bgilbert do you know which version of the CoreOS Stable HVM AMI is required in order to have ENA enabled?

**Comment by joelittlejohn** [comment]
Sorry, answered my own question. Looks like it's CoreOS-stable-1353.6.0-hvm (this is the first AMI that has `EnaSupport: true`).
