### ISSUE TITLE
ct isn't suppose to work with a full containeros could-init file ?

### ISSUE THREAD

**Issue by kfirufk** [coreos/bugs#1870]
i have Container Linux by CoreOS alpha (1339.0.0) installed on my pc and as a configured cloud-init file (var/lib/coreos-install/user_data) with coreos configuration, users, ssh keys and other stuff.

when I execute ct I get:

warning at line 2, column 0
Config has unrecognized key: hostname
warning at line 3, column 0
Config has unrecognized key: write_files
warning at line 146, column 0
Config has unrecognized key: ssh_authorized_keys
warning at line 148, column 0
Config has unrecognized key: users
warning at line 155, column 0
Config has unrecognized key: coreos

in the examples I didn't see any specific coreos cloud-config. do I need to break it apart ? how do I resolve this ?

thanks!

**Comment by crawford** [comment]
coreos-cloudinit and ct/Ignition are two different methods for configuring Container Linux (coreos-cloudinit is on its way out). When using Container Linux Configs, you need to process them with ct and then pass the result (an Ignition config) to `coreos-install`. Judging by the output, it looks like you wrote a cloud-config (which can be passed directly to the machine) instead of a Container Linux Config.

**Comment by dgonyeo** [comment]
@kfirufk does that make sense? Were you able to resolve this?

**Comment by kfirufk** [comment]
Thank you. If appears that I was fed with false information regarding your tool and it does not suite my needs which to convert a cloud-init coreos file. I just created the ignition file from scratch.  Thank you for your support

**Comment by richp10** [comment]
This confused me as well - comment for the benefit of others who pass by..

The earlier cloud-config yaml format is similar but not compatible with the yaml that you need to feed into ct to produce the json for ignition.  So you can't just take a cloudconfig file and use ct to convert to ignition json - you need to change the yaml first to match the ignition specification. 

Maybe the documentation could be a little clearer on this point?

**Comment by crawford** [comment]
[The provisioning doc](https://coreos.com/os/docs/latest/provisioning.html) is a good starting point. This is the main entry point from the root of the OS docs. Where else would benefit from adding a note? It's easy enough to do.

**Comment by ChristopherLClark** [comment]
Might as well just frickin' make the ignition file then. This was a waste of my time, getting ct set up, building out a cloud-config. and it doesnt transpile anything!

**Comment by akutz** [comment]
Hi @ChristopherLClark,

> Might as well just frickin' make the ignition file then. This was a waste of my time, getting ct set up, building out a cloud-config. and it doesnt transpile anything!

I completely agree. I fail to see any value in this tool whatsoever. It seems to be advertised as a way to migrate from Cloud-Init to Ignition, but instead it's from some format that was never the previous, de facto standard anyway. Why would *anyone* bother to first migrate to some silly middle-ground format to just then migrate again to Ignition? 

Please someone tell me what I'm missing?

cc @figo

**Comment by crawford** [comment]
> It seems to be communicated as a way to migrate from Cloud-Init to Ignition

I'm curious where you got this impression. I'd like to clear up any ambiguous wording in our docs. CT transpiles from Container Linux Configs. It has nothing to do with Cloud Configs.

> Why would we first migrate to some middle-ground format to just then migrate again to Ignition?

You should migrate to Container Linux Configs (the middle-ground format) and then use CT to generate your Ignition Configs. Why on Earth would you want to do that? Because using CT will guarantee that your config is syntactically valid (which people have been notoriously bad at, even with Cloud Configs) and will perform a number of semantic checks. It also provides a lot of syntactic sugar for common or complex operations. The intent is that the sysadmin writes a Container Linux Config and feed that into CT, which will output a blob (turns out to be an Ignition Config, but that's largely irrelevant), and then gives that blob to AWS/GCP/Azure/etc when creating an instance. If your Container Linux Config is problematic, you won't waste time booting a machine only to find you made a mistake.

**Comment by akutz** [comment]
Hi @crawford,

It was a series of events. A colleague found the tool, and then found it wasn't working. We tracked down the reason, and it appeared to be that the input was not what we thought. Blogs like https://www.solinea.com/blog/migrating-cloud-init-ignition don't help. Buried in the blog is the following:

> Ignition leverages JSON configurations which are not the easiest thing for humans to create. To make things easier an intermediary yaml specification was created to minimize the bracket matching and effort involved in creating a configuration. 

I think the above got misinterpreted to mean that the tool converts Cloud-Config to Ignition config. Now I know why it's called a transpiler (I was wondering). 

Still, I'm somewhat perplexed that we're really at this stage where transpilers are created just to keep people from having to touch JSON? I guess no one remembers SOAP :) JSON was/is supposed to be the easier format to write/read.

Anyway, when you search for how to migrate from Cloud-Init/Cloud-Config to Ignition, you will inevitably find the [Terraform front-end](https://github.com/coreos/terraform-provider-ct) for this tool, and I think it was a simple misunderstanding from there.

**Comment by akutz** [comment]
Hi @crawford,

In other words, I apologize for and rescind my statement about "as advertised." It's more of it's too easy to find this tool when looking for information on migrating from Cloud-Init to Ignition, and when you're already wanting to do that and find a tool that's related to transforming config files, it's easy to fill in the steps with what you want.

**Comment by akutz** [comment]
Hi @crawford,

Could you possibly verify the following assertions about the content at https://gist.github.com/akutz/0ded895c507856d209d30e05b64daa29? From what I can tell, knowing very little about Cloud-Init, CLC, and Ignition, it looks like:

* The keys under `cores` should slide up nicely to the root of a CLC config file based on its [schema](https://coreos.com/os/docs/latest/configuration.html).
* With Ignition >=2.1.0 it should be possible to transform the keys under `write-files` to `storage.files` keys, including the inline content?

To the best of your knowledge, are the above two observations correct?

**Comment by crawford** [comment]
@akutz Yep, that _seems_ correct. The [migration guide](https://coreos.com/os/docs/latest/migrating-to-clcs.html#write_files) should walk you through everything you'll need.

As for the compression, Ignition supports decompressing contents, but CT doesn't support compressing the inline contents. If you open a [bug report](https://issues.coreos.com), I bet someone will implement it.

**Comment by crawford** [comment]
@akutz If you are using VMware, why is it necessary to compress the contents of those files? I didn't think GuestInfo had size restrictions. Also, in case you weren't aware, any process on your system will be able to read that kubeconfig (and all of the other TLS assets) since the hypercall bridge (slow path) is implemented as a few `IN` calls.

As a side note, you can remove `bins.service` and replace that with some file definitions with remote contents.

**Comment by akutz** [comment]
Hi @crawford,

If you're available for a Zoom please let me know, and I can explain the use case. FWIW, I *did* create a patch for CT, but it doesn't matter since Ignition won't support compressed content for local, inline content:

### CT Patch
```diff
index f335667..79c4611 100644
--- a/config/types/files.go
+++ b/config/types/files.go
@@ -63,9 +63,11 @@ type File struct {
 }
 
 type FileContents struct {
-       Remote Remote `yaml:"remote"`
-       Inline string `yaml:"inline"`
-       Local  string `yaml:"local"`
+       Base64      *bool  `yaml:"base64"`
+       Compression string `yaml:"compression"`
+       Remote      Remote `yaml:"remote"`
+       Inline      string `yaml:"inline"`
+       Local       string `yaml:"local"`
 }
 
 type Remote struct {
@@ -158,11 +160,20 @@ func init() {
                        }
 
                        if file.Contents.Inline != "" {
-                               newFile.Contents = ignTypes.FileContents{
-                                       Source: (&url.URL{
-                                               Scheme: "data",
-                                               Opaque: "," + dataurl.EscapeString(file.Contents.Inline),
-                                       }).String(),
+                               if file.Contents.Base64 != nil && *file.Contents.Base64 {
+                                       newFile.Contents = ignTypes.FileContents{
+                                               Source: (&url.URL{
+                                                       Scheme: "data",
+                                                       Opaque: ";base64," + file.Contents.Inline,
+                                               }).String(),
+                                       }
+                               } else {
+                                       newFile.Contents = ignTypes.FileContents{
+                                               Source: (&url.URL{
+                                                       Scheme: "data",
+                                                       Opaque: "," + dataurl.EscapeString(file.Contents.Inline),
+                                               }).String(),
+                                       }
                                }
                        }
 
@@ -237,7 +248,10 @@ func init() {
                                }
                        }
 
-                       newFile.Contents.Compression = file.Contents.Remote.Compression
+                       if file.Contents.Compression == "" {
+                               file.Contents.Compression = file.Contents.Remote.Compression
+                       }
+                       newFile.Contents.Compression = file.Contents.Compression
                        newFile.Contents.Verification = convertVerification(file.Contents.Remote.Verification)
 
                        out.Storage.Files = append(out.Storage.Files, newFile)
```

### Ignition & Compressed Content
Ignition specifically [disallows](https://github.com/coreos/ignition/blob/master/internal/resource/url.go#L252) compressed file contents for anything using the `data` URL [scheme](https://tools.ietf.org/html/rfc2397):

```go
// FetchFromDataURL writes the data stored in the dataurl u into dest, returning
// an error if one is encountered.
func (f *Fetcher) FetchFromDataURL(u url.URL, dest *os.File, opts FetchOptions) error {
	if opts.Compression != "" {
		return ErrCompressionUnsupported
	}
	url, err := dataurl.DecodeString(u.String())
	if err != nil {
		return err
	}

	return f.decompressCopyHashAndVerify(dest, bytes.NewBuffer(url.Data), opts)
}
```

**Comment by crawford** [comment]
> Those files are generated with the artifacts as compressed binaries encoded as base-64, inline content.

That's what I was afraid of. I think your best bet is to send those assets back through `base64` and `gunzip` and then make use of "local contents" in your Container Linux Config. Something like this:

```
$ cat cncf.clc
storage:
  files:
    - path: /etc/systemd/resolved.conf.d/dns.conf
      filesystem: root
      mode: 0644
      user:
        name: root
      contents:
        local: dns.conf

$ cat dns.conf.b64.gz
H4sIAAAAAAAC/4oOSi3OzylLjeVy8Qu2NTQx1zM31TOz1DMyBgtY6IGhAiAAAP//mLfncScAAAA=

$ base64 --decode < dns.conf.b64.gz | gzip --decompress > dns.conf

$ ./ct-v0.9.0-x86_64-unknown-linux-gnu --strict --pretty --files-dir . < cncf.clc
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.2.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/systemd/resolved.conf.d/dns.conf",
        "user": {
          "name": "root"
        },
        "contents": {
          "source": "data:,%5BResolve%5D%0ADNS%3D147.75.69.23%0ADNS%3D8.8.8.8%20",
          "verification": {}
        },
        "mode": 420
      }
    ]
  },
  "systemd": {}
}
```

It's not ideal, but it should work. I asked one of the Ignition developers why we disallow compression in dataurls and there didn't seem to be any real reason. We could allow that in the future, but that doesn't really help you now.

**Comment by dgonyeo** [comment]
Ignition developer here. I can add in support for compression with dataurls, I think the only reason it's not supported is because no one has asked for it before. Once it gets merged in we can start sending it through the alpha/beta/stable flow for CL.

**Comment by akutz** [comment]
Hi @crawford,

Yeah, I saw the `file.contents.local` field and how it relates to `--files-dir`. It does seem like maybe that's the best bet for handling the files today. As you said, I could patch Ignition myself, but at that point we'd require a custom CoreOS image/OVF, and if we do that then we're just going to use Cloud-Init on boot in the image since we already have the Cloud-Init config files in place and are able to pass them through GuestInfo.

**Comment by akutz** [comment]
Hi @dgonyeo,

Would you like me to open a PR for the CT patch I supplied above? I'm not sure it's comprehensive or even works (since Ignition disallows this state at the moment). Go's `URL` type also doesn't have any true support for the data scheme. For example, I had to place the `;base64,` in the opaque part of the URL when it should really be some attribute of the scheme or some other field not present in Go's URL.

**Comment by akutz** [comment]
Hi @dgonyeo,

Thank you as well for responding so quickly.

**Comment by dgonyeo** [comment]
@akutz go ahead and make that PR. We can test it / make sure it works once I get a corresponding Ignition PR up.

**Comment by akutz** [comment]
Hi @crawford,

FYI, I got cloud-init [working](https://github.com/akutz/cross-cloud/commit/52b8908786aa7bf8f4ff1858d5294b026ed4ccf6) on CoreOS on vSphere by bootstrapping the former with Ignition.

I just thought this may be useful for others or maybe to put in your back pocket when you encounter similar situations where moving to Ignition isn't immediately viable.

**Comment by alpana17** [comment]
How Can I change file permissions using Container Linux Configs in CoreOS
