### ISSUE TITLE
cloud-config: deprecate etcd2 and etcd and create new docs

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1877]
In a [blog post a few weeks ago](https://coreos.com/blog/toward-etcd-v3-in-container-linux.html) we announced deprecation of etcd2 and etcd in Container Linux. But, our docs haven't been updated. We need to do the following things:

- [x] Deprecate etcd2 in the [cloud-config docs](https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/cloud-config.md)
- [ ] ~~Show people how to use etcd-member in the [cloud-config docs](https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/cloud-config.md)~~

Issue filed based on feedback from Twitter: https://twitter.com/spidler/status/844350222524448773

**Comment by philips** [comment]
cc @coreos/team-docs we should do this ASAP.

**Comment by crawford** [comment]
Instead of coreos-cloudinit, we are going to show how this can be done via Container Linux Configs instead (https://github.com/coreos/container-linux-config-transpiler/pull/37).

**Comment by radhikapc** [comment]
I do not have permission to assign this defect to myself. @crawford please assign to me if you are at work.

**Comment by radhikapc** [comment]
as discussed, will wait for the etcd team to complete the new version of docs that they are working on. Then we would be able to provide proper links to the docs, along with stating etcd2 is depreciated.

**Comment by crawford** [comment]
The etcd team has finished most of the documentation (if not all of it). We are really just waiting on the ct documentation @dgonyeo is working on. It should be ready by the end of the week.

**Comment by radhikapc** [comment]
@dgonyeo ping us once you merge the changes!

**Comment by philips** [comment]
@crawford We need both cloud-config and ignition, because:

1. Cloud-config is referenced everywhere in our docs and Google
1. Some people already have cloud-config in their workflow
1. Some can't migrate because of lack or platform support

**Comment by dgonyeo** [comment]
> ping us once you merge the changes

@radhikapc the ct docs were merged: https://github.com/coreos/container-linux-config-transpiler/pull/37

I'm now working on changing all the docs in coreos/docs to use container linux configs: https://github.com/coreos/docs/pull/1024

This change results in the docs for all the platforms I can update (as in, have ignition support) being switched over to etcd v3. It's not in the cloud-config docs like this issue wanted, but mentioning it here because it's very related.

**Comment by radhikapc** [comment]
Thanx @dgonyeo. will look into this shortly.

**Comment by alisonbuss** [comment]
Hello everyone,  \o/

I am interested in new documentation of etcd3 and the use of CT that is not very clear at the moment.

I want to do a tutorial on using ignition 2.0, etcd3, TLS / SSL and firewall rules and provisioning with ansible + shell script on a solid CoreOS.

In this link _https://github.com/coreos/bugs/issues/1882_ I approach some questions to start the tutorial with the use of etcd3 principally.

I am eager for more explanatory documentation and examples.

**Comment by euank** [comment]
From my glance through the etcd docs, the following work for etcd3 on container linux:

- [x] https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html

The following have CL specific bits that reference an old etcd (and a new one as well often):

- [ ] https://coreos.com/etcd/docs/latest/etcd-live-http-to-https-migration.html (`/etc/systemd/system/etcd2.service.d/...`, `systemctl status etcd2`, etc right now)
- [ ] https://coreos.com/etcd/docs/latest/etcd-live-cluster-reconfiguration.html (mixed refs to etcd2 and etcd-member)
- [ ] https://coreos.com/etcd/docs/latest/tls-etcd-clients.html (refs to etcd2 service)

(nit: https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_0.html assumes `/var/lib/etcd` even though it's `etcd2` on container linux, maybe that hsould be mentioned)

The following do not use etcd3:

- [ ] https://coreos.com/etcd/docs/latest/op-guide/clustering.html
- [ ] https://coreos.com/etcd/docs/latest/tuning.html
- [ ] https://coreos.com/etcd/docs/latest/op-guide/runtime-configuration.html

The second section there are more egregious.

@dgonyeo feel free to clarify or update the above list, I might be misunderstanding something.

cc @gyuho since I think some of number-2 are related to your change in https://github.com/coreos/docs/pull/1016

**Comment by radhikapc** [comment]
As per the discussion with @heyitsanthony we need new set of docs specific to Container Linux for the following:

 https://coreos.com/etcd/docs/latest/op-guide/clustering.html
 https://coreos.com/etcd/docs/latest/tuning.html
 https://coreos.com/etcd/docs/latest/op-guide/runtime-configuration.html

**Comment by radhikapc** [comment]
@euank all the issues you have mentioned have been fixed and doc is merged, please go ahead and close this defect unless we have other set of docs to be fixed other than what we have mentioned here.

**Comment by radhikapc** [comment]
related https://github.com/coreos/bugs/issues/1128
