### ISSUE TITLE
Support encrypted EBS volumes for etcd data directory

### ISSUE THREAD

**Issue by cricci82** [coreos/bugs#1878]
## Feature Request ##
Ability to store their etcd data directory on an encrypted EBS volume.  

### Environment ###
AWS

### Desired Feature ###
During installation have the option to select an encrypted EBS volume as a storage type

**Comment by euank** [comment]
@cricci82 mind clarifying exactly what you want here?

If you're using the etcd-operator, I believe that it just relies on a user-defined storage-class which can specify "encrypted: true".

If you're talking about the tectonic installer, then I think that's a valid feature request and I don't think it currently has that option.

If you're talking about regular Container Linux installation, I believe the right process would just be to add another EBS volume with encryption and add drop-ins for etcd-member which depend on that mount.
If this is the case, I don't think there's any work needed from us (since EBS encryption would be entirely up to the aws deployment tool in question and it should just work).

**Comment by euank** [comment]
Please reopen if you have more information about which installation process you mean / what change you're referring to wanting.
