### ISSUE TITLE
iptables kernel panic

### ISSUE THREAD

**Issue by comcast-david** [coreos/bugs#1881]
# Issue Report #

Bug

## Bug ##

When iptables-restore is used to perform replacements of very large tables, `ipt_alloc_initial_table` hangs, and when it does, the linux kernel panics.

The following screenshot was captured from the console of a virtual machine, but the issue also occurs on bare-metal machines.

![image](https://cloud.githubusercontent.com/assets/19591184/24277402/71faa9f8-1002-11e7-8f6e-50e837a53bb0.png)

### Container Linux Version ###

```
cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1185.5.0
VERSION_ID=1185.5.0
BUILD_ID=2016-12-07-0937
PRETTY_NAME="CoreOS 1185.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"


cat /proc/version
Linux version 4.7.3-coreos-r3 (jenkins@jenkins-os-executor-1.c.coreos-gce-testing.internal) (gcc version 4.9.3 (Gentoo Hardened 4.9.3 p1.5, pie-0.6.4) ) #1 SMP Wed Dec 7 09:29:55 UTC 2016
```

### Environment ###

replicated on:

bare metal machines.
also on virtual machines. 
occurs when iptables directly on the host machine. 
also occurs when iptables is executed from within a docker container.

### Expected Behavior ###

a kernel panic does not occur

### Actual Behavior ###

linux kernel panics

### Reproduction Steps ###

1. generate an iptables ruleset with lots and lots of rules. 
2. run `iptables-restore -T nat --noflush --counters saved.log`
3. the kernel will panic

or here's a shell script:

```
# with sudo:

~ # for i in {1..100000}; do iptables-save -t nat > heh.txt; lines=$(cat heh.txt | wc -l); echo -n "#$i - saved $lines rules... "; iptables-restore -T nat --noflush --counters heh.txt ; date +%s; done
#1 - saved 259 rules... 1490325227
#2 - saved 262 rules... 1490325227
#3 - saved 268 rules... 1490325227
#4 - saved 280 rules... 1490325227
#5 - saved 304 rules... 1490325227
#6 - saved 352 rules... 1490325227
#7 - saved 448 rules... 1490325227
#8 - saved 640 rules... 1490325227
#9 - saved 1024 rules... 1490325227
#10 - saved 1792 rules... 1490325227
#11 - saved 3328 rules... 1490325228        <------------- NOTE: it starts to get sluggish here
#12 - saved 6400 rules... 1490325230
#13 - saved 12544 rules... 1490325237
#14 - saved 24832 rules...                           <------------- Can't exceed 32768?

```

**Comment by euank** [comment]
As I understand it, it's basically a known limit of iptables that it doesn't scale well. Even if it didn't bork the kernel, the performance wouldn't be great.

I don't believe that this is specific to our kernel or that this works better on any other linux distro, but do correct me if I'm wrong.

Would it be possible to use ipvs instead, or otherwise avoid creating such a massive number of rules?

**Comment by euank** [comment]
Can you clarify whether you've seen better behaviour on other kernels, or have other reasons to think this is something specific to our distro?

And again, from above, would it be possible to use ipvs or not create so many rules?

Since I think this is an upstream kernel issue / limitation of iptables, I don't think there's anything actionable on our end, but if you have more information I'd be happy to be wrong.

**Comment by comcast-david** [comment]
The issue arose on our part because of a defect in some software I was writing that multiplied iptables rules at a geometric rate. We're not really looking to store 32k+ iptables rules in a single chain. 

The kernel panic itself is most likely an upstream issue, though I have not tested it on other distros.   Where do you report those?

**Comment by bgilbert** [comment]
There's a netfilter component in the [kernel.org bugzilla](https://bugzilla.kernel.org/); you can try there.

Since this doesn't seem specific to Container Linux and doesn't seem likely to occur under normal circumstances, I'll close.
