### ISSUE TITLE
Update.conf Problem with the Date/time

### ISSUE THREAD

**Issue by helletheone** [coreos/bugs#1902]
# Issue Report #
After login: 

Failed Units: 1
  motdgen.service

BUG:  /etc/coreos/update.conf: line 3: 23:00: command not found

## Bug ##

sudo /usr/lib/coreos/motdgen
/etc/coreos/update.conf: line 3: 23:00: command not found

### Container Linux Version ###

$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.6.0
VERSION_ID=1298.6.0
BUILD_ID=2017-03-14-2119
PRETTY_NAME="Container Linux by CoreOS 1298.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###
CoreOs

### Reproduction Steps ###

edit etc/coreos/update.conf

GROUP=stable
REBOOT_STRATEGY=etcd-lock
LOCKSMITHD_REBOOT_WINDOW_START=Wed 23:00
LOCKSMITHD_REBOOT_WINDOW_LENGTH=1h30m

### Environment ###

Root-Server

**Comment by dgonyeo** [comment]
This is because `motdgen` sources `/etc/coreos/update.conf`. The space in the window start line makes bash think that line is the command `23:00` with the environment variable `LOCKSMITHD_REBOOT_WINDOW_START` set to `Wed`. An easy solution is to put `Wed 23:00` in quotes. I'll update our docs to do that.

**Comment by helletheone** [comment]
thx you :) that help us
