### ISSUE TITLE
Upgrade rbd client in quay.io/coreos/hyperkube image

### ISSUE THREAD

**Issue by neith00** [coreos/bugs#1924]
### Environment ###
official coreOS hyperkube image  
### Desired Feature ###

Current version of rbd client embedded in the image is:
$ root@dd1f6792540c:/# rbd --version
ceph version 0.80.7 (6c0127fcb58008793d3c8b62d925bc91963672a3)

It would be great to update the client to support ceph servers in jewel version.
It provides image-type 2 compatibility, note that image-type 1 are already flagged deprecated.
Type 2 ceph image format provides multiple features like snapshots or cloning.

Also it supports **straw2** for server side ceph disk format. which is more optimal than the previous straw mode especially in large ceph cluster.

**Comment by neith00** [comment]
I made some testings. Seems like all features are still functionnal after upgrading the rbd Ceph client.
Anyone from coreOS to validate this update?
I've done this for my hyperkube image to confirm:
`FROM  quay.io/coreos/hyperkube:v1.5.2_coreos.0
RUN   apt-get update \
      && DEBIAN_FRONTEND=noninteractive apt-get install apt-utils wget apt-transport-https -y \
      && wget -q -O- 'https://download.ceph.com/keys/release.asc' | apt-key add - \
      && echo 'deb https://download.ceph.com/debian-jewel/ jessie main' > /etc/apt/sources.list.d/ceph.list \
      && apt-get update \
      && DEBIAN_FRONTEND=noninteractive apt-get install --only-upgrade ceph-common -y \
      && DEBIAN_FRONTEND=noninteractive apt-get autoremove -y \
      && DEBIAN_FRONTEND=noninteractive apt-get clean \
      && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
CMD ["/bin/bash"]
`

**Comment by pgburt** [comment]
Hi @neith00 ! I chatted with some folks and they said we're pretty strictly tied to the upstream HyperKube, since deviating would place an enormous testing / stability burden on us.

The quick way to get this in is to highlight it to the folks working on the [upstream Hyperkube](https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube). If they make the change, we'll naturally pull it down.

You made a well written request. Let's get it in front of the [right set of eyes](https://github.com/kubernetes/kubernetes/issues/new).

**Comment by neith00** [comment]
I opened it to the upstream Hyperkube team.
Thanks
