### ISSUE TITLE
AWS DHCP Options set domain-name separated by "032" rather than a space"

### ISSUE THREAD

**Issue by tylux** [coreos/bugs#1934]
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.6.0
VERSION_ID=1298.6.0
BUILD_ID=2017-03-14-2119
PRETTY_NAME="Container Linux by CoreOS 1298.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###
AWS EC2 Instance inside a VPC

### Expected Behavior ###
Adding multiple domains in VPC DHCP options should result in a space separated string of search domains under /etc/resolv.conf
Example: search foo.com bar.com candy.com

### Actual Behavior ###
Rather than a space in between the search domains, a "032" is added without any spaces

Example: search foo.com032bar.com032candy.com

### Reproduction Steps ###

  1. Add multiple domain-name options under VPC > DHCP Option sets
  2. Attach that new option set to the VPC
  2. Wait for /etc/resolv.conf to update

### Other Information ###
Current "fix" is to created a file under /etc/systemd/resolved.conf.d/*.conf with the following

```
[resolve]
Domains=search foo.com bar.com candy.com
```
systemctl restart systemd-resolved

Note: This bug does not affect Ubuntu 16.04 machines in the same VPC. 

Also, looks like "32" is the ASCII equivalent of "space" http://www.ascii-code.com/ so maybe an issue translating that.

**Comment by euank** [comment]
I can reproduce tihs on `VERSION=1353.6.0` as well, so systemd v233 doesn't fix this either.

It's likely a networkd bug

**Comment by m4x1202** [comment]
I can reproduce this on version:
```bash
/etc/systemd $ cat /etc/*-release
DISTRIB_ID="Container Linux by CoreOS"
DISTRIB_RELEASE=1409.5.0
DISTRIB_CODENAME="Ladybug"
DISTRIB_DESCRIPTION="Container Linux by CoreOS 1409.5.0 (Ladybug)"
```
aswell

**Comment by wallentx** [comment]
From http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html#AmazonDNS
>**Important**
>Some Linux operating systems accept multiple domain names separated by spaces. However, other Linux operating systems and Windows treat the value as a single domain, which results in unexpected behavior. If your DHCP options set is associated with a VPC that has instances with multiple operating systems, specify only one domain name.

Does CoreOS actually support multiple search domains?

**Comment by twilfong** [comment]
Doing a bit of research on this, it looks like a simple patch to /lib/dhcpcd/dhcpcd-hooks/20-resolv.conf could fix this. Of course, on the latest stable AWS CoreOs image, /lib is a symlink to /usr/lib64 and /usr is a read-only filesystem.

**Comment by euank** [comment]
@twilfong Having a read-only `/usr` partition is part of what allows us to update machines automatically.

For changes that make for saner defaults for the distro, we'd happily take PRs to update those files, which would then be part of a future update.
In addition, `dhcpcd`'s configuration can also be configured via files in etc (such as adding a systemd dropin to point to a different hook directory).

.. That being said, I think it's a moot point since our dhcp client is `systemd-networkd`, not dhcpcd.

---------

@wallentx Yes, multiple search domains are supported / should work if they're manually configured.

**Comment by twilfong** [comment]
Understood, on why /usr is read-only. I hadn't thought about editing dhcpcd.conf to point to a script in a writeable area. Thanks for the tip. But, as you've said, this won't help because CoreOS is not using dhcpcd. I had just assumed that it was, since this is installed in the AMI, and I've seen other systemd-based distros use dhcpcd.

**Comment by coresolve** [comment]
This is hitting a prospective customer. @euank @crawford

**Comment by lucab** [comment]
I did some initial investigation into this and it looks like the problem is the AWS DHCP implementation being out of spec, thus the DNS-related value in the Offer being wrong. This is how an AWS DHCP offer [capture](https://github.com/coreos/bugs/files/1495675/aws-dhcp-offer.pcap.gz) looks like when multiple domains are specified in [domain-name AWS-DHCP-Options](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html):
```
10:30:45.120540 IP (tos 0x10, ttl 16, id 0, offset 0, flags [none], proto UDP (17), length 362)
    10.0.32.1.bootps > 10.0.35.248.bootpc: [udp sum ok] BOOTP/DHCP, Reply, length 334, xid 0xa493830e, secs 1, Flags [none] (0x0000)
          Your-IP 10.0.35.248
          Client-Ethernet-Address yy:yy:yy:xx:xx:xx (oui Unknown)
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Offer
            Server-ID Option 54, length 4: 10.0.32.1
            Lease-Time Option 51, length 4: 3600
            Subnet-Mask Option 1, length 4: 255.255.240.0
            Default-Gateway Option 3, length 4: 10.0.32.1
            Hostname Option 12, length 14: "ip-10-0-35-248"
            Domain-Name Option 15, length 38: "eu-west-1.compute.internal example.com"
            Domain-Name-Server Option 6, length 4: 8.8.8.8
            MTU Option 26, length 2: 9001
            END Option 255, length 0
```

There are two problems in there:
 1. [DHCP Option 15](https://tools.ietf.org/html/rfc2132#section-3.17) is being returned here. RFC2132 specifies that this is a single string for a domain name, and networkd correctly decodes it as such. If the intent is to specify a list of multiple search domain instead, AWS DHCP server must return it as a [DHCP Option 119](https://tools.ietf.org/search/rfc3397#section-2).
 2. whitespaces are [not allowed](https://tools.ietf.org/html/rfc952) in domain names, thus the value of Option 15 technically contains an invalid character.

**Comment by squeed** [comment]
Its not exactly AWS being the problem. It's rather a case of garbage-in garbage-out, and AWS not supporting DHCP option 119, search path.

**Comment by nstielau** [comment]
Cross-linking back to mailing list issue: https://groups.google.com/forum/#!topic/coreos-user/wl6QVwaMVVI

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.

**Comment by ggrandes** [comment]
Workaround can be found here:
https://bugs.launchpad.net/cloud-images/+bug/1791578/comments/5
