### ISSUE TITLE
Etcd3 Recovery Documentation

### ISSUE THREAD

**Issue by matthewceroni** [coreos/bugs#1980]
# Issue Report #

https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md

Following documentation outlines how to backup and restore an ETCDv3 cluster.

The issue is the etcdctl command does not understand option snapshot. 

I figured this might be due to the version of CoreOS I am running, upgraded but same issue. Therefore I built the latest version of etcdctl but it itself does not have the snapshot option.

What is the procedure for backing up and restoring an ETCDv3 cluster? 

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.5.0
VERSION_ID=1298.5.0
BUILD_ID=2017-02-28-0013
PRETTY_NAME="Container Linux by CoreOS 1298.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Amazon Web Services

**Comment by monder** [comment]
Could you please check your `etcdctl` version.
All current Container Linux versions ship with
```
$ etcdctl --version
etcdctl version 2.3.7
```
Whereas v3 API (and ETCDCTL_API flag) is only available in `etcdctl` v3+.
You can download static binary of `etcdctl` 3.x to match your cluster version [here](https://github.com/coreos/etcd/releases) and it will have the `snapshot` flag.

I do agree that we should document somewhere that coreos has the version 2 of etcd by default or somehow ship the new version of `etcdctl` along with etcd2 since the new one supports both api versions.

**Comment by matthewceroni** [comment]
This was a mistake on my part. 

I believe I set ETCDCTL_API flag when testing version 2.3.7 that is available on CoreOS but not when I compiled the latest etcdctl. Once I set API = 3 I was able to access the snapshot feature.
