### ISSUE TITLE
kubelet-wrapper and arbitrary rootfs access

### ISSUE THREAD

**Issue by euank** [coreos/bugs#1993]
Currently, we ship the kubelet in a rkt fly chroot. This has served us fairly well so far, but has required us to identify any new paths on the host the kubelet requires persistence for and bindmount them over.
For example, https://github.com/coreos/coreos-kubernetes/issues/322, https://github.com/coreos/coreos-overlay/pull/2566, etc.

Keeping up with these paths is one of the primary problems with kubelet-wrapper.

However, starting in either 1.7 or 1.8 (depending how quickly the feature is implemented), an additional feature will be introduced to kubernetes that will require more complex handling. The [hostpath type feature](https://github.com/kubernetes/kubernetes/pull/46597), which *might* maybe be part of 1.7, but also might end up not being there until 1.8

This is a much larger problem since the kubelet-wrapper, as used today, will be unable to cope with this new feature.

## Impact

Once this feature is merged, a kubelet launched with kubelet-wrapper will be unable to mount the majority of mounts that make use of the hostPath type feature.

Any pods not using that feature will not be impacted.

## Possible Solutions

To keep us on the same page, here's the problem statement:

"We wish to run the kubelet on Container Linux, but not have to ship all its dependencies on the host filesystem. These dependencies include socat and various mount binaries such as the ceph mount tool.

We also want the kubelet, via some mechanism, to be able to validate the existence of arbitrary paths on the host"

#### Upsides

1. Used in some other distributions afaik (see https://github.com/kubernetes/kubernetes/issues/43708#issuecomment-289519511)
1. Some initial support for it in the hostpath type PR
1. Migration might be as easy as adding the flag in kubelet-wrapper

#### Downsides

1. Breaks mount binaries shipped in the hyperkube image; they must either be added to the distro or otherwise provided
1. Absolute symlinks for the hostpath type will be wrong, possibly other gotchas
1. Not all that widely used

#### Upsides

1. Possibly the most simple change
1. Doesn't require shipping mount.* on CL directly

#### Downsides

1. Fork
1. Absolute symlinks for the hostpath type will be wrong, possibly other gotchas

### Run on the host, use containerized-mounter

I refer to what [gci](https://github.com/kubernetes/kubernetes/blob/8f4aacf6d50cec456be9c723c5e317dbfe366181/cluster/gce/gci/configure-helper.sh#L1082-L1092) runs.

This involves running the kubelet on the host and passing in the `--experimental-mounter-path` flag to the kubelet.

#### Upsides

1. Some level of upstream support maybe via gci

#### Downsides

1. Hardcodes some [filesystem types](https://github.com/kubernetes/kubernetes/blob/8f4aacf6d50cec456be9c723c5e317dbfe366181/pkg/util/mount/mount_linux.go#L78); this is the list GCI needs it for and our list is probably the same, but I'm not sure
1. Experimental feature
1. Running the kubelet on the host is an interesting migration; kubelet-wrapper could maybe do that instead?
1. Doesn't solve the other things `--containerized` does (socat), likely would have to add socat to CL image
1. Shipping the containerized mounters would honestly better be done with torcx :S

### Torcx

Longer term, we expect the kubelet to end up in torcx rather than in kubelet wrapper. The full scope of this is not clear.

#### Upside

1. Technically can be quite clean
1. Side benefit of making it easy to provide a `kubectl` in the user's path

#### Downsides

1. Requires building of the torcx package, likely via an ebuild maintained by someone
1. Requires closely tracking new dependencies of upstream rather than being able to base on updates to the hyperkube image
1. Torcx is still experimental, this approach won't be quick nor viable any time soon.

## Preferred solution

This is a tough call. Out of the ones above, torcx is obviously the preferred one. However, switching to containerized-mounters with the intent of moving to torcx in the future is somewhat attractive.

Out of the options we've got above, that's the best I have.

cc @sym3tri @aaronlevy

**Comment by squeed** [comment]
When we initially designed Torcx, we were hoping to avoid supporting the entire hyperkube, mostly because of the large surface area. For example, the hyperkube image depends on python.

However, hyperkube definitely includes far more than is truly necessary - a consequence of the single-stage docker build model. So what do you think would actually need to be packaged? Would torcx need to support redirecting PYTHONPATH somehow as well?

**Comment by squeed** [comment]
@lucab hiiiiiii

**Comment by squeed** [comment]
Just to add fuel to the fire, there are more subtle bugs with `--containerized` as well. For example, it breaks iptables locking, which uses a file in `/run` for modern versions of iptables.

**Comment by aaronlevy** [comment]
Not immediately sure what requires python in hyperkube (some tools we don't use like addon management are python+bash scripts). But this brings to mind all the mount tools that get shipped as part of the hyperkube container -- that might end up being problematic for the torcx approach (do we ship torcx packages for all of these too?)

**Comment by philips** [comment]
We must figure this out in the 1.8 timeframe, looks like the PR is being restarted: https://github.com/kubernetes/kubernetes/pull/46597

**Comment by lucab** [comment]
So we had a bit of discussion today, and I'm capturing here the concerns I expressed on the "kubelet via torcx" model:
 * kubelet shells out to other utils and supports arbitrary plugins; those needs to be shipped in torcx addon images or in the OS base image
 * torcx addons have the lifetime of a machine boot cycle: updating kubelet would require rebooting the machine
 * if there is any dynamic binary (i.e. depending on host libs) in the kubelet+deps chain, we end up with a large matrix of images to build/ship and choose from (one each per k8s-revision * CL-revision)
 * this setup (image building + running) is specific to CL, if it breaks we are on our own in fixing and merging upstream
 * overall, the result looks fragile due to all the un-contained bits and their versioned-dependency chains

My non-technical concern is that we are exploring yet another workaround (systemd-nspawn, rkt, rkt-fly, plain systemd-services, torcx) and we are realizing that each one has different tradeoffs.
I'd prefer if we could spend some time tackling this upstream in the kubelet design, to make it aware that it may not be sharing the rootfs with its CRI runtime and it should account for that (moving across chroot/mount-ns or just demanding some operations to other containers).

This would be the "fork" option from @euank's list, except doing it upstream via stepping stones.

**Comment by philips** [comment]
@lucab the problem is that few teams are thinking about how to make the kubelet upgradeable and self contained. The closest contact I have had is with the Google Container Image team that similarly has had issues with having an OS that "bakes in" the kubelet image. Let me try emailing Vish from Google to see if there is any collaboration point there again.

**Comment by philips** [comment]
What I am saying is that doing it inside of Kubernetes requires us to do the work of trying to get this to work and then convincing others it is a good idea afterwards.

**Comment by philips** [comment]
cc @sym3tri

**Comment by euank** [comment]
Container Linux / kubelet-wrapper is deprecated. Closing this issue as stale.
