### ISSUE TITLE
CoreOS crash on AWS with (many versions)

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#204]
_From @i0n on October 30, 2014 11:23_

Hey there chaps. Experiencing some very strange behaviour using CoreOS 444.5.0 stable on ec2. Cluster boots fine and I am able to schedule services with fleet (which come up and start working), but then after a random length of time machines in the cluster will crash forcing me to restart the VM in question to recover. Only clue in the logs is: 

“ERROR reconcile.go:58: Unable to determine agent's desired state: timeout reached” 

Has anyone else run into this? I have raised this as a fleet issue as the log hints at that, but I guess it could be etcd?

_Copied from original issue: coreos/fleet#1017_

**Comment by rafaeldff** [comment]
Some of our coreos instances started losing all network connectivity some time after boot after the upgrade from 444.5.0 to 522.4.0 We haven't been able to get logs after the connection is dropped, but after if we set ` ethtool -K eth0 sg off`, they never lose connectivity. So either the issue was not really fixed on 522, or we are suffering from a similar related problem.

**Comment by croemmich** [comment]
Having random network drops as well on Linode. Trying @nrandell's solution. Will report back.
