### ISSUE TITLE
OS fails to boot when Ignition adds partitions to the main disk

### ISSUE THREAD

**Issue by shibe2** [coreos/bugs#2106]
### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1492.4.0
VERSION_ID=1492.4.0
BUILD_ID=2017-08-11-2332
PRETTY_NAME="Container Linux by CoreOS 1492.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

QEMU/KVM
Linux 4.12.6 x86_64
QEMU 2.9.0

### Expected Behavior ###

First boot completes normally.

### Actual Behavior ###

System offers emergency shell.

### Reproduction Steps ###

  1. Extract coreos_production_image.bin.bz2 to a raw disk image.
  2. Add Ignition config to OEM partition.
```
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {
    "disks": [
      {
        "device": "/dev/vda",
        "partitions": [
          {
            "label": "SWAP",
            "number": 10,
            "size": 8388608,
            "start": 0,
            "typeGuid": "0657FD6D-A4AB-43C4-84E5-0933C84B4F4F"
          },
          {
            "label": "CEPH",
            "number": 11,
            "size": 0,
            "start": 0,
            "typeGuid": "4FBD7E29-9D25-41B8-AFD0-062C0CEFF05D"
          }
        ]
      }
    ],
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/hostname",
        "contents": {
          "source": "data:,coreos",
          "verification": {}
        },
        "mode": 420,
        "user": {},
        "group": {}
      }
    ]
  },
  "systemd": {},
  "networkd": {},
  "passwd": {}
}
```
  3. Start QEMU.

### Other Information ###

[rdsosreport.txt](https://gist.github.com/shibe2/856537e01c3f9ea6269637753e6815f0)

There seems to be a race in the initrd. Some time is needed to re-populate /dev after ignition-disks. systemd-fsck-root and verity-setup may start too early. Relevant entries from the journal:
```
[    4.860373] localhost sh[383]: No such file or directory
[    4.931492] localhost systemd-fsck[386]: Failed to stat /dev/disk/by-label/ROOT: No such file or directory
```

**Comment by arithx** [comment]
I've repro'd this on my system.

**Comment by bgilbert** [comment]
Thanks for reporting.  There are multiple problems here.

Ignition only waits for devices to settle before it modifies them, not after.  Typically an Ignition config will create both a partition and a filesystem on it, so this isn't usually an issue, but your config only creates the partitions.  Ignition therefore exits successfully before udev has settled, and subsequent systemd units have their device nodes deleted out from under them (since udev deletes and recreates the devices for each partition).  I'd say this should be fixed in Ignition rather than in `ignition-disks.service`, because Ignition knows what device nodes it should wait on and when, while the unit could only do a `udevadm settle`.

Switching your Ignition config to the 2.1.0 spec (for `swap` support) and adding a `filesystems` stanza should work:

```json
{
  "ignition": {
    "version": "2.1.0"
  },
  "storage": {
    "disks": [
      {
        "device": "/dev/vda",
        "partitions": [
          {
            "label": "SWAP",
            "number": 10,
            "size": 8388608,
            "start": 0,
            "typeGuid": "0657FD6D-A4AB-43C4-84E5-0933C84B4F4F"
          },
          {
            "label": "CEPH",
            "number": 11,
            "size": 0,
            "start": 0,
            "typeGuid": "4FBD7E29-9D25-41B8-AFD0-062C0CEFF05D"
          }
        ]
      }
    ],
    "filesystems": [
      {
        "mount": {
          "device": "/dev/disk/by-partlabel/SWAP",
          "format": "swap"
        }
      }
    ],
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/hostname",
        "contents": {
          "source": "data:,coreos",
          "verification": {}
        },
        "mode": 420,
        "user": {},
        "group": {}
      }
    ]
  }
}
```

...but it doesn't.  That's the second problem:

![Screenshot](https://user-images.githubusercontent.com/361374/29445986-a7a6cf54-839e-11e7-9e79-c2811a98efb4.png)

It appears from inode timestamps that udev deletes and recreates the entire `/dev/disk/by-partlabel` directory when the partitions are re-enumerated, but for some reason this is apparently happening *after* Ignition successfully starts `dev-disk-by\x2dpartlabel-SWAP.device`.

cc @dgonyeo

**Comment by shibe2** [comment]
Thanks for the hint. I added swap format /dev/vda10, and it works around the issue. I had to hack ct to produce that configuration.

**Comment by ajeddeloh** [comment]
This should be fixed with https://github.com/coreos/ignition/pull/446 which will be included in the next Ignition release

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/coreos-overlay/pull/2789
