### ISSUE TITLE
default sshd config permits password authentication

### ISSUE THREAD

**Issue by rmmh** [coreos/bugs#2114]
# Issue Report #
When SSHing into a CoreOS cluster without an authorized SSH key, a password prompt appears.

1) No accounts have passwords, so this can confuse users, who might search for account credentials instead of correcting the authorized keys.
2) Some security scanners will flag servers that allow password authentication. (Kubernetes is experiencing this).

### Container Linux Version ###
1465.6.0

### Expected Behavior ###
    Authentications that can continue: publickey

### Actual Behavior ###
    Authentications that can continue: publickey,password,keyboard-interactive

### Reproduction Steps ###
    ssh -v -p 2222 localhost |& grep Authentications

### Other Information ###
This can be fixed by adding `AuthenticationMethods publickey` to /etc/ssh/sshd_config.

**Comment by euank** [comment]
It generally is a good idea to configure sshd as you say. We have documentation on how to do that [here](https://coreos.com/os/docs/latest/customizing-sshd.html#customizing-sshd-with-a-container-linux-config).

Unfortunately, changing the default is a trickier task due to backwards compatibility reasons.
If we just naively update the `/usr` sshd_config, that would lock out users that were relying on password authentication.

Is the above documented configuration enough to solve the problem you're facing?

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
