### ISSUE TITLE
Container Linux boot stuck for 7-8 min on UpBoard

### ISSUE THREAD

**Issue by salkin** [coreos/bugs#2139]
# Issue Report #

Container Linux boot stuck prior to GRUB boot for 7-8 minutes.

### Container Linux Version ###
stable (1465.6.0) 

### Environment ###
UpBoard
http://www.up-board.org/up/specifications/

### Expected Behavior ###
All post install boots should go directly into Grub menu list.

### Actual Behavior ###
All boots except first boot after install is hanging for 7-8 minutes at Grub parameter list. After the 7-8 minutes there is error: "No such device: 00000000-0000-0000-0000....", so probably something not reflected by Ignition after first install to grub? 

### Reproduction Steps ###

  1. Install UpBoard through Matchbox with iPxE with diskinstall to /dev/mmcblk0
  2. Wait for install to complete.
  3. After first boot to disk. Reboot the board.
  4. Boot gets stuck for 7-8 min at pre-Grub menu lst.

### Environment ###
http://www.up-board.org/up/specifications/

**Comment by bgilbert** [comment]
Do I understand correctly that after the delay, the system boots successfully?

It sounds like the culprit is [this GRUB command](https://github.com/coreos/scripts/blob/97ab6524433bd347299216d42f130ac12836c313/build_library/grub.cfg#L74-L75), which is supposed to fail after the first boot but isn't supposed to take 8 minutes to do it.  At a guess:

- On the first boot, GRUB stops searching after the first disk.
- On subsequent boots, the first disk doesn't contain the GUID in question, so GRUB continues searching.  For some reason, checking for other disks takes a long time on the Up Board firmware.

Are you booting via BIOS or via UEFI?

**Comment by salkin** [comment]
Yes, every boot is successful.

Using UEFI based boot. Though the UpBoard has a weird option which I don't know what it means. Where selecting the boot option to UEFI there is a second option of "OS Image ID:  Android" so not really sure what the UpBoard UEFI contains if it has some specialities.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
