### ISSUE TITLE
cloud-init, etcd2, fleet 

### ISSUE THREAD

**Issue by xueshanf** [coreos/bugs#2172]
# Issue Report #

### Environment ###

AWS

### Other Information ###

We have multiple dev, prod environments,  built on top of cloud-init, etcd2, and fleet. A lot of automation processes and code have been developed over the years. With all these components set to be deprecated, it's a challenge to tackle these changes all at once. I hope I am not the only one on this boat, but what would you recommend for migration priorities?  What would happen when things do get "deprecated", I am afraid of the clusters just stop working all of sudden.  We are racing with time.  Our current plan is to run Kubernets on AWS platform with our own build, but the infrastructure build uses cloud-init and etcd2 cluster.  What's the timeline for end-of support for these components? It's been great to use CoreOS for its auto-upgrade and container feature, hopefully we can stay on this platform.

**Comment by agokjr** [comment]
## Environment
mostly Bear metal (coros-install script install to disk, No {PXE, DHCP, iPXE}) and some AWS (though might as well be bear metal)

## Cluster management
I have a similar concern because I am running on mostly bear metal and cloud-init was simple to apply new config changes to the cluster over time.

```
cat user_data | ssh core@${REMOTEHOST} sudo tee /var/lib/coreos-install/user_data
ssh core@${REMOTEHOST} sudo coreos-cloudinit --from-file /var/lib/coreos-install/user_data
```

Ignition only runs first time so fails to have a way to reapply the config after generating a new config from my templating. (I hope that it not simply reinstall os to do a config update across the cluster?)

**Comment by bgilbert** [comment]
## fleet

fleet [will be removed from Container Linux on February 1, 2018](https://coreos.com/blog/migrating-from-fleet-to-kubernetes.html).  Since switching to Kubernetes is a significant transition, you'll probably want to focus on this part.  If February 1st doesn't give you enough time, the deprecation notice [describes how to continue running fleet in a container](https://coreos.com/blog/migrating-from-fleet-to-kubernetes.html#sustaining-fleet-clusters-with-the-fleet-container).

## etcd2

etcd2 [will also be removed from Container Linux on February 1, 2018](https://coreos.com/blog/toward-etcd-v3-in-container-linux.html).  etcd3 supports the etcd2 wire protocol, so you should be able to upgrade to etcd3 and continue to use your existing clients.  If you need to continue running etcd2 after February 1st, you should be able to use a modified version of `etcd-member.service` to run one of the [official etcd2 containers](https://quay.io/repository/coreos/etcd?tag=latest&tab=tags).  

## coreos-cloudinit

coreos-cloudinit has been superseded by the Ignition tool, configured via [Container Linux Configs](https://coreos.com/os/docs/latest/provisioning.html).  We have not set a schedule for removing coreos-cloudinit from Container Linux.  We would, of course, announce a deprecation period before doing so.  As a result, this migration will likely be your lowest priority of the three.

If you are using coreos-cloudinit only for initial provisioning of machines, [migrating to Container Linux Configs](https://coreos.com/os/docs/latest/migrating-to-clcs.html) should be reasonably straightforward.  Because coreos-cloudinit runs on every boot, some users also use coreos-cloudinit to perform configuration updates to existing machines.  Ignition intentionally does not support this use; we recommend that deployments that need such functionality use a configuration management tool.

**Comment by xueshanf** [comment]
@bgilbert Thanks so much! This is very helpful and it is also good to know you are delaying removing coreos-cloudinit.  Currently we just use a script as user-data, which in turn download real coreos cloud-config from AWS S3 bucket. As @agokjr mentioned, being able to run the script on the server during the development phase to iterate code saves lots of time without having to rebooting machines or tear down machines. Maybe something similar can be considered for ignition.  

I will look into etcd-member.service to run etcd3, test our etcd bootstraping code (v2) and hopefully fleet just works against etcd3  with v2 api. 

You can go ahead to close this issue. Thanks!

**Comment by bgilbert** [comment]
@xueshanf Much of Ignition's functionality requires Ignition to run from the initramfs, so there's not a good way to test a config without rebooting.  For development purposes, this completely unsupported process may be useful:

1. Put your Ignition config at `/usr/share/oem/config.ign`.  If you want to ensure a fresh system on every run, have it reformat `/dev/disk/by-partlabel/ROOT` and label the new filesystem `ROOT`.
2. Add `set linux_append="$linux_append coreos.config.url=oem:///config.ign"` to `/usr/share/oem/grub.cfg`, creating that file if necessary.
3. To rerun the config, `sudo touch /boot/coreos/first_boot && sudo rm -f /etc/machine-id && sudo reboot`.
