### ISSUE TITLE
Google Compute Engine Hostname not resolving from inside Docker container on Alpha Build

### ISSUE THREAD

**Issue by advanderveer** [coreos/bugs#220]
Easy to reproduce:

1. Fire up CoreOS alpha on google compute engine with name 'coreos-1'
2. Start a docker container and and run `ping coreos-1`

On the alpha channel it wont resolve, on the beta& stable it will resolve. Since no new version of Docker seemed to be released between the two it seems to be a coreos issue? /etc/resolve looks okay inside the container.

I ran into this while working with weave; @see https://github.com/zettio/weave/issues/296

**Comment by xlab** [comment]
Oh cool, this is now in beta. Thanks.

**Comment by marineam** [comment]
Oops, didn't re-open when I claimed I was re-opening...

**Comment by marineam** [comment]
So the issue here is that the domain name in the DHCP lease is terminated with a trailing `.` and this commit is not allowing that because the domain name is being validated as a host name: https://github.com/systemd/systemd/commit/784d9b9c09aa1ecdc688f251ea423fb47892f498

Will need to either adjust the logic to strip the trailing `.` or allow that case for domain names.

**Comment by marineam** [comment]
Posted a patch for review: http://lists.freedesktop.org/archives/systemd-devel/2015-January/027117.html
