### ISSUE TITLE
Add Wireguard kernel module and tools

### ISSUE THREAD

**Issue by klausenbusk** [coreos/bugs#2225]
## Feature Request ##

I'm currently using OpenVPN running in a container, to ensure that all outgoing traffic is routed through a specific server, it works but is a bit messy. Wireguard seems looks like a more simple and clean solution, and can work as a simple encrypted replacement for a GRE tunnel (it can even replace flannel).

### Environment ###
> What hardware/cloud provider/hypervisor is being used to run Container Linux?

DigitalOcean
### Desired Feature ###

Please consider shipping CoreOS with the Wireguard kernel module and wg tool.

### Other Information ###

https://github.com/hobby-kube/guide#wireguard-setup
https://www.wireguard.com/papers/wireguard.pdf
https://utcc.utoronto.ca/~cks/space/blog/linux/WireGuardWhyISwitched

**Comment by bgilbert** [comment]
As a matter of policy, Container Linux doesn't ship out-of-tree kernel modules. I'll close this issue for now, but we can revisit if the WireGuard kernel module goes upstream.

If you'd like to run WireGuard yourself, you should be able to [build the kernel module using the developer container](https://coreos.com/os/docs/latest/kernel-modules.html) and then run `wg` from a container.

**Comment by klausenbusk** [comment]
> Container Linux doesn't ship out-of-tree kernel modules.

That make sense!

> I'll close this issue for now, but we can revisit if the WireGuard kernel module goes upstream.

I will..


> If you'd like to run WireGuard yourself, you should be able to build the kernel module using the developer container and then run wg from a container.

It is easy enough to build the kernel module (been there, done that), my "concern" is mostly how to keep the kernel module up-to-date automatic when CoreOS kernel is upgraded, but there seems to be some work to solve that: https://github.com/coreos/torcx/issues/93

**Comment by lorenz** [comment]
@klausenbusk I have a torcx module for WireGuard if you're interested

**Comment by klausenbusk** [comment]
> @klausenbusk I have a torcx module for WireGuard if you're interested

I'm very interested :)

**Comment by lorenz** [comment]
You can get it [here](https://blob.dolansoft.org/kmods/wireguard%3A0.0.20171017.torcx.tgz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=UCTUSDYJS5TCCJYG5494%2F20171110%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20171110T142942Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=9e14f3db0766601cdc6426595736ae55fb744e513e1ad945e347c69176cdd6e4) if you're running 1520.8.0. I will probably soon-ish publish the source and build/rollout process so you can build it yourself.

Drop it into `ls /var/lib/torcx/store/1520.8.0/`, configure the profile in /etc/torcx, add the WireGuard configs to `/etc/wireguard/$name.conf`, reboot and execute `sudo systemctl enable wg-quick@$name; sudo systemctl start wg-quick@$name` for every config you added. Minor issue is you need to call the wg tool with its full path /run/torcx/bin/wg, otherwise everything should work.

**Comment by klausenbusk** [comment]
> You can get it here if you're running 1520.8.0. I will probably soon-ish publish the source and build/rollout process so you can build it yourself.

Thanks! I would probably wait for you to publish the build logic. I prefer to run something I can build myself/reproduce.

**Comment by zx2c4** [comment]
@klausenbusk showed over in https://github.com/coreos/flannel/pull/637 how easy it was to do things with WireGuard instead of IPsec, and how much less code that all would entail. The only thing blocking its way, it seems, is the "matter of policy." I suppose this would be an opportune time, then, to ask for an exception to the "matter of policy", given the utility and small code size of WireGuard. Rather than adding lots of code to deal with the IPsec monster, you could avoid the headaches of a complicated PR and subsequent maintenance by doing it with WireGuard.

**Comment by dm0-** [comment]
I don't expect we'll make an exception for this.  There are ongoing efforts for merging the WireGuard kernel changes upstream, so this could potentially be included by default in the coming months.

It seems fairly straightforward to use torcx if you want to go that route.  I tried it with this (after starting a dev container with the same version as the host using `systemd-nspawn --bind="$PWD:/host" --image=coreos_developer_container.bin /bin/bash -l`).

```sh
pkg=WireGuard-0.0.20171211

# Clone a specific tag.
git clone --branch="${pkg##*-}" --depth=1 https://git.zx2c4.com/WireGuard "/tmp/$pkg"

# Verify the tag's signature.
gpg2 --keyserver pool.sks-keyservers.net --recv-keys AB9942E6D4A4CFC3412620A749FC7012A5DE03AE
git -C "/tmp/$pkg" tag -v "${pkg##*-}"

# Build the tools and module.
make -C "/tmp/$pkg/src" -j$(nproc) all V=1

# Install everything in a staging root directory.
make -C "/tmp/$pkg/src" install module-install DESTDIR=/tmp/root V=1
cp --parents "/lib/modules/$(uname -r)/extra/wireguard.ko" /tmp/root

# Edit the service to be torcx-aware.
sed -i \
    -e '/^\[Unit]/aRequires=torcx.target\nAfter=torcx.target' \
    -e "/^\\[Service]/aEnvironmentFile=/run/metadata/torcx\\nExecStartPre=-/sbin/modprobe ip6_udp_tunnel\\nExecStartPre=-/sbin/modprobe udp_tunnel\\nExecStartPre=-/sbin/insmod \${TORCX_UNPACKDIR}/${pkg%-*}/lib/modules/%v/extra/wireguard.ko" \
    -e 's,/usr/s\?bin/,${TORCX_BINDIR}/,g' \
    -e 's,^\([^ ]*=\)\(.{TORCX_BINDIR}\)/,\1/usr/bin/env PATH=\2:${PATH} \2/,' \
    /tmp/root/usr/lib/systemd/system/wg-quick@.service

# Write a torcx image manifest.
mkdir -p /tmp/root/.torcx
cat << 'EOF' > /tmp/root/.torcx/manifest.json
{
    "kind": "image-manifest-v0",
    "value": {
        "bin": [
            "/usr/bin/wg",
            "/usr/bin/wg-quick"
        ],
        "units": [
            "/usr/lib/systemd/system/wg-quick@.service"
        ]
    }
}
EOF

# Write the torcx image.
tar --force-local -C /tmp/root -czf "/host/${pkg/-/:}.torcx.tgz" .
```

Then on the host, write that file into e.g. `/var/lib/torcx/store/1618.0.0`, run `echo wg > /etc/torcx/next-profile`, copy `/usr/share/torcx/profiles/vendor.json` to `/etc/torcx/profiles/wg.json`, add `{ "name": "WireGuard", "reference": "0.0.20171211" }` to its images, and reboot.

**Comment by zx2c4** [comment]
Nice script. Something you might tweak there is all the manual module loading business. It looks like this environment _has_ modprobe, yet you manually insmod wireguard after manually modprobing its dependencies. You should be able to simply `modprobe wireguard`, and it will fulfill the dependencies automatically. However, you shouldn't actually need even that; running `ip link add wg0 type wireguard`, which is what `wg-quick(8)` runs, will cause the kernel to execute modprobe on its own in order to find the module. If this isn't happening, it's because `depmod -a` hasn't been run. The WireGuard `make install` target actually runs `depmod -a` on its own, but it appears what this script does is create a tarball meant to be run on a different system. Therefore, what I'd recommend is that you add some kind of "OnPackageInstall" script to the torcx package that simply runs depmod. Does torcx have this kind of capability?

**Comment by dm0-** [comment]
The files written by `depmod` are on an immutable partition, so that would require a writable overlay like https://coreos.com/os/docs/latest/kernel-modules.html in addition to what I wrote above.

**Comment by lorenz** [comment]
I have a torcx module that actually works, I manually resolved the dependencies since all modprobe config is immutable. Snippet from service file is here:
```
+EnvironmentFile=/run/metadata/torcx
+ExecStartPre=/usr/sbin/modprobe udp_tunnel
+ExecStartPre=/usr/sbin/modprobe ip6_udp_tunnel
+ExecStartPre=-/usr/sbin/insmod /run/torcx/unpack/wireguard/wireguard.ko
```

**Comment by lorenz** [comment]
Full build script is that:
```
#!/bin/bash
export VERSION=0.0.20171017

wget -O - https://git.zx2c4.com/WireGuard/snapshot/WireGuard-$VERSION.tar.xz | tar -xJf -
cd WireGuard-$VERSION/src
patch -u tools/wg-quick.bash << 'EOF'
--- wg-quick.bash.1	2017-10-29 23:34:03.000000000 +0000
+++ wg-quick.bash	2017-10-29 23:52:48.000000000 +0000
@@ -82,24 +82,6 @@
 }
 
 del_if() {
-	local fwmark
-	fwmark="$(wg show "$INTERFACE" fwmark)"
-	DEFAULT_TABLE=0
-	[[ $fwmark != off ]] && DEFAULT_TABLE=$(( fwmark ))
-	if [[ $DEFAULT_TABLE -ne 0 ]]; then
-		while [[ $(ip -4 rule show) == *"lookup $DEFAULT_TABLE"* ]]; do
-			cmd ip -4 rule delete table $DEFAULT_TABLE
-		done
-		while [[ $(ip -4 rule show) == *"from all lookup main suppress_prefixlength 0"* ]]; do
-			cmd ip -4 rule delete table main suppress_prefixlength 0
-		done
-		while [[ $(ip -6 rule show) == *"lookup $DEFAULT_TABLE"* ]]; do
-			cmd ip -6 rule delete table $DEFAULT_TABLE
-		done
-		while [[ $(ip -6 rule show) == *"from all lookup main suppress_prefixlength 0"* ]]; do
-			cmd ip -6 rule delete table main suppress_prefixlength 0
-		done
-	fi
 	cmd ip link delete dev "$INTERFACE"
 }
 
@@ -139,32 +121,12 @@
 }
 
 add_route() {
-	if [[ $1 == 0.0.0.0/0 || $1 =~ ^[0:]+/0$ ]]; then
-		add_default "$1"
-	else
-		cmd ip route add "$1" dev "$INTERFACE"
-	fi
+	:
 }
 
 DEFAULT_TABLE=
 add_default() {
-	if [[ -z $DEFAULT_TABLE ]]; then
-		DEFAULT_TABLE=51820
-		while [[ -n $(ip -4 route show table $DEFAULT_TABLE) || -n $(ip -6 route show table $DEFAULT_TABLE) ]]; do
-			((DEFAULT_TABLE++))
-		done
-	fi
-	local proto=-4
-	[[ $1 == *:* ]] && proto=-6
-	cmd wg set "$INTERFACE" fwmark $DEFAULT_TABLE
-	cmd ip $proto route add "$1" dev "$INTERFACE" table $DEFAULT_TABLE
-	cmd ip $proto rule add not fwmark $DEFAULT_TABLE table $DEFAULT_TABLE
-	cmd ip $proto rule add table main suppress_prefixlength 0
-	local key value
-	while read -r key _ value; do
-		[[ $value -eq 1 ]] && sysctl -q "$key=2"
-	done < <(sysctl -a -r '^net\.ipv4.conf\.[^ .=]+\.rp_filter$')
-	return 0
+	:
 }
 
 set_config() {
EOF
make -j$(nproc)
TMPDIR=$(mktemp -d)
make install PREFIX=$TMPDIR SYSTEMDUNITDIR=$TMPDIR/lib/systemd/system WITH_SYSTEMDUNITS=yes

cat $TMPDIR/lib/systemd/system/wg-quick@.service
ls $TMPDIR/lib/systemd/system/
patch -u $TMPDIR/lib/systemd/system/wg-quick@.service << EOF
--- $TMPDIR/lib/systemd/system/wg-quick@.service 2017-10-27 22:47:34.000000000 +0000
+++ $TMPDIR/lib/systemd/system/wg-quick@.service1 2017-10-27 22:48:33.000000000 +0000
@@ -12,6 +12,10 @@
 [Service]
 Type=oneshot
 RemainAfterExit=yes
+EnvironmentFile=/run/metadata/torcx
+ExecStartPre=/usr/sbin/modprobe udp_tunnel
+ExecStartPre=/usr/sbin/modprobe ip6_udp_tunnel
+ExecStartPre=-/usr/sbin/insmod /run/torcx/unpack/wireguard/wireguard.ko
 ExecStart=/usr/bin/wg-quick up %i
 ExecStop=/usr/bin/wg-quick down %i
EOF
sed -i 's|/usr/bin/wg|/usr/bin/env PATH=${TORCX_BINDIR}:${PATH} ${TORCX_BINDIR}/wg|' $TMPDIR/lib/systemd/system/wg-quick@.service

mkdir $TMPDIR/.torcx
cat > $TMPDIR/.torcx/manifest.json << EOF
{
  "kind": "image-manifest-v0",
  "value": {
      "bin": [
          "/bin/wg",
          "/bin/wg-quick"
      ],
      "units": [
          "/lib/systemd/system/wg-quick@.service"
      ]
  }
}
EOF

cp wireguard.ko $TMPDIR
cd $TMPDIR
tar --force-local -zcf $HOME/wireguard:$VERSION.torcx.tgz .
cd /
rm -rf $TMPDIR
```
I'm still fighting with full-CI building (K8s pod -> KVM -> Systemd-Nspawn), but it works pretty well with manual execution of the build step.

**Comment by zx2c4** [comment]
> The files written by depmod are on an immutable partition

Ooof, rough environment we're in. Here's a little one liner that will determine dependencies for you then, so you don't have to hard code something that _could_ change, in case it's useful:

```
modinfo -F depends path/to/wireguard.ko | tr ',' '\n' | xargs -n 1 modprobe
```

**Comment by antoniaklja** [comment]
I was trying to build custom kernel module but `/lib/modules/4.0.5/build` doesn't not exists.
Env:
`MANPATH=/usr/local/share/man:/usr/share/man
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=83.0.221.49 42826 22
SSH_TTY=/dev/pts/0
USER=core
PAGER=/usr/bin/less
MAIL=/var/mail/core
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
PWD=/home/core
EDITOR=/usr/bin/vim
LESSCHARSET=utf-8
SHLVL=1
HOME=/home/core
LESS=-R -M --shift 5
LOGNAME=core
SSH_CONNECTION=83.0.221.49 42826 172.31.3.78 22
LESSOPEN=|lesspipe %s
INFOPATH=/usr/share/info
CONFIG_PROTECT=/usr/share/gnupg/qualified.txt
_=/usr/bin/env
`

cc @dm0-

**Comment by dm0-** [comment]
That script expects to be run in a developer container on a host with the same CoreOS version.  You'll have to modify it to do otherwise.

If you _are_ running it with matching versions, maybe 681.1.0 is just too old to have a comparable environment.  It has been unsupported for several years at this point.

**Comment by antoniaklja** [comment]
> That script expects to be run in a developer container on a host with the same CoreOS version
versions were the same.

I'll give a try with different CoreOS version.

**Comment by nopdotcom** [comment]
I packaged up the build script into Vagrant at <https://github.com/nopdotcom/coreos-build-wireguard>.

**Comment by miguelangel-nubla** [comment]
Based on the insights from this thread:
WireGuard for CoreOS packages https://github.com/miguelangel-nubla/WireGuard-CoreOS
