### ISSUE TITLE
igntion causes md array resync every reassembly

### ISSUE THREAD

**Issue by redbaron** [coreos/bugs#2263]
## Bug ##

Ignition 0.19 as found in 1576.2.0 causes mdarrays to be resynced every time they are reassembled by ignition. Not sure if it qualifies as a bug, but definitely is undesirable behaviour.

**Comment by bgilbert** [comment]
Could you post your Ignition config and logs?  (`journalctl -t ignition`, plus any messages showing the resync.)  Ignition only runs on the first boot, so it shouldn't be causing resyncs on subsequent boots.

**Comment by redbaron** [comment]
I wasn't clear enough. On a simple reboot everything is fine.  Resync happens when ignition reassembles array. Basically I was looking for something like `wipeFilesystem` flag, where if array is already present Ignition just assembles it in a similar way as normal boot assembles it without resync.

Hope it makes it a bit clearer

**Comment by ajeddeloh** [comment]
Are you running Ignition mutliple times? Unless you're on a platform that requires it (e.g. PXE), Ignition should only run on first boot. Can you post some logs from `journalctl -t ignition --no-pager` and your Ignition configuration/CLC? If your root partition is on a RAID array [things are handled a little differently so the initramfs can find and mount it](https://coreos.com/os/docs/latest/root-filesystem-placement.html)

We're reworking the way Ignition does partitioning and RAID to better handle existing partitions and arrays. We're tackling partitioning first, since it's slightly less hairy, then RAID.

For RAID, the general plan is to make it more similar to how filesystems are handled. Ignition currently tries to recreate the array every time it runs, which may be while you're seeing re-syncs. Our plan (subject to change) is to have Ignition first try to assemble and start the array specified (instead of creating it) and only then create it if the drives are unused or an option `overwriteDevices` is set. We are also planning on adding an `options` field to be passed directly to mdadm.

You can see our discussion [on RAID specifically](https://github.com/coreos/ignition/pull/443/files) and [on raid and partitioning together](https://github.com/coreos/ignition/pull/436). If you have input on our current plans we'd love to hear it.

**Comment by redbaron** [comment]
> Are you running Ignition mutliple times? 
Yes, I am reconfiguring CoreOS servers via PXE boot, but preserving data raid array between reconfigs. Currently Ignition allows me to keep data, but causes underneath md array to be rsynced. 

> For RAID, the general plan is to make it more similar to how filesystems are handled. Ignition currently tries to recreate the array every time it runs, which may be while you're seeing re-syncs. Our plan (subject to change) is to have Ignition first try to assemble and start the array specified (instead of creating it)

That is exactly what I was looking for! Create array first, then just assemble it without resyncing. Looking forward for these changes to land in Ignition :)

**Comment by bgilbert** [comment]
Great, thanks for the report.  I'll close this as a duplicate of https://github.com/coreos/bugs/issues/2100.

In general, it's not possible to reinitialize a RAID array in place and expect its data to remain intact, so your current approach is not safe.  It will probably work as long as all drives are healthy and the system is shut down cleanly, but if e.g. a drive has an intermittent problem and is failed out of the array, recreating the array metadata could cause stale data to be resynced over current data.

For now, it would be better not to handle that RAID in your Ignition config at all, but instead to write a systemd service which initializes the array only if it doesn't already exist.
