### ISSUE TITLE
etcd-member unit becomes ready before accepting requests

### ISSUE THREAD

**Issue by discordianfish** [coreos/bugs#2286]
# Issue Report #
### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
AWS

### Expected Behavior ###
When services with `After=etcd-member.service` get started, the etcd api should be ready to serve requests.

### Actual Behavior ###
Sometimes etcd isn't ready at this point, causing depending units to fail.
Specifically I'm running `kubeadm` in a unit file with `After=etcd-member.service`, yet sometimes it get started too early and fails with:

```
Dec 13 12:52:01 ip-172-20-144-6 kubeadm[858]:         [ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
```

### Reproduction Steps ###
It's a bit racy, so not that reliable to reproduce but it boils down to starting etcd followed by something that talks to the API.

**Comment by lucab** [comment]
Thanks for reporting this. According to [kubeadm source](https://github.com/kubernetes/kubernetes/blob/38e33513126e2090b578531b7c3919348bf6b167/cmd/kubeadm/app/preflight/checks.go#L740-L749), when that error occurs the pre-flight check got a non-error response from etcd. However, it is unable to parse that, seemingly because it is empty.

`etcd-member.service` is a `type=notify` unit, and [etcd source](https://github.com/coreos/etcd/blob/v3.2.11/etcdmain/etcd.go#L163-L168) seems to correctly notify its start once everything else is done.

I suggest you to file a ticket against kubeadm or etcd directly, to investigate why the version endpoint seems to return a positive but empty response. On the OS side, everything looks as I would expect on the surface.
Just for completeness, you could check the journal around kubeadm starting time, to verify that the etcd unit is marked as started before the kubeadm one is starting.

**Comment by discordianfish** [comment]
Thanks @lucab, you're right this appears to be rather a etcd issue.
