### ISSUE TITLE
why core-cloud-init will  execute user-data every rebooting？

### ISSUE THREAD

**Issue by archerslaw** [coreos/bugs#2307]
# Issue Report #

why core-cloud-init will  execute user-data every rebooting？

### Container Linux Version ###

```
$ cat /etc/os-release
Version=1298.7.0
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Expected Behavior ###
core-cloud-init will  execute user-data only the first booting, just execute the user-data per-instance.

### Actual Behavior ###
core-cloud-init will  execute user-data every rebooting

### Reproduction Steps ###

  1. ...
  2. ...

**Comment by dgonyeo** [comment]
Cloudinit runs after every boot by design. You can read more on cloudinit in this document: https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/cloud-config.md

I highly recommend using container linux configs instead of cloudinit, which will only run on the first boot (aside from a few other benefits). Here's our documentation on provisioning container linux: https://coreos.com/os/docs/latest/provisioning.html

**Comment by archerslaw** [comment]
No， the cloud-init for redhat/oracle/suse/opensuse/ubuntu/debian and cloudbase-init for windows only execute user-data only the first booting, just execute the user-data per-instance.

Any good workaround for this issue, i do not need the user-data  executed every rebooting at all, THX.

Actual Behavior

**Comment by dgonyeo** [comment]
You could try deleting the userdata stored on disk that cloudinit is executing, which on bare metal at least is stored at `/var/lib/coreos-install/user_data`. The path might vary depending on your platform.

**Comment by lucab** [comment]
> Any good workaround for this issue, i do not need the user-data executed every rebooting at all

The "workaround" is to let Ignition take care of provisioning the supplied user-data. By design, this only happens on the first boot. However you need to craft a proper configuration for it, either manually or starting from a Container Linux Config.
That is indeed the recommended way of provisioning ContainerLinux instances, as documented in https://coreos.com/os/docs/latest/provisioning.html.

**Comment by archerslaw** [comment]
You shoud not say this by design at all, the users and me just need the user-data  execute only the first booting, not run every rebooting.

**Comment by archerslaw** [comment]
you should refer to the cloud-init and cloudbase-init source code how this designed, why does the coreos-cloudinit so that, this behaviour is rubbish for the users. e.g. if the user inject a script for a password resetting, and the user cann't change the password at all when he login to the VM after rebooting the instance.

**Comment by mcapuccini** [comment]
Hitting the same problem, very frustrating.
