### ISSUE TITLE
CL sometimes does not reboot into the correct partition

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/bugs#2334]
# Issue Report #

### Container Linux Version ###
Current master, mostly likely all version

### Environment ###

AWS, possibly others

### Expected Behavior ###

When set to reboot into `USR-B`, it does.

### Actual Behavior ###

Occasionally it reboots into `USR-A` instead

### Reproduction Steps ###

Run the `coreos.update.reboot` kola test until it fails on aws (may take a while to fail, recommend doing it a while loop)

### Other Information ###
I modified the test locally to run `cgpt show /dev/xvda` before and after setting it to boot from USR-B and confirmed it does set the prio/tries/success bits correctly and there is no difference between successful and unsuccessful runs.

**Comment by euank** [comment]
To replicate some discussion:

update_engine, around [45 seconds](https://github.com/coreos/update_engine/blob/eb3900a/src/update_engine/main.cc#L128-L131) after starting, will mark the current partition as [good](https://github.com/coreos/update_engine/blob/eb3900a/coreos-setgoodroot).

The [reboot test](https://github.com/coreos/mantle/blob/abe8b8/kola/tests/misc/update.go#L51-L67) in question, on boot, does some disk io, marks usr-b, and reboots.

It's possible that if it takes about 45 seconds to do the disk-io/setup stuff, update_engine could overwrite our 'usr-b' mark with its "setgood usr-a" marking, and result in this sort of failure.

That seems like a plausible enough possibility which we'll investigate now. If it's that, then the bug was in the test, not grub or update_engine, so here's to hoping 😌

**Comment by ajeddeloh** [comment]
Looks like that is in fact the case. Masking update-engine seems to fix the problem. Closing since this is mantle/test bug not an OS bug. See mantle fix here: https://github.com/coreos/mantle/pull/801
