### ISSUE TITLE
error creating overlay mount to .../merged: invalid argument.

### ISSUE THREAD

**Issue by taadis** [coreos/bugs#2340]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

阿里云ECS

### Reproduction Steps ###

``` docker
docker pull hello-world
docker run -it hello-world
/run/torcx/bin/docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay/dd60d72e130f87883312069f54ae40d886ce40e3a589ad5a2b5c44020f9c8e1d/merged: invalid argument.
See '/run/torcx/bin/docker run --help'.
```

### Other Information ###

**Comment by lucab** [comment]
Thanks for the report. I can't reproduce this on stable, and our CI didn't seem to experience this either.

It would be great if you could add additional details on your environment. What is the content of `/var/lib/update_engine/prefs/aleph-version` and what does `docker info` say?

**Comment by euank** [comment]
Since we don't actually publish images for Alibaba cloud, it's possible the issue is in their image or configuration.

If you're able to reproduce this issue on a different platform or figure out more information about the error, that would be helpful.

Possible steps to get more information about the error could be:
1. Check docker's log output (set the loglevel to debug, look for any other output related to that mount or other errors)
1. `strace` the containerd process, including spawned children, and find the set of calls related to that mountpoint and what arguments + return code the failed call had.
1. Add additional debug code to the docker daemon

**Comment by ill55666** [comment]
Same issue here.

@taadis 有解吗？

My friend chat with aliyun cs: (using their public coreos image)

<img width="575" alt="screen shot 2018-03-09 at 10 01 11" src="https://user-images.githubusercontent.com/37199447/37186528-ee59f1ec-2380-11e8-82d4-f78178268b97.png">

Summary:

The image is not owned by them.
You need debug by yourself. 😭

**Comment by ill55666** [comment]
Finally, i know how to fix this.
The reason is aliyun ecs may not support overlay [storage driver](https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-ce),
you need manually changing it to devicemapper.

see https://github.com/moby/moby/issues/23930#issuecomment-337413837

Full script:

```sh
# fix wrong driver
echo '{ "storage-driver": "devicemapper" }' | sudo tee /etc/docker/daemon.json
sudo systemctl restart docker.service

# fix aliyun buggy selinux
sudo sed -i 's/SELINUXTYPE=mcs/SELINUXTYPE=targeted/' /etc/selinux/config
```

**Comment by ill55666** [comment]
BTW,
The engineer just reply us with NO solution and suggest us to use their container service...
😠

**Comment by taadis** [comment]
@ill55666 同感

**Comment by taadis** [comment]
@ill55666 给你看看阿里某工程师的解决方案:
```
vi /run/systemd/system/docker.service 
注释掉 #Environment=DOCKER_SELINUX=--selinux-enabled=true 
然后reload一下配置文件
systemctl daemon-reload 
重启docker 即可 
systemctl restart docker
```
好一个解决方法...

**Comment by euank** [comment]
Changing the overlay driver or selinux config shouldn't be necessary. It sounds like the Container Linux image being used might be broken, or the instance's storage might be misbehaving.

Unfortunately, since we don't publish or support those images, I don't think there's much we can do on our end to fix these problems.

If you do run into this issue on another platform or find more information about why things are broken (e.g. from steps in [my previous comment](https://github.com/coreos/bugs/issues/2340#issuecomment-363257964)), let us know and we can look again.

Best,
Euan

**Comment by congjie** [comment]
这个问题我的一个解决方案，修改/etc/selinux/config 改SELINUX=disable 改成 SELINUX=permissive

**Comment by 1412kid** [comment]
我比较赞同congjie的解决方法，推荐修改/etc/selinux/config 改SELINUX=disabled 改成 SELINUX=permissive 
因为腾讯云的CoreOs就默认是permissive
