### ISSUE TITLE
github.com/coreos/coreos-overlay uses github.com/jteeuwen/go-bindata

### ISSUE THREAD

**Issue by ericchiang** [coreos/bugs#2349]
# Issue Report #

The owner of github.com/jteeuwen/go-bindata recently deleted their account, and someone else took it over.

https://twitter.com/francesc/status/961249107020001280

We probably want to re-evaluate how we're using that tool and if we should switch to something else.

**Comment by euank** [comment]
The ebuild checks out a specific git commit, so an attack would also need to cause a git collision. I wouldn't be too worried about that. It also seems to be completely unused for any purpose.

From its [history](https://github.com/coreos/coreos-overlay/commits/6b2e14bbd4a82ad3f716e2e47b0ce6d46e4cf04f/dev-util/go-bindata), it was added for rkt, and rkt hasn't depended on it [since 2015](https://github.com/rkt/rkt/pull/436), so it should be entirely safe to delete.

**Comment by bgilbert** [comment]
https://github.com/coreos/coreos-overlay/pull/3052 drops the package.  Thanks for reporting.
