### ISSUE TITLE
No update available

### ISSUE THREAD

**Issue by ruudboon** [coreos/bugs#2393]
I'm trying to manual update my CoreOS install from 1662.2.0 to latest 1688.4.0 looking at the log files it looks like https://public.update.core-os.net/v1/update/ is returning the wrong info.

Some grabs from the log file
```
Posting an Omaha request to https://public.update.core-os.net/v1/update/
<request protocol="3.0" version="update_engine-0.4.2" updaterversion="update_engine-0.4.2" installsource="scheduler" ismachine="1">
<os version="Chateau" platform="CoreOS" sp="1662.2.0_x86_64"></os>

Omaha request response: <?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="update.core-os.net">
<daystart elapsed_seconds="0"></daystart>
<app appid="xxx-xx" status="ok">
<updatecheck status="noupdate"></updatecheck>
</app>
</response>
```

I tried resetting the update using
```
sudo update_engine_client -reset_status
sudo update_engine_client -check_for_update
```

**Comment by bgilbert** [comment]
We are not rolling out updates to 1688.4.0 due to a regression; see [here](https://groups.google.com/d/topic/coreos-user/5ihE2cKuYck/discussion) for more information.  The stable channel is currently set to 1632.3.0.

In addition, though, the update you're attempting is unusual.  1662.2.0 is a beta release, so unless you've switched your machine from the beta channel to the stable channel, it should be successfully updating to 1722.2.0.

**Comment by ruudboon** [comment]
@bgilbert Yes, I've switched to the stable branch that why I'm so eager to get the update.
Thnx. I'll wait for a fix. Is there a way to update this [page](https://coreos.com/releases/) and add a notice?

**Comment by bgilbert** [comment]
Stable 1688.5.3 addresses the regression in 1688.4.0 and is rolling out now.
