### ISSUE TITLE
Advice on how to inspect sudden (seemingly random) system crashes

### ISSUE THREAD

**Issue by mbger** [coreos/bugs#2465]
# Issue Report #

I am experiencing sudden system crashes / hangs on my server, but so far I could not manage to reproduce the crashes or find anything in the logs which points me to the root of the problem. When the system crashes, the entire machine is unresponsive. Pressing and holding the Power button does not trigger a shutdown or reboot. I have to switch off the power supply, switch it on again, and only then I am able to boot the system by pressing the power button. 

Is it possible that this is an overheating issue? Any advice on how to track down the cause of these crashes is much appreciated. 

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.7.0
VERSION_ID=1745.7.0
BUILD_ID=2018-06-14-0909
PRETTY_NAME="Container Linux by CoreOS 1745.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

I am running CoreOS on a Bare Metal Server.

### Expected Behavior ###

Well, the system should not crash ...

### Actual Behavior ###

... yet it does.

### Reproduction Steps ###

Unfortunately, I couldn't find any pattern to the crashes, but everything I know so far is in the section below. 

### Other Information ###

As mentioned at the top, I find it odd that the system does not react to anything and that the only option to get it back up again is pulling the plug. 

Here's the output of the `last` command: 

```text
core     ssh          192.168.1.82     Wed Jun 20 12:07 - 12:34  (00:27)
reboot   system boot  4.14.48-coreos-r Wed Jun 20 12:04 - 12:56  (00:51)
core     pts/1        192.168.1.77     Wed Jun 20 09:54 - crash  (02:10)
core     ssh          192.168.1.77     Wed Jun 20 09:54 - 09:56  (00:02)
core     pts/0        192.168.1.86     Wed Jun 20 08:45 - 09:56  (01:11)
```

And here is the `journalctl` log before and after the reboot: 

```text
Jun 20 09:54:11 hochstaufen systemd[1]: Started OpenSSH per-connection server daemon (192.168.1.77:55687).
Jun 20 09:54:16 hochstaufen sshd[13736]: Accepted publickey for core from 192.168.1.77 port 55687 ssh2: RSA SHA256:g2ohJyB2eKdC41y3JLW9zd/f3NbQqj/Q9YnPiT2V6Tc
Jun 20 09:54:16 hochstaufen sshd[13736]: pam_unix(sshd:session): session opened for user core by (uid=0)
Jun 20 09:54:16 hochstaufen systemd-logind[720]: New session 6 of user core.
Jun 20 09:54:16 hochstaufen systemd[1]: Started Session 6 of user core.
Jun 20 09:56:39 hochstaufen sshd[11570]: Received disconnect from 192.168.1.86 port 53840:11: disconnected by user
Jun 20 09:56:39 hochstaufen sshd[11570]: Disconnected from user core 192.168.1.86 port 53840
Jun 20 09:56:39 hochstaufen sshd[11570]: pam_unix(sshd:session): session closed for user core
Jun 20 09:56:39 hochstaufen systemd-logind[720]: Removed session 5.
-- Reboot --
Jun 20 12:04:46 localhost kernel: Linux version 4.14.48-coreos-r2 (jenkins@ip-10-7-32-103) (gcc version 7.3.0 (Gentoo Hardened 7.3.0 p1.0)) #1 SMP Thu Jun 14 08:23:03 UTC 2018
Jun 20 12:04:46 localhost kernel: Command line: BOOT_IMAGE=/coreos/vmlinuz-b mount.usr=/dev/mapper/usr verity.usr=PARTUUID=e03dd35c-7c2d-4a47-b3fe-27f15780a57c rootflags=rw mount.usrflags=ro consoleblank=0 root=LAB
EL=ROOT console=ttyS0,115200n8 console=tty0 coreos.config.url=oem:///coreos-install.json verity.usrhash=40d5ccdbb27a1b659fe84a6da8a68277bf53927d2939c947df896362dc915ec8
Jun 20 12:04:46 localhost kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Jun 20 12:04:46 localhost kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Jun 20 12:04:46 localhost kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Jun 20 12:04:46 localhost kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Jun 20 12:04:46 localhost kernel: x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
```

**Comment by ajeddeloh** [comment]
Hi, do you know if it happens with older versions of coreos (i.e. is new behavior with 1745.7.0)? If possible can you try alpha and/or beta as well?

**Comment by mbger** [comment]
Hi, thanks for the quick reply! `pstore` is empty. I had this problem with earlier versions of CoreOS, too. I have a second machine which also runs the latest CoreOS version from the stable channel, where I don't have any issues at all. 

The machine where the crashes occur has `var/lib/docker` mounted to a RAID1 drive (hardware RAID), so might this be a potential weak point? 

Here's the `journalctl` log for the `var-lib-docker.mount` unit. The first Reboot was after the system crash. The second Reboot was intentional. Nothing spectacular going on there...

```text
Jun 18 13:12:54 hochstaufen systemd[1]: Mounting Mount RAID1 configuration to /var/lib/docker...
Jun 18 13:12:55 hochstaufen systemd[1]: Mounted Mount RAID1 configuration to /var/lib/docker.
-- Reboot --
Jun 20 12:04:51 hochstaufen systemd[1]: Mounting Mount RAID1 configuration to /var/lib/docker...
Jun 20 12:04:53 hochstaufen systemd[1]: Mounted Mount RAID1 configuration to /var/lib/docker.
Jun 20 12:56:36 hochstaufen systemd[1]: Unmounting Mount RAID1 configuration to /var/lib/docker...
Jun 20 12:56:37 hochstaufen systemd[1]: Unmounted Mount RAID1 configuration to /var/lib/docker.
-- Reboot --
Jun 20 12:57:52 hochstaufen systemd[1]: Mounting Mount RAID1 configuration to /var/lib/docker...
Jun 20 12:57:53 hochstaufen systemd[1]: Mounted Mount RAID1 configuration to /var/lib/docker.
```

**Comment by lucab** [comment]
@mbger is this a baremetal node? If so, when it freezes it may be spitting out kernel logs on the console. 
How often does this happen and is it limited to a single machine? I would run a memtest/cpuburn before further digging into the kernel side, because it may be simply a faulty piece of hardware.

**Comment by mbger** [comment]
@lucab Yes it's a baremetal node. After the freeze yesterday I attached a monitor to it. 

> How often does this happen

Usually, it freezes every 2 to 3 days, so let's see if the console will show anything interesting. 

> and is it limited to a single machine?

Yes.

> I would run a memtest/cpuburn before further digging into the kernel side

I will read up on that and do it, thanks for the tip! 

> ...because it may be simply a faulty piece of hardware.

Yeah, right now this is my best guess, too, but didn't know how to best approach investigating it.

**Comment by lorenz** [comment]
@mbger I've seen this exact issue on one of my Haswell-based nodes. What hardware are you running on?

**Comment by mbger** [comment]
@lorenz Can you reproduce your issue? I'm currently waiting for the next crash to see if the Console has any useful information. 

My hardware: 
- Processor: **AMD A12-9800E**
- Board: **GIGABYTE GA-AB350N**
- RAID Controller: **Adaptec RAID 6405E**

**Comment by lorenz** [comment]
Off-topic: For me it was a bad CPU. Hang frequency was a bit lower than yours (every few weeks). It is definitely not the OS if your reset and power buttons stop working. Basically it could be either the power supply. the motherboard or the CPU. When you press your reset button or ACPI power button the SuperIO chip basically attempts to reset the system by asserting a lot of RST lines in the board. If that fails it initiates (after some time, usually 5 seconds) a full reboot by powering down the power supply. This still worked for my system. Because that doesn't seem to work on yours we have to assume that either the SuperIO stopped working (because of an internal fault, heat or power management issues) or that the power supply fails to power off.

If you have a system you can use to swap components with, I'd just swap until the bug goes away. Then you have your culprit. Otherwise next time the system hangs, probe all power supply voltages with a multimeter and check if they are within reasonable limits. Press the reset button or the power button for more than 5 seconds, wait another 5 seconds, then check if PS_ON (on the ATX connector) is being pulled high (>0.7V). If it is and you still see voltages other than 5v on your connector, your PSU is faulty (it doesn't power off). If you haven't found the PSU at fault by now, I'd just replace the motherboard. It is very likely the cause of your issues.

As for the actual issue: I think it can be closed as a hardware error. It's pretty unlikely that CoreOS broke the either the SuperIO chip in a way where it doesn't perform critical hardwired functions or made the PSU fail.

**Comment by mbger** [comment]
@lorenz Thank you very much for the detailed info. I totally agree that this has to be some hardware issue. I am now moving everything from that machine to other hosts. I am still curious if the OS may be in any form responsible for the hardware to get into this faulty state or if this is truly software independent. 

If @lucab and / or others say that this cannot possibly be caused by an OS bug, I will close the issue. Meanwhile, I'll still try to reproduce the issue because I really want to know what's going on there.

**Comment by lucab** [comment]
@mbger while I can't exclude a kernel bug, this ticket is likely peculiar to your environment so it isn't something that we can easily debug and fix on our side. If you manage to track down the issue we can help following up with the fix, but otherwise unfortunately there isn't much we can do here at the moment.

**Comment by mbger** [comment]
@lucab No worries, the discussion here already helped me understand the problem better and convinced me to swap the hardware in the short term. I am closing the issue for now and if I can come back to the server at a later time and discover something which is worthwile to share here, I will update or reopen the issue. Thanks!
