### ISSUE TITLE
Update OpenSSL to 1.0.2o

### ISSUE THREAD

**Issue by kbrwn** [coreos/bugs#2466]
## Feature Request ##

Update OpenSSL from 1.0.2n to 1.0.2o

### Other Information ###

https://www.openssl.org/news/openssl-1.0.2-notes.html

**Comment by dm0-** [comment]
We can push the update and have it released with the alpha in two weeks, but what is prompting this?  Is there a security issue?  Some reason to consider backporting to other channels?

**Comment by kbrwn** [comment]
This is a request from CoreOS customer Nike. Perhaps @zlangbert can provide additional info.

**Comment by zlangbert** [comment]
Thanks Kyle and David, we had a request come from our security team to be on the latest version of OpenSSL. Our timeline has since been clarified, and there is no immediate need, but would like to see this is the coming month or two. If possible, if it could get into the next alpha I think that would be sufficient. Thanks!
