### ISSUE TITLE
sys-apps/file-5.33-r2 breaks splitdebug for a target

### ISSUE THREAD

**Issue by hasso** [coreos/bugs#2469]
### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1814.0.0+2018-06-28-1821
VERSION_ID=1814.0.0
BUILD_ID=2018-06-28-1821
PRETTY_NAME="Container Linux by CoreOS 1814.0.0+2018-06-28-1821 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD=""
```

### Environment ###

SDK

### Expected Behavior ###

All binaries in target are expected to be stripped and debug info splitted into separate file.

### Actual Behavior ###

Binaries are installed with full debug info.

### Reproduction Steps ###

Just an example:
```
$ emerge-amd64-usr sudo
...
$ sudo file /build/amd64-usr/usr/bin/sudo
/build/amd64-usr/usr/bin/sudo: setuid ELF 64-bit LSB pie executable x86-64, version 1
(SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32,
with debug_info, not stripped 
```
### Other Information ###

Downgrading sys-apps/file to the version 5.32 fixes the problem. Also, there is no problem in SDK itself.

**Comment by dm0-** [comment]
Thanks for reporting this.  That particular `file` upgrade was for a security fix, so we will most likely keep it in place: https://security.gentoo.org/glsa/201806-08 .  The problem was that our old portage version was looking for the pattern `SB executable` where the pattern changed to `SB pie executable`.  I have a fix running in test builds for it (namely coreos/coreos-overlay#3311).

**Comment by dm0-** [comment]
I've patched our current portage version in coreos/coreos-overlay#3313 to get it working again instead of upgrading since there are issues to investigate with the new portage version.  I'll close this now that `splitdebug` is functioning again, but please reopen if you still have trouble.
