### ISSUE TITLE
Ignition - Cloud Failure Allowance Mode

### ISSUE THREAD

**Issue by pctj101** [coreos/bugs#2512]
# Issue Report #

## Feature Request ##
When Ignition fails, it crashes the system. In a cloud environment, during development, this severely inhibits debugging.

I would like a way to tell ignition not to crash and give me a debug shell/normal shell for debug instead.

### Environment ###

AWS 

### Desired Feature ###

I propose to add some kind of key/value to ignition to indicate something like

- Log FIRST failure to journal, mark ignition complete, stop, reboot as if ignition complete
- Log Up to X failures to journal, mark ignition complete, stop, reboot as if ignition complete
- Log all failures to journal (may be more harmful than helpful, but hey it all depends!), mark ignition complete, stop, reboot as if ignition complete

### Other Information ###

Example:
```
{ .....,
  debug: {
   maximum_errors: 10
  }
}
```

**Comment by crawford** [comment]
Ignition very explicitly will not allow the machine to boot in the event of a failure. This is so that it never masks a failure.

You can use the online validator to check your config before booting and you can check the AWS console logs to see any errors that occurred. If those aren't sufficient for debugging, we should improve those instead.

**Comment by bgilbert** [comment]
When Ignition fails, Container Linux drops to an emergency shell on the system console which can be used for debugging (e.g. reading the journal).  Unfortunately AWS does not provide interactive access to the system console.

**Comment by ajeddeloh** [comment]
I'm going to close as WONTFIX since as @bgilbert and @crawford have stated, this is antithetical to Ignition's design. If you have ideas on how to make debugging Ignition failures easier without allowing the system to come fully up, I'd love to hear them.

Online validator that @crawford mentioned: https://coreos.com/validate/

There's also the [container linux config transpiler](https://github.com/coreos/container-linux-config-transpiler) that lets you write a config similar to the Ignition config except it's yaml and has sugar for some common operations. It also validates the config as part of the translation process.

**Comment by pctj101** [comment]
@ajeddeloh - I don't have a failure with my syntax as I use CT to generate it and have the JSON validated.  However in many cases, even when the ignition syntax is correct, CoreOS will fail to boot and on AWS without a console is extremely difficult to debug.

I've gotten pretty good at blackbox ignition debugging thanks to this setup, but I have my doubts that my co-workers will find as much success.  

Again I'm not asking for ignition to not-fail during production.  I'm asking for ignition to offer tools to be debuggable in the AWS cloud.

**Comment by arithx** [comment]
You might be able to find some extra information in the console history.

**Comment by pctj101** [comment]
@arithx Thanks a bunch for the tip but when Ignition fails, nothing is left in the AWS console log and it's not possible to scroll upwards.  The maximum information available is a corrupted screen grab.

Let me share with you the maximum available information on AWS when ignition fails:

https://www.evernote.com/l/AE__MLODCjJN_p8vv9G_LkqC2nBnb6BbAqI

That's it :)

So for users of coreos/ignition on a cloud service, it just might be reasonable to consider additional ways of providing debug information.

**Comment by dustymabe** [comment]
> Thanks a bunch for the tip but when Ignition fails, nothing is left in the AWS console log and it's not possible to scroll upwards.

In AWS there also exists the ability to grab the serial console output: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html . I don't remember what the console= kernel command line settings are for CL but you can try that and give it a shot.

**Comment by arithx** [comment]
@pctj101 I was talking about the serial console history that @dustymabe linked. We use that in our test framework (`kola`) to pull information for debugging when tests fail on AWS.

> I don't remember what the console= kernel command line settings are for CL but you can try that and give it a shot.

You shouldn't need to pass anything special on to the command-line on AWS to get serial console logs.
