### ISSUE TITLE
Update libcurl (CVE-2019-3822)

### ISSUE THREAD

**Issue by joelbirchler** [coreos/bugs#2555]
# Issue Report #

## Bug ##

libcurl versions from 7.36.0 to before 7.64.0 are vulnerable to a stack-based buffer overflow.

CVE: [CVE-2019-3822](https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3822)

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1967.6.0
VERSION_ID=1967.6.0
BUILD_ID=2019-02-12-2138
PRETTY_NAME="Container Linux by CoreOS 1967.6.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Expected Behavior ###

Libcurl version >= 7.64.0

### Actual Behavior ###

Libcurl version is 7.61.1

### Reproduction Steps ###

```
$ curl-config --version
libcurl 7.61.1
```

**Comment by bgilbert** [comment]
CVE-2019-3822 affects NTLM authentication, which is disabled by default.  The curl(1) man page says:

```
       --ntlm (HTTP) Enables  NTLM  authentication.  The  NTLM  authentication
              method was designed by Microsoft and is used by IIS web servers.
              It is a proprietary protocol, reverse-engineered by clever  peo‐
              ple and implemented in curl based on their efforts. This kind of
              behavior should not be endorsed, you should  encourage  everyone
              who  uses  NTLM to switch to a public and documented authentica‐
              tion method instead, such as Digest.
```

A fixed version of curl has been merged to master (https://github.com/coreos/portage-stable/pull/711) and will be included in the next Container Linux alpha release.  Because we don't expect the NTLM vulnerabilities (or the SMTP vulnerability also fixed by curl 7.64.0) to affect any code running directly in the host, we don't plan to backport the fixes to the current Container Linux beta or stable releases.
