### ISSUE TITLE
Relationship between AMI CoreOS version and volume's CoreOS version

### ISSUE THREAD

**Issue by joelchen** [coreos/bugs#256]
Dear CoreOS Team,

If the original Amazon Machine Image I used to spawn my instance attached with a EBS volume is CoreOS-alpha-561.0.0-hvm - ami-8c032bde, and with the recent auto-updates it is updated to CoreOS 575, should I be detaching my outdated instance and attach my EBS volume with the latest (CoreOS-alpha-575.0.0-hvm - ami-e0ba91b2) to match my updated OS?

In other words, are there any virtualization or other updates between Amazon AWS and CoreOS I am missing out on by only updating my instance (or in fact it is updating the CoreOS in the attached EBS volume, please correct me if I am wrong) with the latest CoreOS version? Thank you.

Warmest Regards,
Joel

**Comment by marineam** [comment]
Generally there shouldn't be a need to re-create instances from newer AMIs. As you add instances use the latest AMI currently available but no need to worry about existing ones since they are being upgraded automatically.

Only the `/usr` partition is included in updates so there are a few things that will always remain unchanged from the base image but newer `/usr` partitions always remain compatible with older systems. There are a few situations where re-imaging may be useful:
- Switching the root filesystem from btrfs to ext4.
- Updating the bootloader. Over time we have improved our boot process, fixing issues and extending upgrade fallback support to more systems.
- Updating `/usr/share/oem` which provides platform-specific configuration/tools.

Does that cover your question?

**Comment by joelchen** [comment]
Hi @marineam,

Thanks for your reply. If I understand your explanation correctly, do you mean that most of /usr partition is changed by swapping an instance spawned from old AMI (even though it is upgraded to the latest CoreOS version automatically) to a new instance spawned from new AMI, thereby updating what CoreOS might improve in the root filesystem, bootloader, and platform-specific configuration/tools?

By the way, it seems that CoreOS has changed its root filesystem from [1][btrfs to ext4]?

Warmest Regards,
Joel

[1]: https://github.com/coreos/scripts/pull/372

**Comment by marineam** [comment]
During a regular upgrade /usr is updated to the new version (a new copy of that filesystem is fetched and written to disk). Nothing else about the instance changes, it will still report as being created from the old AMI, no other partitions are altered. Since everything needed at runtime is provided by /usr this is normally sufficient.

If you want to switch to a system based on a newer image (say one that now uses ext4 instead of btrfs) you will need to spin up a new instance using a newer AMI.
