### ISSUE TITLE
Please support encrypted drives

### ISSUE THREAD

**Issue by hunger** [coreos/bugs#261]
Please consider to support full disk encryption for the data partition and any additional drives. There are lots of companies that require all _data_ to be held encrypted, so this would help them use coreos.

To do so you would need to add the cryptsetup to the coreos image. That is not too big a package, but annoying to add after the fact since systemd needs cryptsetup installed to enable its support for that. So just adding the package later as a customization is not straight forward (I tried that already;-).

You would also need to support entering a keyphrase during boot. Users in small companies with one or two servers will probably want that. Systemd does support this, so that should not be any additional effort on your side.

For bigger deployments you would want them to be able to send keys as part of cloudconfig. It should not be too hard to turn some cloudconfig key/value pairs into /etc/crypttab so that the boot will proceed without human intervention.

I think that should not be too much effort to implement and would help making coreos acceptable to a wide range of users that currently can not consider your product for legal reasons.

Thank you for considering this suggestion.

**Comment by hunger** [comment]
@kelseyhightower suggested I raise a bug report about this issue at FOSDEM this weekend. It was really interesting talking to Kelsey and Jonathan there. Thanks!

**Comment by lungj** [comment]
@hunger, I just discovered CoreOS last week and am interested in bringing up a small cluster of old machines using it as a host OS. I'd also really like to see FDE as well. While I haven't tried modifying CoreOS (don't have disk space to set up a CoreOS dev environment), I do have an FDE setup that I've got running that you might be able to adapt to your environment.

My boot process:
 - Netboot a node (I do it via HTTPS with iPXE using two-factor authentication to grab both cloud-config and the OS images). Do NOT mount any disks using the `root` kernel flag. At this point, / is a tmpfs mount. Because there are no disks mounted, there's no danger of any data you write to disk will be written to disk (I think).
 - In my cloud-config, I use an entry in the `write_files` section to write the disk encryption key to a file "on disk" (the tmpfs root partition). This ought to be safe since there is no persistent storage for tmpfs to write swap out to.
 - Have a service that attempts to mount /dev/sda using cryptsetup using the key from the previous step as a key file.
 - If a successful mount of btrfs partition in the encrypted /dev/sda occurs, I relocate `/home` and `/root` to a new location, symlink in the counterparts from the encrypted partition, and ensure that the encrypted `/home/core/.ssh/authorized_keys` is symlinked back to the one created by my cloud-init file (otherwise, I can't log in).

Comments/questions/suggestions very much welcome.

**Comment by marineam** [comment]
Just to be clear to the original request: We do include cryptsetup support in CoreOS but currently the initrd will not have any mechanism to get a decryption key other than prompting on the console which isn't useful in many environments using CoreOS. You can add a /etc/crypttab and /etc/fstab to mount additional volumes that are encrypted and you will be able to put together more ways to provide the key that fit your environment. So additional volumes should be fine but the root filesystem is tricky.

**Comment by philhug** [comment]
How about adding support to initrd by creating a random encryption and create a new root file system on every boot?
This should solve the PXE use case for nodes without persistent data.

**Comment by Andrew415** [comment]
Bump. This would be very useful.

**Comment by lungj** [comment]
For anyone that's interested, you can incorporate one of the `btrfs.mount` targets (as appropriate for your RAID level) from https://github.com/SojournLabs/netboot/tree/master/recore.docker/profiles along with the `mount`  and `enc.service` targets from https://github.com/SojournLabs/netboot/tree/master/recore.docker/profiles/bootserver/lib64/systemd/system .

To format your disk and enable LUKS (_warning_: destructive!), use the `reformat.sh` script for your RAID level from here: https://github.com/SojournLabs/netboot/tree/master/recore.docker/profiles.

**Comment by azgazg** [comment]
any news about about full disk encryption?

**Comment by mikefedyk** [comment]
Does anyone have FDE working, setup with ignition?

**Comment by crawford** [comment]
Ignition doesn't support LUKS yet, so encrypting the ROOT filesystem will be tricky. It's possible (and relatively straightforward) to encrypt data partitions, so it depends on what you are trying to get out of full-disk encryption. If you are looking to protect data, using a separate data partition will suffice in most situations. If you are using to protect system integrity, trusted boot and dm-verity (enabled by default) will get you most of the way there.

**Comment by aboyett** [comment]
@crawford your talk listed at https://www.meetup.com/San-Francisco-Kubernetes-Meetup/events/239526761/ seems to indicate progress has been made on rootfs encryption
>Alex Crawford - Disk Encryption using Ignition
>
>Disk encryption has long been a staple of systems security. While possible today in Container Linux, it is a very difficult process and limited to data partition. Ignition aims to improve this situation by making it easier to encrypt partitions and by making it possible to encrypt the root partition.

Is it supported now, or will the talk discuss future developments that will enable Ignition to support encryption?

**Comment by crawford** [comment]
@aboyett uhhhhhhhhhhh, I didn't submit that talk. I'll be covering a completely different topic (what are Container Linux Configs).

> Is it supported now, or will the talk discuss future developments that will enable Ignition to support encryption?

It's still not supported, though we've been experimenting with some designs. The difficult question is "how do we get the secrets _back_ to the box at a later point for decryption?". If you have any suggestions or experience, we'd love to hear your thoughts.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
