### ISSUE TITLE
How to execute linux commad via Ignition

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2619]
# Issue Report #
I want to set iptables.
How can I execute plain linux commands via Ignition

## Feature Request ##
There must be provision to execute linux cmds via Ignition

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by ajeddeloh** [comment]
> How can I execute plain linux commands via Ignition

You can't, by design. Ignition reads a declarative config file that states how the system should be, not commands to get there. Since Ignition only runs on first boot, using commands to start services, load configuration, etc doesn't make sense. Instead Ignition should be used to enable services to run on boot, write configuration that those services read, etc.

> I want to set iptables

The canonical way to do this would be to use Ignition to write a file with those rules and enable the `iptables-restore.service` to load them on boot. Running `systemctl cat iptables-restore.service` on my system shows:
```
[Unit]
Description=Restore iptables firewall rules
# if both are queued for some reason, don't store before restoring :)
Before=iptables-store.service
# sounds reasonable to have firewall up before any of the services go up
Before=network-pre.target
Wants=network-pre.target

[Service]
Type=oneshot
ExecStart=/sbin/iptables-restore -w -- /var/lib/iptables/rules-save

[Install]
WantedBy=basic.target
```

Which shows it's reading from `/var/lib/iptables/rules-save` so you should write the rules there (or wherever they're saved to on your system).

**Comment by alpana17** [comment]
ok
Thanks for clarifying it quickly.
