### ISSUE TITLE
Service to convert binary logs to splunk is getting timeout

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2643]
I created a service to convert binary journal logs to json
Service is:
[Unit]
Description=Convert Binary logs to JSON
[Service]
Type=forking
ExecStartPre=/usr/bin/journalctl --vacuum-size=10M
ExecStart=/bin/bash -c '/usr/bin/journalctl --identifier systemd --identifier sshd --identifier sudo --identifier su --no-tail -f -o json > /var/splunk/journald'
RemainAfterExit=false
[Install]
WantedBy=multi-user.target

When  I start this service, it gives 
Nov 29 07:30:58 ip-123-123-1-217.us-west-2.compute.internal systemd[1]: Starting Convert Binary logs to JSON...
Nov 29 07:30:58 ip-123-123-1-217.us-west-2.compute.internal journalctl[666]: Vacuuming done, freed 0B of archived journals from /var/log/journal/6f56620150354cb380ba8604e32604a8.
Nov 29 07:32:29 ip-123-123-1-217.us-west-2.compute.internal systemd[1]: log-convert.service: Start operation timed out. Terminating.
Nov 29 07:32:29 ip-123-123-1-217.us-west-2.compute.internal systemd[1]: log-convert.service: Control process exited, code=killed, status=15/TERM
Nov 29 07:32:29 ip-123-123-1-217.us-west-2.compute.internal systemd[1]: log-convert.service: Failed with result 'timeout'.
Nov 29 07:32:29 ip-123-123-1-217.us-west-2.compute.internal systemd[1]: Failed to start Convert Binary logs to JSON.

**Comment by lucab** [comment]
This is likely due to the usage of `Type=forking` in your custom service. Please make sure to check systemd documentation when adding your customizations: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=.

Closing the ticket as the service is not one we ship in the base OS.

Additionally, this is a ticket tracker for bugs in the distribution itself. If you have troubles with customizations or doubts about "how to do X", I'd instead recommend to direct them at community forums and docs.

**Comment by alpana17** [comment]
Please share the link of  community forums and docs.
