### ISSUE TITLE
598 Alpha ISO says it's "CoreOS stable"

### ISSUE THREAD

**Issue by SpencerBrown** [coreos/bugs#276]
Downloaded ISO image for CoreOS 598 (coreos_production_iso_image.iso) which is Alpha release channel latest. Burned it to USB and booted it on a bare metal machine.

When it books, the initial message says "CoreOS stable (598.0.0)" with the magenta O and cyan S.

Obviously it should say "alpha" not "stable".

**Comment by crawford** [comment]
It appears as though we have been doing this for quite a while... Let me figure out why this is happening.

**Comment by porjo** [comment]
Same thing happens with 604 ISO image. Also, when I attempt to do a `coreos-install` it attempts to fetch the base image from URL `http://stable.release.core-os.net/amd64-user/604.0.0/..` (which fails)

**Comment by crawford** [comment]
Sorry, I thought I responded to this already. This particular oddity is due to the way that images are generated. The /usr partition contains the default update.conf (/usr/share/coreos/update.conf) which sets the group to "stable". All of our images share the same /usr layout which means, by default, they all have the group set to "stable". During the build process, `image_set_group` clobbers /etc/coreos/update.conf with the desired group. The ISO and PXE images are diskless however, and only include /usr (as a squashfs) and therefore don't have this new update.conf.

It might make sense to ship a modified /usr in diskless images (since they aren't going to update anyway).

**Comment by SpencerBrown** [comment]
![]()))

**Comment by SpencerBrown** [comment]
porjo, I did not have this problem of coreos-install trying to download from a bogus URL. 

What options did you use on coreos-install?  I used -C alpha and it gave me the right image.
