### ISSUE TITLE
Override DNS resolvers sent via DHCP

### ISSUE THREAD

**Issue by porjo** [coreos/bugs#289]
I've tried disabling `systemd-resolved` using `systemctl disable systemd-resolved` however every time my VM boots, the service has been re-enabled!? I want to disable it as I'd like to use statically assigned DNS resolvers, rather than getting them via DHCP.

My static network config is as follows:
```ini
      [Match]
      Name=eth0

      [Network]
      DHCP=no
      DNS=8.8.8.8
      DNS=8.8.4.4

      [Route]
      Gateway=x.x.x.1

      [Address]
      Address=x.x.x.x/18

      [DHCP]
      UseDNS=false
```

I added `DHCP=no` and `UseDNS=false` afterwards, but that hasn't made any difference: `resolve.conf` is still being populated with DNS resolvers from DHCP.

Using alpha 607.0.0. My Cloud provider is DigitalOcean.

**Comment by robszumski** [comment]
I think you want `systemctl mask systemd-resolved`.

"Masking a service prevents the service from being started manually or automatically"

**Comment by porjo** [comment]
@robszumski thanks that did the trick. 

Unfortunately now `resolv.conf` is missing altogether which isn't quite what I had in mind. I guess my question really is: how do I auto-create resolv.conf from network config but override DNS resolvers with static entries?

**Comment by crawford** [comment]
@porjo DigitalOcean has a very odd networking setup. DHCP is unfortunately not used. The network configuration is instead provided via a metadata service. coreos-cloudinit is responsible for converting that information into network units. It will put this config under /run/systemd/network. I suspect that that config is taking precedence over yours. You should be able to give your network unit the same name as the dynamically generated unit in order to override it's behavior.

**Comment by bobymicroby** [comment]
Hi @porjo . 
Did you find a way to override the DNS properly on DO, and if so, do you care to share ?
B.

**Comment by crawford** [comment]
@bobymicroby you can remove the `/etc/resolv.conf` symlink and replace it with a regular file with your desired nameservers.
