### ISSUE TITLE
CoreOS VM losing networking after reboot

### ISSUE THREAD

**Issue by geauxvirtual** [coreos/bugs#329]
I've been using an older version of CoreOS (522) for the longest time as a dev VM on my laptop without issue. Recently, I've updated the laptop to OS X 10.10.3, Parallels 10.2, and updated the VM to CoreOS 647.0.0. After these updates, I noticed my VM lost IPv4 connectivity after the laptop was put to sleep (VM was paused). I built a new VM and I noticed the VM lost network connectivity after a reboot following first boot. I've tried both 653.0.0 and back to 522.0.0 with same results, which makes me thinks this is outside of CoreOS unless I have an issue in my cloud-config. I've download VMware Fusion 7 Pro with same results. I have a Windows 7 image that this does not occur with in Parallels. I'm currently attempting to install Ubuntu 14.10 to see if this is linux specific or not.

Here is a link to the cloud-config I'm currently using to configure the server during installation.

https://gist.github.com/geauxvirtual/a99a98c079dbca670227

**Comment by marineam** [comment]
The `nameservers.network` is your issue: https://gist.github.com/geauxvirtual/a99a98c079dbca670227#file-config-yml-L38

That is matching all network interfaces and configuring nameservers for it but using an empty network configuration. Things happen to work on first boot because the config is getting dropped in after DHCP has already configured your interface. When networkd is restarted with the new configuration it does not bother clearing the IP addresses previously set. So any event that takes the interface down completely (vmware tools does this when suspending) or a reboot of an existing instance will have similar results.

You will want to include a full configuration that includes your nameservers. The default configs for vmware and non-vmware systems can be found here: https://github.com/coreos/init/tree/master/systemd/network

Alternatively, drop the use of .network configs and just replace the /etc/resolv.conf symlink with a regular file containing your own settings. Nothing will overwrite or modify /etc/resolv.conf if it is a regular file.

**Comment by geauxvirtual** [comment]
Thanks for the assistance.
