### ISSUE TITLE
BareMetal - discovery url

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#432]
_From @tdeheurles on August 10, 2015 10:26_

I have problem with a `baremetal CoreOS` to connect to `discovery url`.

here is my etcd2 configuration :
```
etcd2:
    name: tdeheurles-bm-coreos
    listen-peer-urls: http://192.168.1.6:2380
    listen-client-urls: http://0.0.0.0:2379
    initial-advertise-peer-urls: http://192.168.1.6:2380
    advertise-client-urls: http://192.168.1.6:2379
    discovery: https://discovery.etcd.io/b9371c90aa85773de23c3c3eb52a60b9
```

What I don't understand is that this configuration work with a vagrant VM.  
I can see the VM registred at the discovery url.

PS: this discovery url is out of date

_Copied from original issue: coreos/docs#558_

**Comment by crawford** [comment]
Do you have logs for this failure?

**Comment by tdeheurles** [comment]
Sorry, question without question ...

I worked on that this evening and my problem as evolved. If it can help others, I have written the first part of my problem and how to resolve it after.

## baremetal problem

I change the configuration of my baremetal very often for my tests.  
For that I create a new `cloud-config` and copy/paste it to `/var/lib/coreos-install/user_data`

But doing that, I just understand tonight with this log :  `discovery token ignored since a cluster has already been initialized. Valid log found at "/var/lib/etcd2/member/wal"`.

I have just `deleted directory wal and snap` and then restarted. But for now `the etcd2 can't restart` (deleting was maybe not the good way to do that :p)

```bash
Aug 10 23:02:11 barebone-coreos systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 23:02:11 barebone-coreos systemd[1]: etcd2.service: Unit entered failed state.
Aug 10 23:02:11 barebone-coreos systemd[1]: etcd2.service: Failed with result 'exit-code'.
Aug 10 23:02:22 barebone-coreos systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Aug 10 23:02:22 barebone-coreos systemd[1]: Started etcd2.
Aug 10 23:02:22 barebone-coreos systemd[1]: Starting etcd2...
Aug 10 23:02:22 barebone-coreos systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 23:02:22 barebone-coreos systemd[1]: etcd2.service: Unit entered failed state.
Aug 10 23:02:22 barebone-coreos systemd[1]: etcd2.service: Failed with result 'exit-code'.
```


## Initial problem (solved on virtual machine)
This problem came from the size for my discover url. I requested a size 3 and try `etcdctl ls` before the 3 nodes made the raft.

Here is the error : 
`Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379`

I tried to add `http://127.0.0.1:2379` to `listen-client-urls` but does solve the problem.
`etcdctl ls` take a while to respond that : `Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379`
Then, every next try is directly the same response (without the wait time).

Here is the `journalctl` log for etcd2 :
```
Aug 10 19:10:22 tdeheurles1-vm-core systemd[1]: Started etcd2.
Aug 10 19:10:22 tdeheurles1-vm-core systemd[1]: Starting etcd2...
Aug 10 19:10:22 tdeheurles1-vm-core etcd2[703]: 2015/08/10 19:10:22 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
Aug 10 19:10:22 tdeheurles1-vm-core etcd2[703]: 2015/08/10 19:10:22 etcdmain: listen tcp 192.168.1.17:2380: bind: cannot assign requested address
Aug 10 19:10:22 tdeheurles1-vm-core systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 19:10:22 tdeheurles1-vm-core systemd[1]: etcd2.service: Unit entered failed state.
Aug 10 19:10:22 tdeheurles1-vm-core systemd[1]: etcd2.service: Failed with result 'exit-code'.
Aug 10 19:10:32 tdeheurles1-vm-core systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Aug 10 19:10:32 tdeheurles1-vm-core systemd[1]: Started etcd2.
Aug 10 19:10:32 tdeheurles1-vm-core systemd[1]: Starting etcd2...
Aug 10 19:10:32 tdeheurles1-vm-core etcd2[833]: 2015/08/10 19:10:32 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
Aug 10 19:10:32 tdeheurles1-vm-core etcd2[833]: 2015/08/10 19:10:32 etcdmain: listening for peers on http://192.168.1.17:2380
Aug 10 19:10:32 tdeheurles1-vm-core etcd2[833]: 2015/08/10 19:10:32 etcdmain: listening for client requests on http://127.0.0.1:2379
Aug 10 19:10:32 tdeheurles1-vm-core etcd2[833]: 2015/08/10 19:10:32 etcdmain: listening for client requests on http://192.168.1.17:2379
Aug 10 19:10:35 tdeheurles1-vm-core etcd2[833]: 2015/08/10 19:10:35 discovery: found self ae0d24e5cffb77bf in the cluster
Aug 10 19:10:35 tdeheurles1-vm-core etcd2[833]: 2015/08/10 19:10:35 discovery: found 1 peer(s), waiting for 2 more
Aug 10 19:11:34 tdeheurles1-vm-core systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 19:11:34 tdeheurles1-vm-core systemd[1]: etcd2.service: Unit entered failed state.
Aug 10 19:11:34 tdeheurles1-vm-core systemd[1]: etcd2.service: Failed with result 'exit-code'.
Aug 10 19:11:44 tdeheurles1-vm-core systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
[...]
```

The discoveryUrl was request for a size of 3.

The relevant parts are :
```
etcd2[703]: 2015/08/10 19:10:22 etcdmain: listen tcp 192.168.1.17:2380: bind: cannot assign requested address
```
just followed by :
```
etcd2[833]: 2015/08/10 19:10:35 discovery: found self ae0d24e5cffb77bf in the cluster
Aug 10 19:10:35 tdeheurles1-vm-core etcd2[833]: 2015/08/10 19:10:35 discovery: found 1 peer(s), waiting for 2 more
Aug 10 19:11:34 tdeheurles1-vm-core systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
```

It tests for 1 minute and then fail.  

### so ...
Requesting a discovery URL for a "cluster" of 1 node solved the ptoblem.

**My feeling here is that you can't use etcdctl during the discovery part**  
Maybe we can add a little note about that in the documentation.

**Comment by tdeheurles** [comment]
I have re-installed the baremetal coreos this morning and it had connected to the `1 node ''cluster''`

The problem was coming from the misunderstanding of the size of the DiscoveryUrl :  
- Trying `etcdctl ls` on a cluster that didn't reach the `size` of the new discovery url create an error
- Trying to restart coreos with a different cloud-config in `/var/lib/coreos-install/user_data` does not reconfigure etcd as it finds a save of the previous cluster in `/var/lib/etcd2/member/wal`

I didn't find how to delete the coreos etcd configuration for now.

Here are working parameters :
```
coreos:
  etcd2:
    name: bm0-coreos
    listen-peer-urls: http://192.168.1.13:2380
    listen-client-urls: http://192.168.1.13:2379, http://127.0.0.1:2379
    initial-advertise-peer-urls: http://192.168.1.13:2380
    advertise-client-urls: http://192.168.1.13:2379
    discovery: https://discovery.etcd.io/9c216d6d409b88c........
```
And resolve the discovery cluster size before trying to use etcd

**Comment by robszumski** [comment]
If you want to blow away the old cluster:

1. Change your cloud-config as you describe by editing the user_data on disk. Be sure to use a new discovery url with the correct size
2. Stop etcd2 with `sudo systemctl stop etcd2`
3. Remove /var/lib/etcd2/* to delete the state on disk
4. Reboot the machine

Your new cloud-config should have been processed on boot and etcd should be using the new discovery url.

**Comment by tdeheurles** [comment]
**Cool, Works fine. Thank you.**
