### ISSUE TITLE
etcd2 is not starting correctly after CoreOS reboot 

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#438]
_From @christ0pher on August 13, 2015 11:30_

Hi,

we have a cluster running on aws with a custom cloud-config. Everytime we reboot one of the servers etcd2 is not initialised correctly, because it is started before the network is up and running.
```
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Started etcd2.
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Starting etcd2...
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Started Configure Addon /usr/share/oem.
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Starting Update Engine...
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Starting Login Service...
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Starting Generate /run/issue...
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Started Serial Getty on ttyS0.
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Starting Serial Getty on ttyS0...
Aug 13 10:07:09 ip-172-31-54-202.ec2.internal systemd[1]: Started D-Bus System Message Bus.
Aug 13 10:07:10 ip-172-31-54-202.ec2.internal dbus[480]: [system] Successfully activated service 'org.freedesktop.systemd1'
Aug 13 10:07:10 ip-172-31-54-202.ec2.internal systemd[1]: Starting D-Bus System Message Bus...
Aug 13 10:07:10 ip-172-31-54-202.ec2.internal systemd[1]: Starting Network Service...
Aug 13 10:07:10 ip-172-31-54-202.ec2.internal systemd[1]: Started Modifies /etc/environment for CoreOS.
Aug 13 10:07:10 ip-172-31-54-202.ec2.internal systemd[1]: Started Load cloud-config from url defined in /proc/cmdline.
Aug 13 10:07:10 ip-172-31-54-202.ec2.internal systemd[1]: Starting Load cloud-config from /usr/share/oem/cloud-config.yml...
```
One solution might be to just add:
```
Requires=network-online.target
After=network-online.target
```
To the etcd2-unit-file. 

Best,
Chris

_Copied from original issue: coreos/coreos-overlay#1460_

**Comment by crawford** [comment]
Let's move this to the correct repo.

**Comment by crawford** [comment]
It looks like you've included `enable: true` under the etcd2 service. You just need to get rid of that.

When the etcd2 service is enabled, it will start up with multi-user.target. coreos-cloudinit writes the temporary config potentially after etcd2 has started. The solution is to add a dependency from etcd2 on oem-cloudinit or to just let coreos-cloudinit start the service.

**Comment by christ0pher** [comment]
Ok. Thanks! But the cloudinit on aws just contains:
```
units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
```
I added a drop-in with:
```
write_files:
    - path: /run/systemd/system/etcd2.service.d/01-start-after-network.conf
      owner: root:root
      permissions: 0644
      content: |
        [Unit]
        Requires=network-online.target multi-user.target
        After=network-online.target multi-user.target
```
This works fine and starts all services in the correct order!

**Comment by crawford** [comment]
I suspect this works because you are starting etcd2 after multi-user.target. Can you check to see if the service is enabled (`systemctl is-enabled etcd2`)? If it's not enabled, it may be a dependency of something that is enabled. You can test with `systemctl list-dependencies etcd2 --reverse`.

As a side note, unit drop-ins can be written via the unit section of your cloud-config:

```yaml
#cloud-config
coreos:
  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 01-start-after-network.conf
          content: |
            [Unit]
            Requires=network-online.target multi-user.target
            After=network-online.target multi-user.target
```

**Comment by christ0pher** [comment]
Hi, sorry for the late response here are the dependencies. On core 717.3.0:
etcd2.service
● ├─authentication.3.service
● ├─delivery.3.service
● ├─events.3.service
● ├─gastro_container.1.service
● ├─google_maps_api.1.service
● ├─guestresponder.2.service
● ├─images.1.service
● ├─roses_container.3.service
● ├─seabeach_container.3.service
● ├─skydns.service
● ├─static.2.service
● ├─template.3.service
● └─user-profile.2.service
And on 723.3.0:
etcd2.service
● ├─blackhawk_container.2.service
● ├─delivery.1.service
● ├─gastro_container.2.service
● ├─greenfinch_container.3.service
● ├─guestresponder.1.service
● ├─images.3.service
● ├─responder_basic.1.service
● ├─seabeach_container.2.service
● ├─skydns.service
● ├─static.3.service
● ├─template.1.service
● ├─user-profile.1.service
● └─web-skeleton.3.service

**Comment by crawford** [comment]
Are any of those services enabled? Is etcd itself enabled?

Can I also see the journal for etcd2?

**Comment by christ0pher** [comment]
The services itsself look like:
[Unit]
Description=Service-Monitor
After=docker.service etcd2.service
Requires=etcd2.service skydns.service
Wants=service-monitor-sidekich@%i.service
[Service]
User=mycroft
EnvironmentFile=/etc/environment
RestartSec=60
Restart=always
ExecStartPre=-/usr/bin/docker kill yp-service-mon-%i
ExecStartPre=-/usr/bin/docker rm yp-service-mon-%i
ExecStartPre=-/usr/bin/docker pull youpooly/service-monitor:live
ExecStartPost=/usr/bin/etcdctl set /skydns/local/skydns/youpooly/dev/service-monitor/%i '{"host":"${COREOS_PRIVATE_IPV4}", "port": 21000}' --ttl 60
ExecStart=/usr/bin/docker run -p ${COREOS_PRIVATE_IPV4}:21000:13000 --dns=${COREOS_PRIVATE_IPV4} --name yp-service-mon-%i -h yp-service-mon-%i youpooly/service-monitor:live
ExecStop=/usr/bin/docker stop yp-service-mon-%i
[Install]
WantedBy=multi-user.target
[X-Fleet]
Conflicts=service-monitor@*.service

etcd2-journal:
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal systemd[1]: Started etcd2.
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal systemd[1]: Starting etcd2...
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcd: already initialized as member before, starting as etcd member...
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcd: listening for peers on http://localhost:2380
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcd: listening for peers on http://localhost:7001
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcd: listening for client requests on http://localhost:2379
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcd: listening for client requests on http://localhost:4001
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: datadir is valid for the 2.0.1 format
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: recovered store from snapshot at index 22422482
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: name = ec2eb03e4df74837b232dbcd834178e7
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: data dir = /var/lib/etcd2
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: member dir = /var/lib/etcd2/member
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: heartbeat = 100ms
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: election = 1000ms
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: snapshot count = 10000
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: loaded cluster information from store: 00c8fd0e10f942c2a6128e70631ce961=http://172.31.
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 etcdserver: restart member e01903d220333951 in cluster 70450803ad4f8399 at commit index 22429549
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 raft: e01903d220333951 became follower at term 431314
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:47 raft: newRaft e01903d220333951 [peers: [17337947880c8e54,60cd5e3d153ed2ec,6840b72db6963f2d,90ba9d7
Aug 10 15:33:47 ip-172-31-55-105.ec2.internal systemd[1]: Started etcd2.
Aug 10 15:33:48 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:48 raft: e01903d220333951 is starting a new election at term 431314
Aug 10 15:33:48 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:48 raft: e01903d220333951 became candidate at term 431315
Aug 10 15:33:48 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:48 raft: e01903d220333951 received vote from e01903d220333951 at term 431315
Aug 10 15:33:48 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:48 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 60cd5e3d153ed2ec at
Aug 10 15:33:48 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:48 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 6840b72db6963f2d at
Aug 10 15:33:48 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:48 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 90ba9d7d3aa92c07 at
Aug 10 15:33:48 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:48 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to d536f2f995b7dd35 at
Aug 10 15:33:48 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:48 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 17337947880c8e54 at
Aug 10 15:33:50 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:50 raft: e01903d220333951 is starting a new election at term 431315
Aug 10 15:33:50 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:50 raft: e01903d220333951 became candidate at term 431316
Aug 10 15:33:50 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:50 raft: e01903d220333951 received vote from e01903d220333951 at term 431316
Aug 10 15:33:50 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:50 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 90ba9d7d3aa92c07 at
Aug 10 15:33:50 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:50 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to d536f2f995b7dd35 at
Aug 10 15:33:50 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:50 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 17337947880c8e54 at
Aug 10 15:33:50 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:50 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 60cd5e3d153ed2ec at
Aug 10 15:33:50 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:50 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 6840b72db6963f2d at
Aug 10 15:33:51 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:51 raft: e01903d220333951 is starting a new election at term 431316
Aug 10 15:33:51 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:51 raft: e01903d220333951 became candidate at term 431317
Aug 10 15:33:51 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:51 raft: e01903d220333951 received vote from e01903d220333951 at term 431317
Aug 10 15:33:51 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:51 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 90ba9d7d3aa92c07 at
Aug 10 15:33:51 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:51 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to d536f2f995b7dd35 at
Aug 10 15:33:51 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:51 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 17337947880c8e54 at
Aug 10 15:33:51 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:51 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 60cd5e3d153ed2ec at
Aug 10 15:33:51 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:51 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 6840b72db6963f2d at
Aug 10 15:33:52 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:33:52 etcdserver: publish error: etcdserver: request timed out

Then lots of this election stuff (etcd listening only on localhost). Manually stopping and starting:

Aug 10 15:37:09 ip-172-31-55-105.ec2.internal etcd2[472]: 2015/08/10 15:37:09 raft: e01903d220333951 [logterm: 431314, index: 22429549] sent vote request to 90ba9d7d3aa92c07 at
Aug 10 15:37:09 ip-172-31-55-105.ec2.internal systemd[1]: Stopping etcd2...
Aug 10 15:37:09 ip-172-31-55-105.ec2.internal systemd[1]: Stopped etcd2.
Aug 10 15:37:14 ip-172-31-55-105.ec2.internal systemd[1]: Started etcd2.
Aug 10 15:37:14 ip-172-31-55-105.ec2.internal systemd[1]: Starting etcd2...
Aug 10 15:37:14 ip-172-31-55-105.ec2.internal systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 15:37:14 ip-172-31-55-105.ec2.internal systemd[1]: etcd2.service: Unit entered failed state.
Aug 10 15:37:14 ip-172-31-55-105.ec2.internal systemd[1]: etcd2.service: Failed with result 'exit-code'.
Aug 10 15:37:25 ip-172-31-55-105.ec2.internal systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Aug 10 15:37:25 ip-172-31-55-105.ec2.internal systemd[1]: Started etcd2.
Aug 10 15:37:25 ip-172-31-55-105.ec2.internal systemd[1]: Starting etcd2...
Aug 10 15:37:25 ip-172-31-55-105.ec2.internal systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 15:37:25 ip-172-31-55-105.ec2.internal systemd[1]: etcd2.service: Unit entered failed state.
Aug 10 15:37:25 ip-172-31-55-105.ec2.internal systemd[1]: etcd2.service: Failed with result 'exit-code'.
Aug 10 15:37:31 ip-172-31-55-105.ec2.internal systemd[1]: Stopped etcd2.
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal systemd[1]: Started etcd2.
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal systemd[1]: Starting etcd2...
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcd: already initialized as member before, starting as etcd member...
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcd: listening for peers on http://172.31.55.105:2380
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcd: listening for peers on http://172.31.55.105:7001
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcd: listening for client requests on http://0.0.0.0:2379
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcd: listening for client requests on http://0.0.0.0:4001
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: datadir is valid for the 2.0.1 format
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: discovery token ignored since a cluster has already been initialized. Valid log found 
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: recovered store from snapshot at index 22422482
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: name = ec2eb03e4df74837b232dbcd834178e7
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: data dir = /var/lib/etcd2
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: member dir = /var/lib/etcd2/member
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: heartbeat = 100ms
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: election = 1200ms
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: snapshot count = 10000
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: discovery URL= https://discovery.etcd.io/6533e2ed1944dcec568d69d7794358d8
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: advertise client URLs = http://172.31.55.105:2379,http://172.31.55.105:4001
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: loaded cluster information from store: 00c8fd0e10f942c2a6128e70631ce961=http://172.31.
Aug 10 15:39:04 ip-172-31-55-105.ec2.internal etcd2[892]: 2015/08/10 15:39:04 etcdserver: restart member e01903d220333951 in cluster 70450803ad4f8399 at commit index 22429549

etcd is not enabled. at least not in the cloud-config.

**Comment by crawford** [comment]
Again, are any of those services (which have a dependency on etcd2) enabled on your system? You need to ask systemd directly.
