### ISSUE TITLE
Error pulling: too many links

### ISSUE THREAD

**Issue by jvassev** [coreos/bugs#474]
I am constantly starting images which differ only in the last 2 layers (CI scenario). After a few days of docker run/stop/rm (done using docker-compose 1.3.3) I start getting this error:
Creating jvassevci134oumq_scripthost_1...75d283ae9112dbe3348c469badc25c045e90bd9-python-iniparse-0.4-9.el7-noarch/installed_by: too many links
Error pulling image (ci-134) from IMAGE, link /var/lib/docker/overlay/c1ffdfb9ecd3629f3eb60a2f80ff9da32333f4c476ed95cd8b95ba0024f1f537/root/var/lib/yum/yumdb/p/575d283ae9112dbe3348c469badc25c045e90bd9-python-iniparse-0.4-9.el7-noarch/installed_by /var/lib/docker/overlay/37d7e6a2378d457e832bd35efe837e58d53ed37062b4dd52f8f9d4e5478bb6ba/tmproot220122062/var/lib/yum/yumdb/p/575d283ae9112dbe3348c469badc25c045e90bd9-python-iniparse-0.4-9.el7-noarch/installed_by: too many links

At a certain point in time there are more than 100 images (tags) known to docker that share about 15 layers.
I am running https://github.com/spotify/docker-gc to garbage collect images which solves the problem. 
If I run it too often then I cannot leverage layer reuse which leads to slower pulls - a lose-lose situation

Meanwhile, I can pull other unrelated images (like ubuntu) and run them. 
It could be a docker issue or overlayfs. Am I hitting a hard limit in overlayfs? Is it possible to tweak the filesystem so it survives at least a week (~150 tags) without the need for gc?

```
Environement:

cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=766.3.0
VERSION_ID=766.3.0
BUILD_ID=
PRETTY_NAME="CoreOS 766.3.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

df- hi
Filesystem     Inodes IUsed IFree IUse% Mounted on
devtmpfs         996K   394  995K    1% /dev
tmpfs            999K     1  999K    1% /dev/shm
tmpfs            999K   905  998K    1% /run
tmpfs            999K    14  999K    1% /sys/fs/cgroup
/dev/sda9        9.4M 1014K  8.4M   11% /
/dev/sda4        254K  4.5K  250K    2% /usr
/dev/sda1           0     0     0     - /boot
tmpfs            999K     1  999K    1% /media
tmpfs            999K     9  999K    1% /tmp
/dev/sda6         32K   113   32K    1% /usr/share/oem


ls -l /var/lib/docker/
total 196
drwx------  24 root root  4096 Sep 15 06:48 containers
drwx------   4 root root  4096 Sep  8 17:53 devicemapper
drwx------ 553 root root 65536 Sep 15 06:55 graph
drwx------   2 root root  4096 Sep  9 13:20 init
-rw-r--r--   1 root root 13312 Sep 15 06:48 linkgraph.db
drwx------ 596 root root 69632 Sep 15 06:55 overlay
-rw-------   1 root root  9418 Sep 15 06:55 repositories-overlay
drwx------   2 root root  4096 Sep  8 17:55 tmp
drwx------   2 root root  4096 Sep  8 17:55 trust
drwx------   3 root root  4096 Sep  8 17:57 vfs
drwx------   4 root root  4096 Sep 15 06:48 volumes

docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 2c2c52b-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 2c2c52b-dirty
OS/Arch (server): linux/amd64

```

**Comment by mischief** [comment]
@jvassev i assume that your /dev/sda9 is ext4. i briefly looked at the overlayfs source, and didn't see anywhere that EMLINK (too many links) would be issued. ext4 seems to have a limit of 65000 links, but it's hard to believe you hit that limit with your number of docker images.

have you tried a different driver for docker, such as devicemapper or btrfs?

**Comment by vcaputo** [comment]
Related: https://github.com/coreos/bugs/issues/264

The layers aren't assembled by docker using overlayfs, those are being constructed using hard-link farms.  65000 seems unlikely given the numbers mentioned above, you can confirm with a `find -inum $inode_of_installed_by` and see which/how many names refer to that inode.  Maybe there's a leak or some other bug to be uncovered there.

If it turns out to be legitimate, your use case may be better served by docker on btrfs at this time.

XFS does support more hard links than ext4, but I'm uncertain on its suitability to overlayfs use.

**Comment by delbaeth** [comment]
I am getting the same error and have been for a few months.
I run something like this:

 docker rmi $(docker images | grep "<none>" | awk ' { print $3} ')

and then the pull will work.

I am also running 766.3.0 but this has been happening for a few version upgrades at least.

df:

Filesystem      1K-blocks     Used Available Use% Mounted on
devtmpfs          8205828        0   8205828   0% /dev
tmpfs             8219076        0   8219076   0% /dev/shm
tmpfs             8219076      600   8218476   1% /run
tmpfs             8219076        0   8219076   0% /sys/fs/cgroup
/dev/vda9      1013510092 34121048 937466376   4% /
/dev/vda4         1007760   398616    557128  42% /usr
tmpfs             8219076        0   8219076   0% /tmp
tmpfs             8219076        0   8219076   0% /media
/dev/vda1          130798    58258     72540  45% /boot
/dev/vda6          110576       56    101348   1% /usr/share/oem

mount:

sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=8205828k,nr_inodes=2051457,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
/dev/vda9 on / type ext4 (rw,relatime,data=ordered)
/dev/vda4 on /usr type ext4 (ro,relatime)
tmpfs on /tmp type tmpfs (rw)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
tmpfs on /media type tmpfs (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
systemd-1 on /boot type autofs (rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
/dev/vda1 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
/dev/vda6 on /usr/share/oem type ext4 (rw,nodev,relatime,commit=600,data=ordered)

**Comment by delbaeth** [comment]
So it does look like there are actually 65000 links when this happens.  I recently ran a cleanup so there are only 35260 at the moment but it will rise as new images are downloaded.  Effectively it comes down to yum using the same filename with the same contents a lot.

sh-4.2# stat checksum_type
  File: 'checksum_type'
  Size: 6         	Blocks: 8          IO Block: 4096   regular file
Device: fe09h/65033d	Inode: 13550       Links: 35260
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-09-16 17:28:48.000000000 +0000
Modify: 2015-03-04 12:44:36.000000000 +0000
Change: 2015-09-16 22:32:02.000000000 +0000
 Birth: -

So "Links" is 35260 and the inode is 13550.

I then did the "find . -inum 13550" and actually found more than the
35260 files because more images have been downloaded.  All of the files were named
"checksum_type".  They all lived in a subdirectory of "yumdb" and for every one I checked
they all had the same contents "sha256".

It appears that yumdb has one of these checksum_type files for every rpm installed and
every layer has a yumdb so we end up with a bit of a combinatorial explosion.

I assume something is noticing that the contents of the files are identical and using
a hardlink instead of a copy.   When there are actually 65000 files with the same
contents we end up hitting the hardlink limit for ext4.

**Comment by jvassev** [comment]
This seems using hard-links are the default behaviour of yum since 3.2.28: http://yum.baseurl.org/wiki/whatsnew/3.2.28
So neither coreos nor docker issue I guess.

**Comment by delbaeth** [comment]
The fact that the yumdb hardlinks can span multiple layers may
be something to think about though.

**Comment by crawford** [comment]
Dup of https://github.com/coreos/bugs/issues/285.

**Comment by mimmus** [comment]
Issue still present on 1010.6.0.
