### ISSUE TITLE
Add conntrack-tools

### ISSUE THREAD

**Issue by polarina** [coreos/bugs#485]
Can the tools provided by the `conntrack-tools` package be added?

**Comment by mischief** [comment]
@polarina is it possible to simply use conntrack-tools in a container?

**Comment by polarina** [comment]
@mischief: that seems to be work when running with `--privileged=true --net=host`.

**Comment by wmark** [comment]
Unfortunately this needs a container engine to be up and running. But `conntrack` is needed before that. For example, for containers that emit UDP. (Here's an example [usage in Kubernetes](https://github.com/kubernetes/kubernetes/pull/32561/files).)

**Comment by euank** [comment]
@wmark Does it need to run before Docker due to docker's bridge creation behaviour, or some other reason? If the appropriate flags are passed to dockerd such that it doesn't create a bridge, then a `--net=host` container shouldn't create anything either and the bridge can be created after the fact.

Regardless, if it's just related to how dockerd creates/manipulates interfaces/iptables, then using rkt could help.

I created a script named `conntrack` on my Container Linux machine with the following contents:

```shell
#!/bin/sh

set -e

uuid=$(mktemp)
rkt run --uuid-file-save="${uuid}" \
  --net=host \
  --interactive \
  --insecure-options=image,ondisk \
  docker://euank/conntrack:8b4a394 \
  --caps-retain=CAP_NET_ADMIN \
  --exec=conntrack -- \
  $@

rkt rm --uuid-file="${uuid}" &>/dev/null || true
```

After adding it to my path, I could run `sudo conntrack -D -p udp --dport 80` and get the expected `conntrack v1.4.4 (conntrack-tools): 0 flow entries have been deleted.`, without requiring any network bridge to be created or any bulky container engine to be downloaded (though note, the `rkt image fetch` should be done out-of-band probably).

Also, specifically for the Kubernetes case, we recommend running the kubelet in a chroot (via rkt fly currently) which provides the necessary tools, including conntrack. That accomplishes something not too-dissimilar to the above.

**Comment by mikenorgate** [comment]
Apologies for resurrecting this thread. From my understanding of reading a few other posts online `conntrack` is required by Kubernetes to manage UDP routing. Is the approach suggested by @euank still the recommended way of making the tool available in CoreOS?

**Comment by integrii** [comment]
`docker run --net=host --privileged --rm claesjonsson/conntrack -S`
