### ISSUE TITLE
boot with tmpfs when Label or UUID is not found

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#690]
<a href="https://github.com/f0"><img src="https://avatars.githubusercontent.com/u/1117435?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [f0](https://github.com/f0)**
_Friday May 16, 2014 at 08:11 GMT_
_Originally opened as https://github.com/coreos/bootengine/issues/34_

---

Hi,

atm when a  flag to the initrd is provided to boot from e.g the disk with label root
root=LABEL=root, and this disk is not found, whyever the the boot breaks and dropts in the emergency shell.

It would be nice to boot  with a tmpfs in this case, this would make the process for pxe boots so much simpler, as i can create all pxe files  with root=LABEL=ROOT, and do not need a 2 step process.

maybe the rootfallback  option an be used 

http://man7.org/linux/man-pages/man7/dracut.cmdline.7.html

regards f0

**Comment by marineam** [comment]
Making sure rootfallback to works seems reasonable. It would certainly need to be an explicit request because a system coming up stateless when it shouldn't could lead to more confusing issues than a system that fails to boot. Given the awkward implementation of dracut's systemd support it may be tricky though.

Once that is in place then yes users could use it to automatically provision a machine if ROOT cannot be found but I could only recommend that for a deployment where it is absolutely safe for the system disk to get wiped at any time in response to an error.

**Comment by crawford** [comment]
This implicit behavior seems like a bad idea for many of the reasons @marineam mentioned. I'm going to pass on this idea.
