### ISSUE TITLE
Units submitted with fleetctl hang in "not-found" state

### ISSUE THREAD

**Issue by marceldegraaf** [coreos/bugs#8]
From time to time (and randomly) a unit that has been destroyed and then re-submitted with `fleetctl` will hang in a `not-found` state. The workflow looks like this:

1. Submit a unit with `fleetctl submit`, observe it does not start and is in `not-found` state
2. Destroy the unit with `fleetctl destroy`, confirm the unit is gone with `fleetctl list-units`
3. Re-submit the unit with `fleetctl submit`
4. Observe it is again stuck in `not-loaded` state. `fleetctl status` shows old log entries

The output of `fleetctl status` looks like this:

```
● sinatra@5000.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Sat 2014-04-26 13:43:53 UTC; 7min ago
 Main PID: 6449 (code=exited, status=255)

Apr 26 13:43:53 core-01 systemd[1]: Stopping sinatra...
Apr 26 13:43:53 core-01 docker[7034]: sinatra-5000
Apr 26 13:43:53 core-01 systemd[1]: sinatra@5000.service: main process exited, code=exited, status=255/n/a
Apr 26 13:43:53 core-01 systemd[1]: sinatra@5000.service: control process exited, code=exited status=4
Apr 26 13:43:53 core-01 systemd[1]: Stopped sinatra.
Apr 26 13:43:53 core-01 etcdctl[7048]: Error: 100: Key not found (/app) [23975]
Apr 26 13:43:53 core-01 systemd[1]: Unit sinatra@5000.service entered failed state.
Apr 26 13:46:59 core-01 systemd[1]: Stopped sinatra@5000.service.
Apr 26 13:47:07 core-01 systemd[1]: Stopped sinatra@5000.service.
Apr 26 13:51:04 core-01 systemd[1]: Stopped sinatra@5000.service.
```

Note that the time is "7min ago", although this unit was submitted a few seconds before using `fleetctl status`. Also note the timestamps in the unit output. The output seems to contain output of a previous version of the unit, which was destroyed.

My expectation would be that `fleetctl destroy` actually destroys the unit completely, without retaining any state. Note that the `ExecStopPost` for this unit failed a few times when destroying the unit. Perhaps this causes the destroy process itself to fail, and leads to this stale information being left behind?

**Comment by scole-scea** [comment]
Ok, so this is really hitting us hard. One of my CoreOS clusters went down last night because services vanished into "No such file or directory" after GCE instances updated their coreOS installations and rebooted.

The error seems to be in the interaction between fleet and systemd, because that no-filename-specified "No such file" error comes from inside systemd... Something about a unit file still being a STUB when it tries to get loaded.

I've got a repeatable set of scripts that can recreate this state, but I don't have a development environment to poke around inside systemd. 

(For what it's worth: this is CoreOS 607; systemd 218).

I think we've hit the `fail` target in systemd's `unit_load` routine.
https://github.com/systemd/systemd/blob/v218/src/core/unit.c#L1237

**Comment by bcwaldon** [comment]
@scole-scea Given that this bug is almost a year old (and has likely been fixed), could you please file a new bug against github.com/coreos/fleet so we can effectively debug your specific failure case? I was just investigating a bug that sounds similar that could be the same as your issue: https://github.com/coreos/fleet/issues/1158

**Comment by scole-scea** [comment]
Will do.
