### ISSUE TITLE
Default useDNS to be 'No' on sshd_config

### ISSUE THREAD

**Issue by developerinlondon** [coreos/bugs#92]
We are making an unnecessary DNS lookup from CoreOS nodes every time we connect to it.

I'd propose to make the default setting for UseDNS be `No`.

From the manpage of `sshd_config(5)`:

```
 UseDNS  Specifies whether sshd(8) should look up the remote host name and
         check that the resolved host name for the remote IP address maps
         back to the very same IP address.  The default is “yes”.
Enabling this makes access from a location without proper (forward and reverse) DNS generate a warning in the logs.
```

So this doesn't prevent any attack except that it would need some qualified remote address of the client in order not to log any warning. Such a warning may help you in tracing down the attacker only if that PTR record makes any sense.

It is needed when you use FROM option in an authorized_keys file and you want to filter by names and not just IPs.

The FROM option in a line of an authorized_keys file allows you to limit hosts that can use a specific key.
This increases the ability of managing multiple servers that have access to each other without allowing clones of a machine to impersonate it's origin, usually unintentionally (leftover crontabs, human error).

(source: http://unix.stackexchange.com/questions/56941/what-is-the-point-of-sshd-usedns-option)

Additionally adding comments in the `sshd_config` and man page:

```
# UseDNS - Determines whether IP Address to Hostname lookup and comparison is performed
# Default value is No which avoids login delays when the remote client's DNS cannot be resolved
# Value of No implies that the usage of "from=" in authorized_keys will not support DNS host names but only IP addresses.
# Value of Yes supports host names in "from=" for authorized_keys. Additionally if the remote client's IP address does not match the resolved DNS host name (or could not be reverse lookup resolved) then a warning is logged.
# UseDNS Yes
```

**Comment by v173k** [comment]
This change had me searching for a while! It broke ssh logins to a sshd server that was using `username@hostname` as a parameter for `AllowUsers` in the sshd_config file. If `AllowUsers username@ip-address` was used logins worked.

The sshd_auth.log simply states:
`User <username> from <ip-address> not allowed because not listed in AllowUsers`

That is a little miss leading becase there is no mention of it not being able to resolve said hostname which is really the reason (isn't it?) why access was denied.

Perhaps something could be added in the sshd_config man page to alert users of the same. Something along the lines of: 

`If using "AllowUsers username@hostname" then "UseDNS yes" must be used otherwise clients are rejected from logging in because hostname will not be resolved.`

For the record I faced this problem when updating from OpenSSH v6.8p1-1  to v6.9p1-1
